import type { CollegeContentPack } from "./types";

// NIRF Engineering 2024 #64-75 — hand-authored, matches iit-madras.ts / eng-batch2-5.ts depth.

const iitPalakkad: CollegeContentPack = {
  slug: "indian-institute-of-technology-palakkad",
  college: {
    estd: 2015,
    website: "https://www.iitpkd.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹14 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Palakkad — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Palakkad NIRF #64 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Palakkad, established in 2015 as part of the third wave of new IITs, operates from a developing permanent campus near Palakkad, Kerala. Mentored initially by IIT Madras, it has built a research culture emphasising sustainability and rural-technology applications alongside its core B.Tech programmes, admitted through JEE Advanced.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "70", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Civil & Environmental Engineering", duration: "4 years", seats: "40", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹14 LPA", highestPackage: "₹45 LPA (indicative)", placedPct: "82" },
  recruiters: ["Amazon", "Microsoft", "Qualcomm", "Deloitte", "TCS", "Cognizant", "ONGC", "Samsung R&D"],
  highlights: [
    "Third-generation IIT (2015), mentored initially by IIT Madras",
    "Developing campus near Palakkad, Kerala, with a sustainability-focused research culture",
    "IIT brand and JEE Advanced admission at accessible cutoffs given its youth",
    "JEE Advanced is the sole admission route for B.Tech",
  ],
  faqs: [
    { question: "Was IIT Palakkad mentored by another IIT?", answer: "IIT Palakkad was initially mentored by IIT Madras during its early years, a common arrangement for newer IITs to accelerate faculty hiring, curriculum design, and academic quality benchmarks." },
    { question: "What is IIT Palakkad's CSE cutoff?", answer: "CSE closing ranks at IIT Palakkad have typically fallen in the 5,500-8,000 band (General) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Palakkad", body: "Indian Institute of Technology Palakkad was established in 2015 as part of the third wave of new IITs sanctioned by the Government of India. It was initially mentored by IIT Madras during its formative years, a common model used to help new IITs establish academic standards quickly. Its developing permanent campus is located near Palakkad, Kerala, running B.Tech programmes across Computer Science, Electrical, Mechanical, and Civil & Environmental Engineering.\n\nIIT Palakkad has built a research identity with particular emphasis on sustainability, rural technology, and environmental engineering, alongside its core computer science and engineering programmes." },
    { tab: "info", heading: "Campus & Location", body: "The Palakkad campus is being developed in phases in Kerala's Palakkad district, with academic and hostel infrastructure expanding as the institute matures. Kerala's strong educational infrastructure and connectivity support the institute's growth." },
    { tab: "info", heading: "Why Choose IIT Palakkad", body: "- IIT brand with mentorship pedigree from IIT Madras during its founding years\n- Distinctive sustainability and environmental-engineering research focus\n- Accessible JEE Advanced cutoffs relative to older IITs\n- Kerala location with strong regional educational infrastructure" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 70 | ₹8.0 L |\n| Electrical Engineering | 4 years | 60 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 60 | ₹8.0 L |\n| Civil & Environmental Engineering | 4 years | 40 | ₹8.0 L |\n\nFees follow the standard IIT structure; full tuition waivers apply for SC/ST, PwD, and income-eligible General/OBC students." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and General/OBC students with family income under ₹5 lakh/year, per common IIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "B.Tech admission is exclusively via JEE Advanced rank through JoSAA counselling. Candidates must qualify JEE Main, rank in the top ~2.5 lakh to be eligible for JEE Advanced, and register their preferences on JoSAA for seat allotment across multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Palakkad's placement cell draws software, core engineering, and analytics recruiters, with CSE graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 80s across recent years as the institute's placement network continues to mature." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Qualcomm, Samsung R&D (software/semiconductor)\n- TCS, Cognizant (IT services)\n- Deloitte (consulting/analytics)\n- ONGC and other core/PSU recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 5,500 – 8,000 |\n| Electrical Engineering | 10,000 – 14,000 |\n| Mechanical Engineering | 14,000 – 19,000 |\n| Civil & Environmental Engineering | 19,000 – 25,000 |\n\nRanges are indicative from recent JoSAA rounds; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Palakkad is ranked #64 in NIRF 2024 Engineering, a solid position for one of the newer IITs founded in 2015." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIT Palakkad provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity as the campus matures." },
  ],
};

const manipalJaipur: CollegeContentPack = {
  slug: "manipal-university-jaipur",
  college: {
    estd: 2011,
    website: "https://jaipur.manipal.edu",
    feesNum: 900000,
    feesLabel: "₹9.0 L",
    packageLabel: "₹6.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Manipal University Jaipur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Manipal University Jaipur NIRF #65 engineering: B.Tech courses, fees, MUJEE admission, placement stats, hostel and scholarship details.",
    about:
      "Manipal University Jaipur (MUJ), established in 2011 as part of the Manipal group of institutions, operates from a campus at Dehmi Kalan, near Jaipur, Rajasthan. Built on the reputation of the older Manipal Institute of Technology in Karnataka, MUJ has grown into a well-regarded private university across engineering, media, and management programmes in North India.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "360", feesLabel: "₹9.0 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "150", feesLabel: "₹9.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹7.5 L total" },
  ],
  placement: { avgPackage: "₹6.5 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "80" },
  recruiters: ["Amazon", "TCS", "Infosys", "Wipro", "Cognizant", "Deloitte", "HCL", "Capgemini"],
  highlights: [
    "Part of the Manipal group of institutions, established 2011 near Jaipur",
    "Benefits from the Manipal brand's placement and academic reputation",
    "Strong CSE and AI/ML specialisation offerings",
    "Admission via MUJEE (own test) or JEE Main score",
  ],
  faqs: [
    { question: "Is Manipal University Jaipur connected to MIT Manipal?", answer: "Yes — Manipal University Jaipur is part of the broader Manipal group of institutions, sharing academic frameworks and brand association with Manipal Institute of Technology in Karnataka, though it operates as an independent deemed university in Rajasthan." },
    { question: "What is MUJEE?", answer: "MUJEE (Manipal University Jaipur Entrance Examination) is MUJ's own online entrance test; applicants can alternatively use their JEE Main score for admission to select programmes." },
  ],
  sections: [
    { tab: "info", heading: "About Manipal University Jaipur", body: "Manipal University Jaipur was established in 2011 as part of the broader Manipal group of educational institutions, operating from a campus at Dehmi Kalan, near Jaipur, Rajasthan. It shares academic frameworks, quality benchmarks, and brand association with the older Manipal Institute of Technology in Karnataka, while functioning as an independent deemed university.\n\nMUJ runs a large School of Computer Science and Communication Engineering alongside programmes in Mechanical, Civil, and allied branches, along with strong media and management schools reflecting the broader Manipal group's multi-disciplinary model." },
    { tab: "info", heading: "Campus & Facilities", body: "The Dehmi Kalan campus spans a substantial site near Jaipur, with modern academic blocks, computer labs, hostels, and sports facilities built out since the university's 2011 founding." },
    { tab: "info", heading: "Why Choose Manipal University Jaipur", body: "- Benefits from the established Manipal group's academic and placement reputation\n- Strong CSE and AI/ML specialisation offerings\n- Modern campus infrastructure built from the ground up since 2011\n- Multiple admission routes (MUJEE, JEE Main) for flexibility" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 360 | ₹9.0 L |\n| CSE — AI & ML | 4 years | 150 | ₹9.5 L |\n| Electronics & Communication | 4 years | 150 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹7.5 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Manipal University Jaipur admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "MUJ offers merit-based fee waivers tied to MUJEE or JEE Main rank at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "MUJ offers admission through MUJEE (its own online entrance test) or direct admission based on JEE Main rank for a portion of seats. Applicants apply online, sit MUJEE if choosing that route, and are allotted seats through the university's own counselling process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by category)\n- Valid MUJEE rank or JEE Main score/rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "MUJ's placement cell runs campus drives across IT services with growing product-company and analytics participation, benefiting from association with the broader Manipal group's recruiter network. CSE and AI/ML post the strongest outcomes; overall placement percentage has generally stayed around 80% across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Wipro, Cognizant, HCL, Capgemini (bulk IT-services hiring)\n- Deloitte (analytics/consulting)\n- Regional Rajasthan and North India IT/service firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the MUJEE route, CSE admissions have typically required a rank within the top few thousand test-takers in recent years; for the JEE Main route, CSE cutoff percentiles have generally fallen in the 80-90 range. These are indicative — MUJ publishes exact cutoffs after each admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- MUJEE/JEE Main rank-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Education loan facilitation cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Manipal University Jaipur is ranked #65 in NIRF 2024 Engineering and also features in NIRF's Overall University category, a solid result for a university founded as recently as 2011." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MUJ provides on-campus hostel accommodation across its Dehmi Kalan campus, with multiple room-sharing options. Campus life includes technical and cultural fests, active sports facilities, and a growing international-student presence typical of the Manipal group's global outlook." },
  ],
};

const sathyabama: CollegeContentPack = {
  slug: "sathyabama-institute-of-science-and-technology",
  college: {
    estd: 1987,
    website: "https://www.sathyabama.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹4.2 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Sathyabama Institute of Science and Technology — Courses, Fees, Placements 2026",
    metaDescription: "Sathyabama Chennai NIRF #66 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Sathyabama Institute of Science and Technology, founded in 1987 and granted deemed-university status in 2001, operates from a large campus in Chennai, Tamil Nadu, known for its wide-ranging engineering programme spread including a notable Aeronautical Engineering department and satellite-building student projects run in collaboration with ISRO.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "480", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Aeronautical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "180", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹4.8 L total" },
  ],
  placement: { avgPackage: "₹4.2 LPA", highestPackage: "₹36 LPA (indicative)", placedPct: "76" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)", "L&T"],
  highlights: [
    "Deemed university since 2001, large campus in Chennai",
    "Notable Aeronautical Engineering programme with ISRO-linked student satellite projects",
    "Wide engineering programme spread across a large Chennai campus",
    "Admission via own entrance test or TNEA/JEE Main score",
  ],
  faqs: [
    { question: "Is Sathyabama good for Aeronautical Engineering?", answer: "Sathyabama's Aeronautical Engineering programme is one of its notable strengths, backed by student-satellite projects developed in collaboration with ISRO, giving students hands-on exposure uncommon among conventional private engineering colleges." },
    { question: "How is admission to Sathyabama done?", answer: "Sathyabama admits students through its own entrance examination, or directly via TNEA rank (Tamil Nadu domicile) or JEE Main score (out-of-state applicants)." },
  ],
  sections: [
    { tab: "info", heading: "About Sathyabama", body: "Sathyabama Institute of Science and Technology was founded in 1987 and granted deemed-to-be-university status in 2001. Its main campus is located in Chennai, Tamil Nadu, and the institute has built a wide-ranging engineering programme spread including Computer Science, Aeronautical Engineering, Electronics, and Mechanical branches.\n\nA notable feature of Sathyabama is its student-satellite programme, developed in collaboration with ISRO, which has given its Aeronautical and allied engineering students hands-on space-technology project experience uncommon among private engineering institutes." },
    { tab: "info", heading: "Campus & Facilities", body: "The Sathyabama campus in Chennai includes academic blocks, an aeronautical engineering lab and small aircraft/satellite project facilities, hostels, and sports infrastructure including a large indoor stadium." },
    { tab: "info", heading: "Why Choose Sathyabama", body: "- Notable Aeronautical Engineering programme with hands-on ISRO-linked satellite projects\n- Large, well-resourced Chennai campus with wide programme spread\n- Deemed-university flexibility in curriculum design\n- Multiple admission routes (own entrance test, TNEA, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 480 | ₹5.5 L |\n| Aeronautical Engineering | 4 years | 90 | ₹5.0 L |\n| Electronics & Communication | 4 years | 180 | ₹5.0 L |\n| Mechanical Engineering | 4 years | 120 | ₹4.8 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Sathyabama admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Sathyabama offers merit-based fee waivers tied to entrance rank or Class 12 percentage at admission. Fees are payable in semester instalments through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Sathyabama admits B.Tech students through its own entrance examination, or directly via TNEA rank (Tamil Nadu domicile) or JEE Main score (out-of-state applicants). Applicants apply online, and seats are allotted through Sathyabama's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score/rank via the chosen admission route\n- Documents: Class 10/12 mark sheets, entrance scorecard/TNEA rank card, community certificate (Tamil Nadu candidates), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Sathyabama's placement cell runs drives concentrated in IT services, with CSE posting the strongest outcomes and Aeronautical Engineering graduates finding niche opportunities in aviation and defence-adjacent sectors. Overall placement percentage has generally stayed in the mid-70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- L&T (core engineering)\n- Amazon for select high-performing CSE graduates\n- Regional Chennai IT and aerospace-adjacent firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the TNEA route, CSE cutoff scores have typically required a strong Class 12 cutoff (out of 200) in recent years for open category; for the university's own entrance test, ranks within the top few thousand test-takers are typically needed for CSE. Confirm current-year cutoffs directly with Sathyabama admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/Class 12-percentage merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Tamil Nadu state government scholarship schemes for eligible domicile students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Sathyabama Institute of Science and Technology is ranked #66 in NIRF 2024 Engineering and also features in NIRF's Overall University category." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Sathyabama provides on-campus hostel accommodation for men and women across its Chennai campus. Student life includes technical fests centred on its aeronautical and satellite projects, plus cultural events and active sports facilities." },
  ],
};

const psgTech: CollegeContentPack = {
  slug: "psg-college-of-technology",
  college: {
    estd: 1951,
    website: "https://www.psgtech.edu",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹6.5 LPA",
    affiliation: "Autonomous College, Anna University",
    approvedBy: "UGC, AICTE",
    metaTitle: "PSG College of Technology — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "PSG College of Technology Coimbatore NIRF #67 engineering: B.Tech courses, fees, TNEA admission, placement stats, hostel and scholarship details.",
    about:
      "PSG College of Technology, founded in 1951 by the PSG & Sons' Charities Trust in Coimbatore, Tamil Nadu, is one of South India's most respected autonomous engineering colleges, with a long-standing reputation for academic rigour, strong industry ties (particularly with Coimbatore's textile-machinery and manufacturing base), and a research culture unusual for a non-deemed private college.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "240", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Information Technology", duration: "4 years", seats: "120", feesLabel: "₹4.8 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "180", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Electrical & Electronics", duration: "4 years", seats: "120", feesLabel: "₹4.5 L total" },
  ],
  placement: { avgPackage: "₹6.5 LPA", highestPackage: "₹45 LPA (indicative)", placedPct: "88" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Zoho", "L&T", "Amazon (select roles)", "Wipro", "TAFE"],
  highlights: [
    "Founded 1951, one of South India's most respected autonomous engineering colleges",
    "Strong industry ties with Coimbatore's textile-machinery and manufacturing base",
    "Consistently high placement percentage with a research culture unusual for a private college",
    "Admission via TNEA (Tamil Nadu Engineering Admissions) counselling",
  ],
  faqs: [
    { question: "Is PSG Tech a good college?", answer: "PSG College of Technology is widely regarded as one of the best non-deemed private engineering colleges in South India, with a long academic history, strong industry ties, and consistently high placement outcomes, particularly in Mechanical Engineering and Computer Science." },
    { question: "How is admission to PSG Tech done?", answer: "The bulk of PSG Tech's seats are filled through TNEA (Tamil Nadu Engineering Admissions) counselling based on Class 12 cutoff marks, with a smaller management quota for other candidates." },
  ],
  sections: [
    { tab: "info", heading: "About PSG College of Technology", body: "PSG College of Technology was founded in 1951 by the PSG & Sons' Charities Trust in Coimbatore, Tamil Nadu — a city long known as a hub for textile machinery, pumps, and precision manufacturing. As an autonomous college affiliated with Anna University, PSG Tech has built one of South India's most respected engineering reputations over seven decades, with particular strength in Mechanical Engineering, Computer Science, and Production Engineering.\n\nPSG Tech's close ties to Coimbatore's dense manufacturing ecosystem have historically shaped a strong industry-linked curriculum and research culture, alongside consistently competitive placement outcomes for a non-deemed private college." },
    { tab: "info", heading: "Campus & Location", body: "The PSG Tech campus in Coimbatore spans a well-established site with departmental blocks, workshops, and a central library built up over more than 70 years. Coimbatore's manufacturing-industry density gives the college strong access to core-engineering internships and recruiters." },
    { tab: "info", heading: "Why Choose PSG College of Technology", body: "- Seven decades of academic reputation and strong South Indian industry ties\n- Particularly strong Mechanical Engineering and Production Engineering programmes\n- Consistently high placement percentage among non-deemed private colleges\n- Coimbatore location within a dense manufacturing and textile-machinery industrial base" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 240 | ₹5.0 L |\n| Information Technology | 4 years | 120 | ₹4.8 L |\n| Mechanical Engineering | 4 years | 180 | ₹4.5 L |\n| Electrical & Electronics | 4 years | 120 | ₹4.5 L |\n\nFees are set per Anna University/Tamil Nadu government norms for self-financing colleges; confirm current-year figures with PSG Tech admissions." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "TNEA-counselled seats follow government-regulated fee slabs; management-quota seats carry a separate fee structure. Fees are payable per semester through the college's designated bank channels." },
    { tab: "admissions", heading: "Admission Process (TNEA)", body: "The bulk of PSG Tech's seats are filled through TNEA (Tamil Nadu Engineering Admissions) counselling, based on a normalised Class 12 cutoff score (out of 200) for Tamil Nadu domicile students. A smaller share of seats is available under the management quota, filled by PSG Tech's own admission process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per TNEA norms\n- TNEA cutoff score/rank for counselling-quota seats\n- Documents: Class 10/12 mark sheets, TNEA application/rank card, community certificate (Tamil Nadu candidates), transfer certificate, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "PSG Tech's placement cell runs strong drives across IT services and core manufacturing recruiters, reflecting both its Computer Science and its historically strong Mechanical Engineering reputation. Overall placement percentage has generally stayed in the mid-to-high 80s across recent years, among the best for a non-deemed private college in Tamil Nadu." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro (bulk IT-services hiring)\n- Zoho (select product-engineering roles)\n- L&T, TAFE (core/manufacturing — reflecting the Mechanical Engineering programme's strength)\n- Amazon for select high-performing CSE graduates" },
    { tab: "cutoffs", heading: "TNEA Cutoffs (Indicative)", body: "| Branch | Approx. TNEA Cutoff (Open Category, out of 200) |\n|---|---|\n| Computer Science & Engineering | 193 – 198 |\n| Information Technology | 188 – 194 |\n| Mechanical Engineering | 175 – 185 |\n| Electrical & Electronics | 178 – 188 |\n\nRanges are indicative from recent TNEA counselling years; exact cutoffs vary by round and category, confirm on the official TNEA portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Tamil Nadu government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible students\n- PSG & Sons' Charities Trust merit scholarships for top academic performers\n- Continuing merit scholarships tied to semester GPA\n- Need-based financial assistance through trust-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "PSG College of Technology is ranked #67 in NIRF 2024 Engineering — a strong, long-held position for a self-financing, non-deemed private college with a seven-decade academic history." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "PSG Tech provides on-campus hostel accommodation for both men and women. Student life includes the annual technical symposium, cultural fest, and a strong sports and alumni-network culture reflecting the college's long institutional history." },
  ],
};

const nitMeghalaya: CollegeContentPack = {
  slug: "national-institute-of-technology-meghalaya",
  college: {
    estd: 2010,
    website: "https://www.nitm.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹8 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Meghalaya — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Meghalaya Shillong NIRF #68 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Meghalaya, established in 2010 as one of the newer NITs formed under the National Institutes of Technology Act, operates from a campus in Shillong, Meghalaya. As one of the youngest NITs, it serves as a key technical institute for India's Northeast region, running core B.Tech programmes admitted via JoSAA.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "50", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "50", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "40", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹8 LPA", highestPackage: "₹36 LPA (indicative)", placedPct: "75" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Cognizant", "Deloitte", "HCL"],
  highlights: [
    "One of the newer NITs (2010), located in Shillong, Meghalaya",
    "Key technical institute serving India's Northeast region",
    "Growing CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Meghalaya a good option?", answer: "As one of the newer NITs, NIT Meghalaya's infrastructure and placement network are still developing relative to older NITs, but it carries the NIT brand and JoSAA admission credibility, with a distinctive role serving the Northeast region." },
    { question: "What is NIT Meghalaya's CSE cutoff?", answer: "CSE closing ranks at NIT Meghalaya have typically fallen in the 22,000-28,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Meghalaya", body: "National Institute of Technology, Meghalaya was established in 2010 as one of the newer NITs sanctioned under the National Institutes of Technology Act, 2007. Located in Shillong, Meghalaya, it runs undergraduate programmes across Computer Science, Electronics & Communication, Mechanical, and Civil Engineering, serving as a key technical institute for India's Northeast region alongside NIT Silchar.\n\nAs a young institute, NIT Meghalaya is still building out its permanent infrastructure and research profile, but its NIT brand and JoSAA-based admission give it strong national credibility." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Meghalaya campus in Shillong is being developed in phases, with academic blocks, hostels, and laboratory facilities expanding as the institute matures. Shillong's hill-station setting gives the campus a cooler climate than most plains-based technical institutes." },
    { tab: "info", heading: "Why Choose NIT Meghalaya", body: "- NIT brand and JoSAA admission credibility for a Northeast-region institute\n- Distinctive Shillong hill-station location and climate\n- Growing placement network as the institute matures\n- Comparatively accessible JoSAA cutoffs relative to older, more established NITs" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 60 | ₹5.5 L |\n| Electronics & Communication | 4 years | 50 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 50 | ₹5.5 L |\n| Civil Engineering | 4 years | 40 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Meghalaya's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Meghalaya's placement cell draws IT-services recruiters, with CSE graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 70s across recent years as the institute's placement network continues to grow." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 22,000 – 28,000 |\n| Electronics & Communication | 35,000 – 42,000 |\n| Mechanical Engineering | 48,000 – 58,000 |\n| Civil Engineering | 55,000 – 65,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Northeast-region specific government scholarship schemes for eligible students\n- Institute merit scholarships for top academic performers" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Meghalaya is ranked #68 in NIRF 2024 Engineering, a solid position for one of the newer NITs founded in 2010." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Meghalaya provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity reflecting the institute's Northeast setting." },
  ],
};

const vtu: CollegeContentPack = {
  slug: "visvesvaraya-technological-university",
  college: {
    estd: 1998,
    website: "https://vtu.ac.in",
    feesNum: 400000,
    feesLabel: "₹4.0 L",
    packageLabel: "₹4.5 LPA",
    affiliation: "State Government University, Karnataka",
    approvedBy: "UGC, AICTE",
    metaTitle: "Visvesvaraya Technological University (VTU) — Courses, Fees, Placements 2026",
    metaDescription: "VTU Belgaum NIRF #69 engineering: B.Tech affiliated colleges, fees, KCET/COMEDK admission, placement details, and scholarship info.",
    about:
      "Visvesvaraya Technological University (VTU), established in 1998 and headquartered in Belgaum, Karnataka, is a state government affiliating university overseeing engineering education across more than 200 affiliated colleges throughout Karnataka. Rather than a single-campus institute, VTU's NIRF ranking reflects the aggregate output of its vast affiliated-college network, named after the pioneering engineer Sir M. Visvesvaraya.",
  },
  courses: [
    { name: "B.E. Computer Science & Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-4 L/year" },
    { name: "B.E. Electronics & Communication (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-3.5 L/year" },
    { name: "B.E. Mechanical Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-3 L/year" },
    { name: "B.E. Civil Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-3 L/year" },
  ],
  placement: { avgPackage: "₹4.5 LPA", highestPackage: "Varies significantly by affiliated college", placedPct: "70" },
  recruiters: ["TCS", "Infosys", "Wipro", "Cognizant", "Accenture", "HCL", "L&T"],
  highlights: [
    "State affiliating university headquartered in Belgaum, Karnataka, established 1998",
    "Oversees engineering education across 200+ affiliated colleges statewide",
    "Named after pioneering Indian engineer Sir M. Visvesvaraya",
    "Admission and outcomes vary significantly by individual affiliated college",
  ],
  faqs: [
    { question: "Is VTU a single college or a university system?", answer: "VTU is a state affiliating university, not a single-campus institute — it sets curriculum, conducts examinations, and confers degrees for a network of over 200 engineering colleges across Karnataka, so admission, fees, and placement outcomes vary substantially by the specific affiliated college a student attends." },
    { question: "How do I get admission to a VTU-affiliated college?", answer: "Admission to VTU-affiliated colleges is primarily through Karnataka CET (KCET) or COMEDK UGET, Karnataka's state-level engineering entrance exams, with individual colleges also running management-quota admissions." },
  ],
  sections: [
    { tab: "info", heading: "About VTU", body: "Visvesvaraya Technological University was established in 1998, headquartered in Belgaum (Belagavi), Karnataka, and named after the celebrated Indian engineer and statesman Sir M. Visvesvaraya. Unlike most institutes on this list, VTU is a state affiliating university rather than a single-campus college — it sets curriculum standards, conducts university-wide examinations, and confers degrees across a network of more than 200 affiliated engineering colleges throughout Karnataka.\n\nVTU's NIRF Engineering ranking reflects the aggregate academic and research output of this large affiliated-college network rather than a single institutional campus, making it structurally different from every other entry in this list." },
    { tab: "info", heading: "University Structure", body: "VTU's affiliated colleges span a wide quality range, from well-regarded institutions like RV College of Engineering and BMS College of Engineering to smaller regional colleges. Prospective students should evaluate the specific affiliated college they are applying to — its placement record, faculty, and infrastructure — rather than relying solely on VTU's aggregate university-level ranking." },
    { tab: "info", heading: "Why Consider a VTU-Affiliated College", body: "- Wide choice of affiliated colleges across Karnataka, from top-tier to regional institutions\n- Standardised curriculum and examination system across the network\n- Multiple admission routes (KCET, COMEDK, management quota) depending on the college\n- Fee levels generally lower than deemed/private universities outside the affiliating system" },
    { tab: "courses-fees", heading: "Programmes & Fee Structure (Varies by College)", body: "| Programme | Duration | Fee Range (approx., varies by college) |\n|---|---|---|\n| Computer Science & Engineering | 4 years | ₹1 L – ₹4 L per year |\n| Electronics & Communication | 4 years | ₹1 L – ₹3.5 L per year |\n| Mechanical Engineering | 4 years | ₹1 L – ₹3 L per year |\n| Civil Engineering | 4 years | ₹1 L – ₹3 L per year |\n\nFees vary substantially by the specific affiliated college and whether the seat is filled via KCET (government-regulated fee) or management quota (higher fee); confirm the exact figure with your chosen college." },
    { tab: "courses-fees", heading: "Fee Regulation", body: "KCET-counselled seats at VTU-affiliated colleges follow Karnataka government-regulated fee slabs, which are typically lower than management-quota or COMEDK seats at the same college. Each affiliated college publishes its own fee structure per admission category." },
    { tab: "admissions", heading: "Admission Process", body: "Admission to VTU-affiliated colleges is primarily through Karnataka CET (KCET) for Karnataka-domicile students, or COMEDK UGET for a broader applicant pool including out-of-state candidates. Some colleges also run a management-quota admission process directly. Applicants should apply to their specific college of choice through the relevant counselling process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per KCET/COMEDK norms\n- Valid KCET or COMEDK UGET rank/score\n- Documents: Class 10/12 mark sheets, entrance scorecard, category/domicile certificate (for KCET), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Placement outcomes across VTU-affiliated colleges vary widely by institution — top affiliated colleges post strong IT-services and even some product-company placement, while smaller regional colleges see more modest outcomes. Prospective students should review the specific college's own placement report rather than relying on a university-wide aggregate." },
    { tab: "placements", heading: "Common Recruiters Across the Network", body: "- TCS, Infosys, Wipro, Cognizant, Accenture, HCL (the most common recruiters across VTU-affiliated colleges' IT-services drives)\n- L&T and regional Karnataka manufacturing firms for core branches\n- Product-company and analytics recruiters concentrate at the network's top-tier colleges" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative, Varies by College)", body: "KCET and COMEDK cutoff ranks vary enormously across the 200+ VTU-affiliated colleges — top-tier colleges can require ranks in the low thousands for CSE, while many regional colleges admit at much higher (less competitive) ranks. Always check the specific college's cutoff trend rather than a university-wide figure." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Karnataka state government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible KCET students\n- Individual affiliated colleges often run their own merit scholarships\n- Central government scholarship schemes for eligible students\n- Fee concessions vary by college — check directly with your chosen institution" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Visvesvaraya Technological University is ranked #69 in NIRF 2024 Engineering as an aggregate university-level ranking; individual VTU-affiliated colleges may separately hold their own NIRF rankings and should be evaluated independently." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Hostel availability, quality, and campus life vary significantly by the specific VTU-affiliated college — most established colleges offer on-campus hostels, while smaller ones may have more limited accommodation. Check directly with your chosen college for specifics." },
  ],
};

const uohyd: CollegeContentPack = {
  slug: "university-of-hyderabad",
  college: {
    estd: 1974,
    website: "https://uohyd.ac.in",
    feesNum: 300000,
    feesLabel: "₹3.0 L",
    packageLabel: "₹9 LPA",
    affiliation: "Central University",
    approvedBy: "UGC, AICTE",
    metaTitle: "University of Hyderabad — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "University of Hyderabad NIRF #70 engineering: B.Tech School of Engineering Sciences courses, fees, admission, placement details.",
    about:
      "University of Hyderabad, established in 1974 as a central university, is primarily known for its strength in basic sciences, humanities, and research programmes, but also runs a smaller School of Engineering Sciences and Technology offering B.Tech programmes. Its low, government-subsidised fees and strong research culture make it a distinctive, if niche, engineering option within a larger multi-disciplinary research university.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "40", feesLabel: "₹3.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "40", feesLabel: "₹3.0 L total" },
  ],
  placement: { avgPackage: "₹9 LPA", highestPackage: "₹32 LPA (indicative)", placedPct: "80" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Deloitte", "Cognizant", "Wipro"],
  highlights: [
    "Central university established 1974, primarily known for sciences and humanities research",
    "Smaller, research-oriented School of Engineering Sciences and Technology",
    "Very low, government-subsidised fees relative to placement outcomes",
    "Admission via JEE Main score for its limited B.Tech intake",
  ],
  faqs: [
    { question: "Is University of Hyderabad mainly an engineering college?", answer: "No — University of Hyderabad is primarily a research-focused central university known for basic sciences, humanities, and social sciences; its engineering programmes (B.Tech CSE and Electronics) are a smaller, more recently added offering within a much larger multi-disciplinary institution." },
    { question: "What is the fee for B.Tech at University of Hyderabad?", answer: "As a central university, fees are heavily government-subsidised — total 4-year B.Tech fees are typically under ₹3.5 lakh, among the lowest of any NIRF-ranked engineering programme." },
  ],
  sections: [
    { tab: "info", heading: "About University of Hyderabad", body: "University of Hyderabad was established in 1974 as a central university, and has built its primary academic reputation around basic sciences, humanities, social sciences, and doctoral research rather than engineering. Its School of Engineering Sciences and Technology is a smaller, more recently developed unit offering B.Tech programmes in Computer Science and Electronics & Communication Engineering, benefiting from the university's broader research infrastructure and faculty.\n\nAs a central university, fees remain heavily subsidised by the Government of India, making its engineering programme one of the lowest-cost, research-oriented B.Tech options among NIRF-ranked institutes." },
    { tab: "info", heading: "Campus & Location", body: "The University of Hyderabad campus is a large, forested 2,300-acre site in Gachibowli, Hyderabad, known for its green, wildlife-rich setting unusual for an urban university. The engineering school shares this campus with the university's science, arts, and humanities departments." },
    { tab: "info", heading: "Why Choose University of Hyderabad Engineering", body: "- Very low, government-subsidised fees relative to placement outcomes\n- Access to a large, research-intensive multi-disciplinary university environment\n- Gachibowli location within Hyderabad's tech corridor\n- Small, selective B.Tech batches with close faculty interaction" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 40 | ₹3.0 L |\n| Electronics & Communication | 4 years | 40 | ₹3.0 L |\n\nAs a central university, fees remain heavily subsidised; confirm current-year figures on the official University of Hyderabad admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "Additional fee concessions apply for SC/ST/OBC/EWS students under central government norms. Fees are payable per semester via the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "B.Tech admission to University of Hyderabad's School of Engineering Sciences and Technology is based on JEE Main rank, with a limited number of seats filled through the university's own counselling process. Applicants apply through the university's admission portal alongside their JEE Main application." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per university norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "Given its small B.Tech batch sizes, University of Hyderabad's engineering placement outcomes are comparatively strong on a percentage basis, with CSE graduates drawing interest from IT-services and select product-company recruiters. Overall placement percentage has generally stayed around 80% across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Deloitte and other analytics/consulting recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "Given the very small B.Tech intake (around 40 seats per branch), JEE Main cutoff percentiles for CSE have typically required a percentile in the 90-95 range in recent years. These figures are indicative — confirm current-year cutoffs on the official admissions portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Central government fee concessions for SC/ST/OBC/EWS-eligible students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- University research-linked financial assistance for high-performing students\n- UGC and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "University of Hyderabad is ranked #70 in NIRF 2024 Engineering, though the university's stronger NIRF presence is in its Overall University and Research categories, reflecting its primary identity as a sciences-and-humanities research institution." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "University of Hyderabad provides on-campus hostel accommodation across its large, green Gachibowli campus. Student life reflects the university's broader multi-disciplinary research culture, with strong participation in inter-departmental academic and cultural events alongside standard engineering-student activities." },
  ],
};

const nitRaipur: CollegeContentPack = {
  slug: "national-institute-of-technology-raipur",
  college: {
    estd: 1956,
    website: "https://www.nitrr.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹8.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Raipur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Raipur NIRF #71 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Raipur, tracing its origins to 1956 as a Government Engineering College and elevated to NIT status in 2005, is Chhattisgarh's premier technical institute. Located in Raipur, it draws students nationwide through JoSAA, with notable strength in Mining and Metallurgical Engineering given the region's mineral-rich industrial base.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "110", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mining Engineering", duration: "4 years", seats: "40", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹8.5 LPA", highestPackage: "₹38 LPA (indicative)", placedPct: "78" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Bhilai Steel Plant (SAIL)", "Cognizant", "L&T"],
  highlights: [
    "Chhattisgarh's premier NIT, tracing to 1956, NIT status since 2005",
    "Notable Mining Engineering strength given the region's mineral-rich industrial base",
    "Steady CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Raipur good for Mining Engineering?", answer: "NIT Raipur's Mining Engineering programme benefits from Chhattisgarh's mineral-rich industrial base, with strong ties to regional steel and mining recruiters including SAIL's Bhilai Steel Plant." },
    { question: "What is NIT Raipur's CSE cutoff?", answer: "CSE closing ranks at NIT Raipur have typically fallen in the 14,000-18,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Raipur", body: "National Institute of Technology, Raipur traces its origins to 1956 as a Government Engineering College and was granted National Institute of Technology status in 2005. Located in Raipur, Chhattisgarh — a state with a substantial mining and steel-industry base — NIT Raipur runs undergraduate programmes across Computer Science, Electronics, Mining, Mechanical, and Civil Engineering.\n\nThe institute has built particular strength in Mining Engineering, benefiting from Chhattisgarh's mineral-rich industrial corridor, alongside steadily growing Computer Science outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Raipur campus spans a substantial site in Raipur, Chhattisgarh's capital, with academic blocks, hostels, a central library, and workshop facilities. The region's mining and steel industry provides regular internship and recruitment pipelines for core-branch students." },
    { tab: "info", heading: "Why Choose NIT Raipur", body: "- Notable Mining Engineering strength tied to Chhattisgarh's mineral-rich industrial base\n- NIT brand and infrastructure with accessible JoSAA cutoffs relative to older NITs\n- Steady CSE and Electronics placement outcomes\n- Central Raipur location with strong regional connectivity" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 110 | ₹5.5 L |\n| Electronics & Communication | 4 years | 90 | ₹5.5 L |\n| Mining Engineering | 4 years | 40 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Raipur's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Raipur's placement cell draws IT-services and core-industrial recruiters, with strong participation from regional steel and mining companies alongside growing software-sector interest. Overall placement percentage has generally stayed in the high 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant (bulk IT-services hiring)\n- Amazon for select CSE roles\n- SAIL (Bhilai Steel Plant), L&T (core/mining/manufacturing)\n- Regional Chhattisgarh industrial and infrastructure firms" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 14,000 – 18,000 |\n| Electronics & Communication | 22,000 – 28,000 |\n| Mechanical Engineering | 32,000 – 40,000 |\n| Mining Engineering | 45,000 – 55,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Chhattisgarh state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Raipur is ranked #71 in NIRF 2024 Engineering, holding steady as Chhattisgarh's top-ranked technical institute." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Raipur provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const manitBhopal: CollegeContentPack = {
  slug: "maulana-azad-national-institute-of-technology",
  college: {
    estd: 1960,
    website: "https://www.manit.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹10 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "MANIT Bhopal — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Maulana Azad NIT Bhopal NIRF #72 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "Maulana Azad National Institute of Technology (MANIT), established in 1960 as a Regional Engineering College and elevated to NIT status in 2002, is Madhya Pradesh's premier technical institute. Located in Bhopal, MANIT draws students nationwide through JoSAA, named after India's first Education Minister, Maulana Abul Kalam Azad.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "100", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹10 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "82" },
  recruiters: ["Amazon", "TCS", "Infosys", "L&T", "BHEL", "Deloitte", "Cognizant", "Samsung R&D"],
  highlights: [
    "Madhya Pradesh's premier NIT, founded 1960, NIT status since 2002",
    "Named after Maulana Abul Kalam Azad, India's first Education Minister",
    "Solid CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is MANIT Bhopal a good NIT?", answer: "MANIT Bhopal is consistently ranked among the top 15-20 NITs nationally, with solid CSE and Electronics placement outcomes and a strong regional reputation across Madhya Pradesh and central India." },
    { question: "What is MANIT's CSE cutoff?", answer: "CSE closing ranks at MANIT Bhopal have typically fallen in the 7,000-9,500 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About MANIT Bhopal", body: "Maulana Azad National Institute of Technology was established in 1960 as a Regional Engineering College and was granted National Institute of Technology status in 2002, named after Maulana Abul Kalam Azad, India's first Minister of Education. Located in Bhopal, Madhya Pradesh, MANIT is the state's premier technical institute, running undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, and Civil Engineering.\n\nMANIT has built a strong regional reputation across central India, with steady research output alongside its undergraduate placement outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The MANIT campus spans a substantial site in Bhopal, Madhya Pradesh's capital, with academic blocks, hostels, a central library, and workshop facilities. Bhopal's central location gives the institute good connectivity across India." },
    { tab: "info", heading: "Why Choose MANIT Bhopal", body: "- Among the top 20 NITs nationally, with solid CSE and Electronics outcomes\n- Madhya Pradesh's premier technical institute with strong regional recognition\n- NIT brand and infrastructure with accessible JoSAA cutoffs relative to older NITs\n- Central Bhopal location with strong national connectivity" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.5 L |\n| Electronics & Communication | 4 years | 100 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n| Civil Engineering | 4 years | 70 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to MANIT's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "MANIT's placement cell runs solid campus drives across software, core engineering, and analytics recruiters, with CSE and Electronics posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 80s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Samsung R&D (software/semiconductor)\n- TCS, Infosys (bulk IT-services hiring)\n- L&T, BHEL (core/PSU)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 7,000 – 9,500 |\n| Electronics & Communication | 13,000 – 17,000 |\n| Mechanical Engineering | 19,000 – 24,000 |\n| Civil Engineering | 25,000 – 32,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Madhya Pradesh state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "MANIT Bhopal is ranked #72 in NIRF 2024 Engineering, holding a consistent position among the top 20 NITs nationally." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MANIT provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const iitBhilai: CollegeContentPack = {
  slug: "indian-institute-of-technology-bhilai",
  college: {
    estd: 2016,
    website: "https://www.iitbhilai.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹12 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Bhilai — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Bhilai NIRF #73 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Bhilai, established in 2016 as part of the third wave of new IITs, operates from a developing permanent campus near Raipur, Chhattisgarh. Initially mentored by IIT Delhi, it serves as the flagship technical institute for Chhattisgarh, running core B.Tech programmes admitted via JEE Advanced.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "70", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Data Science & Artificial Intelligence", duration: "4 years", seats: "30", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹12 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Deloitte", "Cognizant", "SAIL", "Samsung R&D"],
  highlights: [
    "Third-generation IIT (2016), initially mentored by IIT Delhi",
    "Developing campus near Raipur, Chhattisgarh",
    "Distinctive B.Tech in Data Science and Artificial Intelligence",
    "JEE Advanced is the sole admission route for B.Tech",
  ],
  faqs: [
    { question: "Was IIT Bhilai mentored by another IIT?", answer: "IIT Bhilai was initially mentored by IIT Delhi during its early years, a common arrangement for newer IITs to accelerate faculty hiring, curriculum design, and academic quality benchmarks." },
    { question: "What is IIT Bhilai's CSE cutoff?", answer: "CSE closing ranks at IIT Bhilai have typically fallen in the 7,500-10,000 band (General) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Bhilai", body: "Indian Institute of Technology Bhilai was established in 2016 as part of the third wave of new IITs sanctioned by the Government of India. It was initially mentored by IIT Delhi during its formative years, and its developing permanent campus is located near Raipur, Chhattisgarh, running B.Tech programmes across Computer Science, Electrical, Mechanical, and a distinctive Data Science and Artificial Intelligence programme.\n\nAs the flagship technical institute for Chhattisgarh, IIT Bhilai carries strategic importance for the region's STEM education, alongside the standard IIT brand, faculty hiring standards, and JEE Advanced-based admission process." },
    { tab: "info", heading: "Campus & Location", body: "The campus near Raipur is being developed in phases, with academic and hostel infrastructure expanding as the institute matures. Raipur's connectivity within central India provides reasonable regional access despite the institute's relative youth." },
    { tab: "info", heading: "Why Choose IIT Bhilai", body: "- IIT brand with mentorship pedigree from IIT Delhi during its founding years\n- Distinctive Data Science and Artificial Intelligence B.Tech programme\n- Accessible JEE Advanced cutoffs relative to older IITs\n- Flagship technical institute for Chhattisgarh" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 70 | ₹8.0 L |\n| Electrical Engineering | 4 years | 60 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 60 | ₹8.0 L |\n| Data Science & Artificial Intelligence | 4 years | 30 | ₹8.0 L |\n\nFees follow the standard IIT structure; full tuition waivers apply for SC/ST, PwD, and income-eligible General/OBC students." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and General/OBC students with family income under ₹5 lakh/year, per common IIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "B.Tech admission is exclusively via JEE Advanced rank through JoSAA counselling. Candidates must qualify JEE Main, rank in the top ~2.5 lakh to be eligible for JEE Advanced, and register their preferences on JoSAA for seat allotment across multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Bhilai's placement cell draws software, core engineering, and analytics recruiters, with CSE and Data Science & AI graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s across recent years as the institute's placement network continues to mature." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Samsung R&D (software/semiconductor)\n- TCS, Infosys, Cognizant (IT services)\n- Deloitte (consulting/analytics)\n- SAIL and other regional core/PSU recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 7,500 – 10,000 |\n| Data Science & Artificial Intelligence | 9,000 – 12,000 |\n| Electrical Engineering | 13,000 – 17,500 |\n| Mechanical Engineering | 17,000 – 22,000 |\n\nRanges are indicative from recent JoSAA rounds; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Bhilai is ranked #73 in NIRF 2024 Engineering, a solid position for one of the newest IITs founded in 2016." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIT Bhilai provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity as the campus matures." },
  ],
};

const iiitBangalore: CollegeContentPack = {
  slug: "international-institute-of-information-technology-bangalore",
  college: {
    estd: 1999,
    website: "https://www.iiitb.ac.in",
    feesNum: 950000,
    feesLabel: "₹9.5 L",
    packageLabel: "₹18 LPA",
    affiliation: "Deemed University (Elite, State-supported)",
    approvedBy: "UGC, AICTE",
    metaTitle: "IIIT Bangalore — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIIT Bangalore NIRF #74 engineering: B.Tech CSE/ECE courses, fees, admission via JEE Main, placement package, hostel details.",
    about:
      "International Institute of Information Technology, Bangalore (IIIT-B), founded in 1999 with support from the Karnataka government and the IT industry, is a research-focused, elite computer science institute located in Electronics City, Bengaluru's established tech hub. It runs a comparatively small B.Tech intake alongside larger postgraduate programmes, with a strong emphasis on research and industry-linked projects.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "60", feesLabel: "₹9.5 L total" },
    { name: "B.Tech Electronics & Communication Engineering", duration: "4 years", seats: "40", feesLabel: "₹9.5 L total" },
  ],
  placement: { avgPackage: "₹18 LPA", highestPackage: "₹65 LPA (indicative)", placedPct: "92" },
  recruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "Adobe", "Flipkart", "Qualcomm", "Sprinklr"],
  highlights: [
    "Elite, research-focused CS institute founded 1999 in Electronics City, Bengaluru",
    "Small, highly selective B.Tech intake alongside larger postgraduate research programmes",
    "Placement outcomes among the strongest of any engineering institute in this ranking band",
    "Admission via JEE Main score for its limited B.Tech seats",
  ],
  faqs: [
    { question: "How selective is IIIT Bangalore's B.Tech programme?", answer: "IIIT-B's B.Tech intake is deliberately small (around 100 seats total across CSE and ECE), making admission highly competitive and giving admitted students close access to the institute's strong faculty and research infrastructure." },
    { question: "Is IIIT Bangalore mainly a postgraduate institute?", answer: "IIIT-B is well known for its postgraduate (M.Tech) and research programmes, which form a larger share of its student body than its undergraduate B.Tech intake, giving undergraduates unusual exposure to a research-heavy academic culture." },
  ],
  sections: [
    { tab: "info", heading: "About IIIT Bangalore", body: "International Institute of Information Technology, Bangalore was founded in 1999 with support from the Government of Karnataka and the IT industry, established as a research-focused institute dedicated to information technology. Located in Electronics City, one of Bengaluru's earliest and most established technology hubs, IIIT-B runs a comparatively small B.Tech programme in Computer Science and Electronics & Communication Engineering, alongside larger and well-regarded postgraduate (M.Tech) and doctoral research programmes.\n\nThe institute's identity leans heavily toward research and industry-linked projects, giving even undergraduate students exposure to a graduate-level research culture uncommon at institutes of similar B.Tech intake size." },
    { tab: "info", heading: "Campus & Location", body: "The IIIT-B campus in Electronics City sits within Bengaluru's dense established technology corridor, surrounded by major IT company campuses, giving students strong access to internships and industry projects throughout their degree." },
    { tab: "info", heading: "Why Choose IIIT Bangalore", body: "- Elite, research-focused CS institute with placement outcomes among the strongest in this ranking band\n- Small, highly selective B.Tech batches with close faculty access\n- Electronics City location within Bengaluru's established tech corridor\n- Undergraduate exposure to a graduate-level research culture" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 60 | ₹9.5 L |\n| Electronics & Communication Engineering | 4 years | 40 | ₹9.5 L |\n\nFees are charged per year and reflect IIIT-B's self-supporting deemed-university model; confirm current-year figures on the official admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "IIIT-B offers need-based and merit-based fee waivers for eligible Indian students. Fees are payable per semester through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "IIIT-B admits its B.Tech students based on JEE Main rank, with a limited number of seats filled through the institute's own centralised admission process. Applicants apply through the institute's admission portal alongside their JEE Main application." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per IIIT-B norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIIT-B posts placement outcomes among the strongest of any institute in this NIRF ranking band, with the large majority of its small B.Tech batch placed in software engineering and research roles at leading technology and finance firms. High selectivity at admission combined with a research-heavy curriculum contributes to consistently strong average and median packages." },
    { tab: "placements", heading: "Top Recruiters", body: "- Google, Microsoft, Amazon, Adobe (software/product)\n- Goldman Sachs (quant/analytics)\n- Flipkart, Sprinklr (India-based product companies)\n- Qualcomm and other semiconductor/R&D recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "Given the very small B.Tech intake (around 100 seats total), JEE Main cutoff percentiles for CSE have typically required a percentile in the high 90s in recent years. These figures are indicative — IIIT-B publishes exact cutoffs after each admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Need-based and merit-based fee waivers for eligible Indian students\n- Research assistantships available for students engaged in faculty-led projects\n- Institute merit scholarships for top JEE Main rank-holders\n- External and corporate-sponsored scholarships accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIIT Bangalore is ranked #74 in NIRF 2024 Engineering, a ranking that understates its reputation specifically within computer science research circles, where it is regarded as one of India's stronger CS-focused institutes." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIIT-B provides on-campus hostel accommodation for the large majority of students. Student life includes a dense calendar of hackathons, research talks, and industry-interaction events reflecting the institute's CS-research-first identity, alongside standard technical and cultural fests." },
  ],
};

const msrit: CollegeContentPack = {
  slug: "m-s-ramaiah-institute-of-technology",
  college: {
    estd: 1962,
    website: "https://www.msrit.edu",
    feesNum: 600000,
    feesLabel: "₹6.0 L",
    packageLabel: "₹7 LPA",
    affiliation: "Autonomous College, VTU",
    approvedBy: "UGC, AICTE",
    metaTitle: "M. S. Ramaiah Institute of Technology — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "MSRIT Bengaluru NIRF #75 engineering: B.Tech courses, fees, KCET/COMEDK admission, placement stats, hostel and scholarship details.",
    about:
      "M. S. Ramaiah Institute of Technology (MSRIT), founded in 1962 by industrialist M. S. Ramaiah in Bengaluru, is one of Karnataka's most respected autonomous engineering colleges, affiliated with VTU. Its Bengaluru location — in the heart of India's largest technology hub — has helped it build one of the strongest placement networks among the state's non-deemed private engineering colleges.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Information Science & Engineering", duration: "4 years", seats: "180", feesLabel: "₹5.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.0 L total" },
  ],
  placement: { avgPackage: "₹7 LPA", highestPackage: "₹48 LPA (indicative)", placedPct: "87" },
  recruiters: ["Amazon", "TCS", "Infosys", "Cognizant", "Cisco", "Deloitte", "Wipro", "Bosch"],
  highlights: [
    "Founded 1962 by industrialist M. S. Ramaiah, autonomous college affiliated with VTU",
    "Bengaluru location gives direct access to India's largest technology-industry hub",
    "Consistently strong placement percentage among Karnataka's private engineering colleges",
    "Admission via KCET or COMEDK UGET counselling",
  ],
  faqs: [
    { question: "Is MSRIT good for placements?", answer: "MSRIT posts one of the strongest placement records among Karnataka's non-deemed private engineering colleges, helped significantly by its Bengaluru location in the middle of India's largest technology-industry cluster." },
    { question: "How is admission to MSRIT done?", answer: "MSRIT admits students primarily through Karnataka CET (KCET) for state-domicile candidates and COMEDK UGET for a broader applicant pool including out-of-state students, with a smaller management-quota admission process as well." },
  ],
  sections: [
    { tab: "info", heading: "About MSRIT", body: "M. S. Ramaiah Institute of Technology was founded in 1962 by industrialist and philanthropist M. S. Ramaiah in Bengaluru, Karnataka. As an autonomous college affiliated with Visvesvaraya Technological University (VTU), MSRIT has built one of Karnataka's most respected private-engineering reputations over six decades, with particular strength in Computer Science, Information Science, and Electronics.\n\nMSRIT's location within Bengaluru — India's largest technology-industry hub — has been a significant driver of its strong placement record, with dense access to internships and campus recruitment drives from the city's software and product-company base." },
    { tab: "info", heading: "Campus & Location", body: "The MSRIT campus in Bengaluru spans a well-established site with departmental blocks, a central library, and workshop facilities built up over six decades. Its Bengaluru location places it in close proximity to major technology-company campuses across the city." },
    { tab: "info", heading: "Why Choose MSRIT", body: "- Six decades of academic reputation and strong Bengaluru placement network\n- Particularly strong Computer Science and Information Science programmes\n- Consistently high placement percentage among non-deemed private colleges\n- Direct access to India's largest technology-industry hub" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 300 | ₹6.0 L |\n| Information Science & Engineering | 4 years | 180 | ₹5.8 L |\n| Electronics & Communication | 4 years | 150 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 120 | ₹5.0 L |\n\nFees vary between KCET-counselled (government-regulated) and COMEDK/management-quota seats; confirm current-year figures with MSRIT admissions." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "KCET-counselled seats follow Karnataka government-regulated fee slabs; COMEDK and management-quota seats carry a separate (higher) fee structure. Fees are payable per semester through the college's designated bank channels." },
    { tab: "admissions", heading: "Admission Process", body: "MSRIT admits students primarily through Karnataka CET (KCET) for Karnataka-domicile candidates and COMEDK UGET for a broader applicant pool including out-of-state students, with a smaller management-quota admission process available. Applicants apply through the relevant counselling process and are allotted seats based on rank and category." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per KCET/COMEDK norms\n- Valid KCET or COMEDK UGET rank/score\n- Documents: Class 10/12 mark sheets, entrance scorecard, category/domicile certificate (for KCET), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "MSRIT's placement cell benefits substantially from its Bengaluru location, running dense recruitment drives with both IT-services majors and a meaningful base of product-company and analytics recruiters. Overall placement percentage has generally stayed in the mid-to-high 80s across recent years, among the best for a non-deemed private college in Karnataka." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Cisco (product/software)\n- TCS, Infosys, Cognizant, Wipro (bulk IT-services hiring)\n- Bosch (core engineering/R&D)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the KCET route, CSE admissions have typically required a rank within the top few thousand in recent years for open category; for COMEDK, similarly competitive ranks are needed given high demand. These figures are indicative — MSRIT publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Karnataka state government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible KCET students\n- MSRIT merit scholarships for top academic performers\n- Continuing merit scholarships tied to semester GPA\n- Need-based financial assistance through alumni-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "M. S. Ramaiah Institute of Technology is ranked #75 in NIRF 2024 Engineering — a strong position for a self-financing, non-deemed private college, reflecting its placement strength and academic reputation within Karnataka." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MSRIT provides on-campus hostel accommodation for both men and women, though a significant share of students commute given the college's Bengaluru location. Student life includes the annual technical symposium and cultural fest, plus active sports and departmental clubs." },
  ],
};

export const engBatch6: CollegeContentPack[] = [
  iitPalakkad,
  manipalJaipur,
  sathyabama,
  psgTech,
  nitMeghalaya,
  vtu,
  uohyd,
  nitRaipur,
  manitBhopal,
  iitBhilai,
  iiitBangalore,
  msrit,
];
