import type { CollegeContentPack } from "./types";

// NIRF Engineering 2024 #76-88 — hand-authored, matches iit-madras.ts / eng-batch2-6.ts depth.

const sliet: CollegeContentPack = {
  slug: "sant-longowal-institute-of-engineering-and-technology",
  college: {
    estd: 1989,
    website: "https://www.sliet.ac.in",
    feesNum: 450000,
    feesLabel: "₹4.5 L",
    packageLabel: "₹7 LPA",
    affiliation: "Deemed University, under Ministry of Education",
    approvedBy: "MHRD, AICTE",
    metaTitle: "SLIET Longowal — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Sant Longowal Institute of Engineering and Technology NIRF #76: B.Tech courses, fees, admission, placement, hostel details.",
    about:
      "Sant Longowal Institute of Engineering and Technology (SLIET), established in 1989 at Longowal, Punjab, is a centrally funded deemed university under the Ministry of Education, built with a mandate to serve rural and semi-urban technical education needs. It runs a comparatively small, government-subsidised B.Tech programme alongside diploma and vocational courses.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "60", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "50", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "50", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Food Engineering & Technology", duration: "4 years", seats: "30", feesLabel: "₹4.5 L total" },
  ],
  placement: { avgPackage: "₹7 LPA", highestPackage: "₹32 LPA (indicative)", placedPct: "75" },
  recruiters: ["TCS", "Infosys", "Wipro", "Cognizant", "L&T", "HCL"],
  highlights: [
    "Centrally funded deemed university under the Ministry of Education, established 1989",
    "Distinctive rural and semi-urban technical education mandate",
    "Comparatively low, government-subsidised fees",
    "Admission via JEE Main score for its B.Tech programmes",
  ],
  faqs: [
    { question: "What is SLIET known for?", answer: "SLIET is known for its government-subsidised technical education mandate, particularly serving rural and semi-urban students in Punjab and neighbouring states, alongside a distinctive Food Engineering & Technology programme uncommon at most engineering colleges." },
    { question: "How is admission to SLIET done?", answer: "SLIET admits B.Tech students based on JEE Main rank, with seats allotted through the institute's own centralised counselling process." },
  ],
  sections: [
    { tab: "info", heading: "About SLIET", body: "Sant Longowal Institute of Engineering and Technology was established in 1989 at Longowal, Punjab, as a centrally funded institute under India's Ministry of Education, later attaining deemed-university status. Its founding mandate emphasised technical education access for rural and semi-urban communities, distinguishing it from most other engineering institutes in this ranking band.\n\nSLIET runs B.Tech programmes in Computer Science, Electronics, Mechanical, and a distinctive Food Engineering & Technology department, alongside diploma and vocational training courses that reflect its broader technical-education mission." },
    { tab: "info", heading: "Campus & Location", body: "The SLIET campus is located in Longowal, a rural town in Punjab's Sangrur district, with academic blocks, hostels, and workshop facilities built around the institute's technical and vocational education mission." },
    { tab: "info", heading: "Why Choose SLIET", body: "- Government-subsidised fees, among the lower end for a NIRF-ranked engineering institute\n- Distinctive Food Engineering & Technology programme\n- Centrally funded institute with a rural technical-education mandate\n- Smaller batch sizes with close faculty interaction" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 60 | ₹4.5 L |\n| Electronics & Communication | 4 years | 50 | ₹4.5 L |\n| Mechanical Engineering | 4 years | 50 | ₹4.5 L |\n| Food Engineering & Technology | 4 years | 30 | ₹4.5 L |\n\nFees are government-subsidised given SLIET's central funding; confirm current-year figures on the official SLIET admissions portal." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Fee concessions apply for SC/ST/OBC/EWS students under central government norms. Fees are payable per semester through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "SLIET admits B.Tech students based on JEE Main rank, with seats allotted through the institute's own centralised counselling process rather than JoSAA. Applicants apply through the SLIET admission portal alongside their JEE Main application." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per SLIET norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "SLIET's placement cell runs campus drives concentrated in IT services with core-engineering participation for Mechanical and Food Engineering graduates. Overall placement percentage has generally stayed around 75% across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- L&T (core engineering)\n- Regional Punjab food-processing and manufacturing firms (Food Engineering graduates)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "SLIET's JEE Main-based cutoffs have generally been more accessible than most NITs given its smaller reputation footprint; CSE seats fill first. These figures shift year to year — confirm current-year cutoffs on the official SLIET admission portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Central government fee concessions for SC/ST/OBC/EWS-eligible students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Ministry of Education scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "SLIET is ranked #76 in NIRF 2024 Engineering, reflecting its niche positioning as a centrally funded rural-technical-education institute." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SLIET provides on-campus hostel accommodation for the majority of its students given the rural Longowal setting. Student life includes technical fests and vocational-skills events reflecting the institute's broader technical-education mission." },
  ],
};

const coepPune: CollegeContentPack = {
  slug: "coep-technological-university",
  college: {
    estd: 1854,
    website: "https://www.coeptech.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹9 LPA",
    affiliation: "State Technological University, Maharashtra",
    approvedBy: "UGC, AICTE",
    metaTitle: "COEP Technological University Pune — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "COEP Pune NIRF #77 engineering: B.Tech courses, fees, MHT-CET/JEE Main admission, placement stats, hostel and scholarship details.",
    about:
      "College of Engineering, Pune (COEP), founded in 1854, is one of the oldest engineering colleges in Asia, predating even the earliest IITs by nearly a century. Elevated to full state technological university status as COEP Technological University in 2022, it combines a rare depth of institutional history with modern autonomous-university governance, located in the heart of Pune, Maharashtra.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electronics & Telecommunication", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.0 L total" },
  ],
  placement: { avgPackage: "₹9 LPA", highestPackage: "₹48 LPA (indicative)", placedPct: "86" },
  recruiters: ["Amazon", "Microsoft", "TCS", "Infosys", "L&T", "Bajaj Auto", "Deloitte", "Cummins"],
  highlights: [
    "Founded 1854 — among the oldest engineering colleges in Asia",
    "Elevated to full state technological university status in 2022",
    "Central Pune location with strong access to Maharashtra's auto and IT industry",
    "Admission via MHT-CET or JEE Main score",
  ],
  faqs: [
    { question: "How old is COEP?", answer: "COEP (College of Engineering, Pune) was founded in 1854, making it one of the oldest engineering institutions in Asia — nearly a century older than the earliest IITs." },
    { question: "Is COEP a university now?", answer: "Yes — COEP was elevated from an autonomous college to a full state technological university, renamed COEP Technological University, in 2022, giving it greater academic and administrative autonomy." },
  ],
  sections: [
    { tab: "info", heading: "About COEP Technological University", body: "College of Engineering, Pune was founded in 1854, making it one of the oldest engineering institutions in Asia — predating even the earliest IITs by close to a century. In 2022, it was elevated to full state technological university status, becoming COEP Technological University, giving it expanded academic autonomy while retaining its historic identity and reputation within Maharashtra and across India.\n\nCOEP runs undergraduate programmes across Computer Science, Electronics & Telecommunication, Mechanical, Civil, and allied branches, with a research culture built on nearly 170 years of institutional history." },
    { tab: "info", heading: "Campus & Location", body: "The COEP campus is located in the heart of Pune, Maharashtra, one of India's major automotive, manufacturing, and growing IT hubs. Its central city location gives students strong access to internships and recruiter drives across both traditional manufacturing and newer technology-sector employers." },
    { tab: "info", heading: "Why Choose COEP Technological University", body: "- Among the oldest engineering institutions in Asia, with nearly 170 years of history\n- Recently elevated to full state technological university status\n- Central Pune location within Maharashtra's dense industrial and IT corridor\n- Strong regional reputation and alumni network across Maharashtra" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.0 L |\n| Electronics & Telecommunication | 4 years | 90 | ₹5.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.0 L |\n| Civil Engineering | 4 years | 70 | ₹5.0 L |\n\nFees follow Maharashtra state university norms; SC/ST/OBC/EWS domicile students receive fee concessions under state policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Maharashtra state government fee-reimbursement schemes apply for SC/ST/OBC/EWS domicile students admitted via MHT-CET. Fees are payable per semester through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "COEP admits B.Tech students primarily through MHT-CET for Maharashtra-domicile candidates, with a portion of seats allotted through JEE Main for the All-India quota. Applicants apply through the relevant state CAP rounds (MHT-CET) or COEP's own All-India counselling process (JEE Main quota)." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per quota/category norms\n- Valid MHT-CET or JEE Main score/rank as per chosen quota\n- Documents: Class 10/12 mark sheets, entrance scorecard, domicile certificate (for MHT-CET quota), category certificate, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "COEP's placement cell draws a strong base of software, automotive, and core-manufacturing recruiters given Pune's dense industrial and IT base. CSE and Electronics graduates post the strongest outcomes; overall placement percentage has generally stayed in the mid-80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft (software)\n- Bajaj Auto, Cummins (automotive/manufacturing — key given Pune's industrial base)\n- L&T (core engineering)\n- TCS, Infosys, Deloitte (IT services/consulting)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the MHT-CET route, CSE admissions have typically required a percentile above 99 in recent years given strong demand; for the JEE Main All-India quota, similarly high percentiles are generally needed. These figures are indicative — COEP publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Maharashtra state government fee-reimbursement schemes for SC/ST/OBC/EWS domicile students\n- Merit scholarships for top rank-holders in each department\n- Institute-level need-based financial assistance\n- Alumni-funded scholarship programmes given COEP's long institutional history" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "COEP Technological University is ranked #77 in NIRF 2024 Engineering, a position that reflects its transitional status as a recently elevated university still building out its post-2022 research and placement infrastructure." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "COEP provides on-campus hostel accommodation, though a meaningful share of students commute given the college's central Pune location. Student life includes the annual technical fest Tantrafiesta and cultural fest, plus a strong alumni-network presence at campus events reflecting the institute's long history." },
  ],
};

const banasthali: CollegeContentPack = {
  slug: "banasthali-vidyapith",
  college: {
    estd: 1935,
    website: "https://www.banasthali.org",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹5.5 LPA",
    affiliation: "Deemed University (Women's Institution)",
    approvedBy: "UGC, AICTE",
    metaTitle: "Banasthali Vidyapith — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Banasthali Vidyapith Rajasthan NIRF #78 engineering: B.Tech courses for women, fees, admission, placement, hostel details.",
    about:
      "Banasthali Vidyapith, founded in 1935 in Rajasthan and granted deemed-university status in 1983, is one of India's largest women's universities, running a full B.Tech engineering programme exclusively for women students. Its unique gurukul-inspired residential education model combines full-time on-campus living with modern STEM education, producing a disproportionately large share of India's women engineering graduates from a single institution.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering (Women only)", duration: "4 years", seats: "180", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication (Women only)", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Information Technology (Women only)", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Bioscience & Biotechnology (Women only)", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹5.5 LPA", highestPackage: "₹38 LPA (indicative)", placedPct: "82" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Cognizant", "HCL", "Deloitte"],
  highlights: [
    "One of India's largest women's universities, founded 1935, deemed university since 1983",
    "Distinctive gurukul-inspired residential education model exclusively for women",
    "Notably strong placement percentage relative to fee level",
    "Admission via own entrance test or JEE Main score",
  ],
  faqs: [
    { question: "Is Banasthali Vidyapith only for women?", answer: "Yes — Banasthali Vidyapith is a women's-only university across all its programmes including engineering, making its B.Tech intake exclusively female, part of its founding gurukul-inspired residential education philosophy." },
    { question: "How is admission to Banasthali's B.Tech done?", answer: "Banasthali admits B.Tech students through its own entrance test or JEE Main score, with seats allotted through the university's own counselling process for women applicants." },
  ],
  sections: [
    { tab: "info", heading: "About Banasthali Vidyapith", body: "Banasthali Vidyapith was founded in 1935 in Rajasthan, initially as a school, and was granted deemed-to-be-university status in 1983. It has grown into one of India's largest women's universities, running programmes across engineering, sciences, humanities, and management — all exclusively for women students, following a distinctive gurukul-inspired residential education philosophy that combines full-time on-campus living with modern academic training.\n\nWithin this framework, Banasthali's engineering school offers B.Tech programmes in Computer Science, Electronics, Information Technology, and Bioscience & Biotechnology, producing a disproportionately large share of India's women engineering graduates from a single institution." },
    { tab: "info", heading: "Campus & Facilities", body: "The Banasthali campus in Rajasthan is a large, fully residential setting where all students live on campus for the duration of their studies as part of the institution's founding philosophy. Facilities include dedicated engineering labs, extensive hostel infrastructure, and sports and cultural facilities built around the gurukul residential model." },
    { tab: "info", heading: "Why Choose Banasthali Vidyapith", body: "- One of India's largest and most established women-only engineering programmes\n- Distinctive full-residential gurukul-inspired education model\n- Notably strong placement percentage relative to fee level\n- Multiple admission routes (own entrance test, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 180 | ₹5.5 L |\n| Electronics & Communication | 4 years | 120 | ₹5.5 L |\n| Information Technology | 4 years | 90 | ₹5.5 L |\n| Bioscience & Biotechnology | 4 years | 60 | ₹5.5 L |\n\nAll programmes are open exclusively to women students; fees are charged per year and include the mandatory residential component. Confirm current-year figures on the official Banasthali admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Banasthali offers merit-based fee waivers tied to entrance rank or Class 12 percentage at admission. Fees are payable in semester instalments through the university's online portal, and include mandatory hostel/mess charges given the fully residential model." },
    { tab: "admissions", heading: "Admission Process", body: "Banasthali admits B.Tech students through its own entrance examination or directly via JEE Main score, for women applicants only. Applicants apply online, and seats are allotted through Banasthali's own counselling process based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Female applicants only, Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per Banasthali norms\n- Valid entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance/JEE Main scorecard, category certificate (if applicable), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Banasthali's placement cell runs campus drives concentrated in IT services, with CSE posting the strongest outcomes. Overall placement percentage has generally stayed around 82% across recent years, notably strong for a private deemed university at this fee level." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Deloitte and other analytics/consulting recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For Banasthali's own entrance test, CSE admissions have typically required a rank within the top few thousand test-takers in recent years; for the JEE Main route, cutoff percentiles have generally fallen in the 75-85 range. These are indicative — confirm current-year cutoffs with Banasthali admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/Class 12-percentage merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Need-based financial assistance for economically weaker students\n- Central and state government scholarship schemes for eligible women students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Banasthali Vidyapith is ranked #78 in NIRF 2024 Engineering and also features strongly in NIRF's Overall University category, reflecting its scale and reputation as one of India's largest women's universities." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Hostel accommodation at Banasthali is mandatory for all students as part of its gurukul-inspired residential education model. Student life includes an extensive calendar of cultural, technical, and sports events built around a fully on-campus community." },
  ],
};

const nitSrinagar: CollegeContentPack = {
  slug: "national-institute-of-technology-srinagar",
  college: {
    estd: 1960,
    website: "https://www.nitsri.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹8 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Srinagar — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Srinagar NIRF #79 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Srinagar, established in 1960 as a Regional Engineering College and elevated to NIT status in 2003, is Jammu and Kashmir's premier technical institute. Located in Srinagar, it draws students nationwide through JoSAA, running programmes across Computer Science, Electronics, Mechanical, and Civil Engineering.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "80", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "80", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹8 LPA", highestPackage: "₹36 LPA (indicative)", placedPct: "76" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Cognizant", "L&T", "Deloitte"],
  highlights: [
    "Jammu and Kashmir's premier NIT, founded 1960, NIT status since 2003",
    "Located in Srinagar, serving the region's technical education needs",
    "Growing CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Srinagar a good option?", answer: "NIT Srinagar carries full NIT status and JoSAA admission credibility, serving as the premier technical institute for Jammu and Kashmir, with growing placement outcomes particularly in Computer Science and Electronics." },
    { question: "What is NIT Srinagar's CSE cutoff?", answer: "CSE closing ranks at NIT Srinagar have typically fallen in the 16,000-21,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Srinagar", body: "National Institute of Technology, Srinagar was established in 1960 as a Regional Engineering College and was granted National Institute of Technology status in 2003. Located in Srinagar, Jammu and Kashmir, it serves as the region's premier technical institute, running undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, and Civil Engineering.\n\nNIT Srinagar carries significant regional importance for STEM education access in Jammu and Kashmir, alongside its standing within the national NIT system." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Srinagar campus is located near Hazratbal on the banks of Dal Lake, one of the most scenic NIT campus settings in India, with academic blocks, hostels, and a central library." },
    { tab: "info", heading: "Why Choose NIT Srinagar", body: "- NIT brand and JoSAA admission credibility for Jammu and Kashmir's premier technical institute\n- Distinctive, scenic Dal Lake campus setting\n- Growing CSE and Electronics placement outcomes\n- Accessible JoSAA cutoffs relative to older, more established NITs" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 90 | ₹5.5 L |\n| Electronics & Communication | 4 years | 80 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 80 | ₹5.5 L |\n| Civil Engineering | 4 years | 60 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Srinagar's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Srinagar's placement cell runs campus drives concentrated in IT services with growing core-sector participation. CSE and Electronics graduates post the strongest outcomes; overall placement percentage has generally stayed in the mid-70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant (bulk IT-services hiring)\n- Amazon for select CSE roles\n- L&T (core engineering)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 16,000 – 21,000 |\n| Electronics & Communication | 26,000 – 33,000 |\n| Mechanical Engineering | 38,000 – 47,000 |\n| Civil Engineering | 45,000 – 55,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Jammu and Kashmir/Ladakh region-specific government scholarship schemes for eligible students\n- Institute merit scholarships for top academic performers" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Srinagar is ranked #79 in NIRF 2024 Engineering, holding steady as Jammu and Kashmir's top-ranked technical institute." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Srinagar provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs, set against the scenic Dal Lake backdrop." },
  ],
};

const rgipt: CollegeContentPack = {
  slug: "rajiv-gandhi-institute-of-petroleum-technology",
  college: {
    estd: 2008,
    website: "https://www.rgipt.ac.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹15 LPA",
    affiliation: "Institute of National Importance, under Ministry of Petroleum and Natural Gas",
    approvedBy: "MHRD, AICTE",
    metaTitle: "RGIPT Amethi — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Rajiv Gandhi Institute of Petroleum Technology NIRF #80: B.Tech Petroleum/Chemical courses, fees, admission, placement, hostel details.",
    about:
      "Rajiv Gandhi Institute of Petroleum Technology (RGIPT), established in 2008 at Jais, Amethi, Uttar Pradesh, is an Institute of National Importance under India's Ministry of Petroleum and Natural Gas, built with strong backing from major public-sector oil and gas companies. Its narrow, petroleum-and-energy-focused curriculum gives graduates a distinctive, high-value pathway into India's energy sector.",
  },
  courses: [
    { name: "B.Tech Petroleum Engineering", duration: "4 years", seats: "60", feesLabel: "₹7.0 L total" },
    { name: "B.Tech Chemical Engineering", duration: "4 years", seats: "50", feesLabel: "₹7.0 L total" },
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "40", feesLabel: "₹7.0 L total" },
    { name: "B.Tech Mechanical Engineering (Energy Systems)", duration: "4 years", seats: "40", feesLabel: "₹7.0 L total" },
  ],
  placement: { avgPackage: "₹15 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "90" },
  recruiters: ["ONGC", "Indian Oil", "Reliance Industries", "Shell", "BPCL", "Amazon", "Deloitte"],
  highlights: [
    "Institute of National Importance under the Ministry of Petroleum and Natural Gas",
    "Founded 2008 with strong backing from major public-sector oil and gas companies",
    "Distinctive petroleum-and-energy-focused curriculum with strong sector placement pipeline",
    "Admission via JEE Main score through its own centralised counselling",
  ],
  faqs: [
    { question: "Is RGIPT good for Petroleum Engineering?", answer: "RGIPT is one of India's most focused institutes for petroleum and energy-sector education, with an Institute of National Importance status and direct backing from major oil and gas PSUs, giving its Petroleum Engineering graduates a strong, sector-specific placement pipeline." },
    { question: "How is admission to RGIPT done?", answer: "RGIPT admits B.Tech students based on JEE Main rank, with seats allotted through the institute's own centralised counselling process." },
  ],
  sections: [
    { tab: "info", heading: "About RGIPT", body: "Rajiv Gandhi Institute of Petroleum Technology was established in 2008 at Jais, in Amethi district, Uttar Pradesh, as an Institute of National Importance under India's Ministry of Petroleum and Natural Gas. It was set up with strong backing from major public-sector oil and gas companies including ONGC, Indian Oil, GAIL, and Oil India, which shaped its narrow, sector-focused curriculum around Petroleum Engineering, Chemical Engineering, and allied energy-systems disciplines.\n\nRGIPT's close institutional ties to India's energy PSUs give it a distinctive, high-value placement pathway unmatched by most conventional engineering institutes, alongside a smaller Computer Science programme." },
    { tab: "info", heading: "Campus & Location", body: "The RGIPT campus is located at Jais, in Amethi district, Uttar Pradesh, with academic blocks, hostels, and specialised petroleum-engineering laboratories built around the institute's energy-sector mandate." },
    { tab: "info", heading: "Why Choose RGIPT", body: "- Institute of National Importance with direct backing from major oil and gas PSUs\n- Distinctive, high-value petroleum-and-energy-sector placement pipeline\n- Narrow, focused curriculum built around energy-sector needs\n- Small, highly selective batch sizes across all programmes" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Petroleum Engineering | 4 years | 60 | ₹7.0 L |\n| Chemical Engineering | 4 years | 50 | ₹7.0 L |\n| Computer Science & Engineering | 4 years | 40 | ₹7.0 L |\n| Mechanical Engineering (Energy Systems) | 4 years | 40 | ₹7.0 L |\n\nFees follow a structure comparable to other Institutes of National Importance; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and for General/OBC students with family income under the prescribed threshold, consistent with central-institute fee-waiver policy. Fees are payable in two semester instalments through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "RGIPT admits B.Tech students based on JEE Main rank, with seats allotted through the institute's own centralised counselling process rather than JoSAA. Applicants apply through the RGIPT admission portal alongside their JEE Main application." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per RGIPT norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "RGIPT posts placement outcomes that are exceptionally strong for its niche — India's oil and gas PSUs and major energy companies recruit heavily given the institute's direct sector backing, with placement percentage regularly reported above 85-90% and starting packages notably high for a petroleum-and-energy-focused institute." },
    { tab: "placements", heading: "Top Recruiters", body: "- ONGC, Indian Oil, BPCL (public-sector oil and gas — primary recruiters)\n- Reliance Industries, Shell (private-sector energy majors)\n- Amazon, Deloitte (select roles for CSE and allied graduates opting outside the energy sector)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "RGIPT's JEE Main-based cutoffs have historically been competitive given its small, specialised intake and the strong pull of guaranteed energy-sector placement pathways; Petroleum Engineering and CSE seats fill first. These figures shift year to year — confirm current-year cutoffs on the official RGIPT admission portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute scholarships tied to strong academic performance\n- PSU-sponsored scholarship schemes given RGIPT's energy-sector backing" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "RGIPT is ranked #80 in NIRF 2024 Engineering, a strong position given its extremely narrow, specialised focus on petroleum and energy technology compared to general-purpose engineering institutes ranked around it." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "RGIPT provides on-campus hostel accommodation for its full undergraduate intake given the small batch sizes. Campus life includes technical events closely tied to the energy sector, alongside standard sports and cultural activities typical of a compact, focused campus." },
  ],
};

const nitKurukshetra: CollegeContentPack = {
  slug: "national-institute-of-technology-kurukshetra",
  college: {
    estd: 1963,
    website: "https://www.nitkkr.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹10.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Kurukshetra — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Kurukshetra NIRF #81 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Kurukshetra, established in 1963 as a Regional Engineering College and elevated to NIT status in 2002, is Haryana's premier technical institute. Located in the historic city of Kurukshetra, it draws students nationwide through JoSAA, with well-regarded Computer Science and Electronics programmes.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "100", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹10.5 LPA", highestPackage: "₹45 LPA (indicative)", placedPct: "85" },
  recruiters: ["Amazon", "Microsoft", "TCS", "Infosys", "L&T", "Deloitte", "Samsung R&D", "Maruti Suzuki"],
  highlights: [
    "Haryana's premier NIT, founded 1963, NIT status since 2002",
    "Located in the historic city of Kurukshetra",
    "Strong CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Kurukshetra a good NIT?", answer: "NIT Kurukshetra is consistently ranked among the top 15-20 NITs nationally, with strong CSE and Electronics placement outcomes and a well-established regional reputation across Haryana and Delhi-NCR." },
    { question: "What is NIT Kurukshetra's CSE cutoff?", answer: "CSE closing ranks at NIT Kurukshetra have typically fallen in the 6,500-9,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Kurukshetra", body: "National Institute of Technology, Kurukshetra was established in 1963 as a Regional Engineering College and was granted National Institute of Technology status in 2002. Located in Kurukshetra, Haryana — a city of deep historical and religious significance — NIT Kurukshetra runs undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, and Civil Engineering.\n\nNIT Kurukshetra has built a strong regional reputation across Haryana and the Delhi-NCR region, with steady research output alongside its undergraduate placement outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Kurukshetra campus spans a substantial site in Kurukshetra, Haryana, with academic blocks, hostels, a central library, and workshop facilities. Its proximity to Delhi-NCR gives the institute strong recruiter access." },
    { tab: "info", heading: "Why Choose NIT Kurukshetra", body: "- Among the top 20 NITs nationally, with strong CSE and Electronics outcomes\n- Proximity to Delhi-NCR gives strong recruiter access\n- NIT brand and infrastructure with accessible JoSAA cutoffs relative to older NITs\n- Historic Kurukshetra location with rich cultural heritage" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.5 L |\n| Electronics & Communication | 4 years | 100 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n| Civil Engineering | 4 years | 70 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Kurukshetra's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Kurukshetra's placement cell draws strong software, automotive, and core-engineering recruiters, aided by proximity to Delhi-NCR and Haryana's automotive manufacturing base. CSE and Electronics post the strongest outcomes; overall placement percentage has stayed in the low-to-mid 80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Samsung R&D (software/semiconductor)\n- Maruti Suzuki (automotive — reflecting Haryana's manufacturing base)\n- TCS, Infosys (bulk IT-services hiring)\n- L&T, Deloitte (core engineering/consulting)" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 6,500 – 9,000 |\n| Electronics & Communication | 12,000 – 16,000 |\n| Mechanical Engineering | 17,000 – 22,000 |\n| Civil Engineering | 23,000 – 29,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Haryana state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Kurukshetra is ranked #81 in NIRF 2024 Engineering, holding a consistent position among the top 20 NITs nationally." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Kurukshetra provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const nitAgartala: CollegeContentPack = {
  slug: "national-institute-of-technology-agartala",
  college: {
    estd: 1965,
    website: "https://www.nita.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹7.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Agartala — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Agartala NIRF #82 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Agartala, established in 1965 as a Regional Engineering College and elevated to NIT status in 2006, serves as the premier technical institute for Tripura and the wider Northeast region. Located in Agartala, it draws students through JoSAA with programmes spanning Computer Science, Electronics, Mechanical, and Civil Engineering.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "80", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "80", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹7.5 LPA", highestPackage: "₹34 LPA (indicative)", placedPct: "74" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Cognizant", "HCL"],
  highlights: [
    "Premier technical institute for Tripura and the Northeast, founded 1965, NIT status since 2006",
    "Located in Agartala, serving the region's technical education needs",
    "Growing CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Agartala a good option?", answer: "NIT Agartala carries full NIT status and JoSAA admission credibility, serving as a key technical institute for Tripura and the Northeast region, with steadily growing placement outcomes in Computer Science and Electronics." },
    { question: "What is NIT Agartala's CSE cutoff?", answer: "CSE closing ranks at NIT Agartala have typically fallen in the 24,000-30,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Agartala", body: "National Institute of Technology, Agartala was established in 1965 as a Regional Engineering College and was granted National Institute of Technology status in 2006. Located in Agartala, Tripura, it serves as a key technical institute for India's Northeast region alongside NIT Silchar and NIT Meghalaya, running undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, and Civil Engineering.\n\nNIT Agartala carries significant regional importance for STEM education access in Tripura and neighbouring Northeast states." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Agartala campus spans a substantial site near Agartala, Tripura, with academic blocks, hostels, a central library, and workshop facilities." },
    { tab: "info", heading: "Why Choose NIT Agartala", body: "- NIT brand and JoSAA admission credibility for a key Northeast-region institute\n- Growing CSE and Electronics placement outcomes\n- Regional importance for Tripura's technical education access\n- Accessible JoSAA cutoffs relative to older, more established NITs" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 90 | ₹5.5 L |\n| Electronics & Communication | 4 years | 80 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 80 | ₹5.5 L |\n| Civil Engineering | 4 years | 60 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Agartala's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Agartala's placement cell runs campus drives concentrated in IT services, with CSE and Electronics graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Regional Northeast infrastructure and manufacturing firms" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 24,000 – 30,000 |\n| Electronics & Communication | 36,000 – 44,000 |\n| Mechanical Engineering | 50,000 – 60,000 |\n| Civil Engineering | 55,000 – 65,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Northeast-region specific government scholarship schemes for eligible students\n- Institute merit scholarships for top academic performers" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Agartala is ranked #82 in NIRF 2024 Engineering, holding steady as Tripura's top-ranked technical institute." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Agartala provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs reflecting the institute's Northeast setting." },
  ],
};

const skcet: CollegeContentPack = {
  slug: "sri-krishna-college-of-engineering-and-technology",
  college: {
    estd: 1998,
    website: "https://www.skcet.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹4.2 LPA",
    affiliation: "Autonomous College, Anna University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Sri Krishna College of Engineering and Technology — Courses, Fees, Placements 2026",
    metaDescription: "SKCET Coimbatore NIRF #83 engineering: B.Tech courses, fees, TNEA admission, placement stats, hostel and scholarship details.",
    about:
      "Sri Krishna College of Engineering and Technology (SKCET), founded in 1998 in Coimbatore, Tamil Nadu, is an autonomous college affiliated with Anna University, part of the broader Sri Krishna group of institutions. It has built a solid regional reputation within Tamil Nadu's dense private-engineering ecosystem, particularly for Computer Science and Information Technology.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "240", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Information Technology", duration: "4 years", seats: "120", feesLabel: "₹4.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹4.2 L total" },
  ],
  placement: { avgPackage: "₹4.2 LPA", highestPackage: "₹32 LPA (indicative)", placedPct: "78" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Zoho", "Amazon (select roles)"],
  highlights: [
    "Founded 1998, autonomous college affiliated with Anna University in Coimbatore",
    "Part of the broader Sri Krishna group of institutions",
    "Solid regional placement network within Tamil Nadu's private-engineering ecosystem",
    "Admission via TNEA (Tamil Nadu Engineering Admissions) counselling",
  ],
  faqs: [
    { question: "How is admission to SKCET done?", answer: "The bulk of SKCET's seats are filled through TNEA (Tamil Nadu Engineering Admissions) counselling, based on Class 12 cutoff marks, with a smaller management quota for out-of-state or other eligible candidates." },
    { question: "Is SKCET good for placements?", answer: "SKCET posts solid placement outcomes within Tamil Nadu's dense private-engineering ecosystem, particularly for Computer Science and Information Technology graduates, though packages are moderate compared to top-tier institutes." },
  ],
  sections: [
    { tab: "info", heading: "About SKCET", body: "Sri Krishna College of Engineering and Technology was founded in 1998 in Coimbatore, Tamil Nadu, as part of the broader Sri Krishna group of educational institutions. As an autonomous college affiliated with Anna University, SKCET runs undergraduate programmes across Computer Science, Information Technology, Electronics, and Mechanical Engineering.\n\nSKCET has built a solid regional reputation within Tamil Nadu's dense private-engineering ecosystem, benefiting from Coimbatore's established manufacturing and growing IT-services base." },
    { tab: "info", heading: "Campus & Facilities", body: "The SKCET campus in Coimbatore includes academic blocks, computer labs, hostels, and sports facilities typical of an established private engineering college in the region." },
    { tab: "info", heading: "Why Choose SKCET", body: "- Solid regional placement network within Tamil Nadu's private-engineering ecosystem\n- Part of the broader, well-established Sri Krishna group of institutions\n- Autonomous college status with Anna University affiliation\n- Coimbatore location within a dense manufacturing and IT-services base" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 240 | ₹5.0 L |\n| Information Technology | 4 years | 120 | ₹4.8 L |\n| Electronics & Communication | 4 years | 150 | ₹4.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹4.2 L |\n\nFees are set per Anna University/Tamil Nadu government norms for self-financing colleges; confirm current-year figures with SKCET admissions." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "TNEA-counselled seats follow government-regulated fee slabs; management-quota seats carry a separate fee structure. Fees are payable per semester through the college's designated bank channels." },
    { tab: "admissions", heading: "Admission Process (TNEA)", body: "The bulk of SKCET's seats are filled through TNEA counselling, based on a normalised Class 12 cutoff score (out of 200) for Tamil Nadu domicile students. A smaller share of seats is available under the management quota, filled by SKCET's own admission process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per TNEA norms\n- TNEA cutoff score/rank for counselling-quota seats\n- Documents: Class 10/12 mark sheets, TNEA application/rank card, community certificate (Tamil Nadu candidates), transfer certificate, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "SKCET's placement cell runs steady campus drives concentrated in IT services, with CSE and IT posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Zoho (select product-engineering roles)\n- Amazon for select high-performing CSE graduates" },
    { tab: "cutoffs", heading: "TNEA Cutoffs (Indicative)", body: "| Branch | Approx. TNEA Cutoff (Open Category, out of 200) |\n|---|---|\n| Computer Science & Engineering | 185 – 193 |\n| Information Technology | 180 – 188 |\n| Electronics & Communication | 172 – 182 |\n| Mechanical Engineering | 160 – 172 |\n\nRanges are indicative from recent TNEA counselling years; exact cutoffs vary by round and category, confirm on the official TNEA portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Tamil Nadu government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible students\n- SKCET merit scholarships for top academic performers\n- Continuing merit scholarships tied to semester GPA\n- Need-based financial assistance through college-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Sri Krishna College of Engineering and Technology is ranked #83 in NIRF 2024 Engineering, a solid position for a self-financing, non-deemed private college within Tamil Nadu's competitive engineering-education landscape." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SKCET provides on-campus hostel accommodation for both men and women. Student life includes technical symposiums, cultural fests, and active sports and departmental clubs typical of an established private engineering college." },
  ],
};

const mmmut: CollegeContentPack = {
  slug: "madan-mohan-malaviya-university-of-technology",
  college: {
    estd: 1962,
    website: "https://www.mmmut.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹7 LPA",
    affiliation: "State University, Uttar Pradesh",
    approvedBy: "UGC, AICTE",
    metaTitle: "MMMUT Gorakhpur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Madan Mohan Malaviya University of Technology NIRF #84: B.Tech courses, fees, admission, placement stats, hostel details.",
    about:
      "Madan Mohan Malaviya University of Technology (MMMUT), tracing its origins to 1962 as MMM Engineering College and elevated to full state university status in 2013, is located in Gorakhpur, Uttar Pradesh. Named after the educationist and freedom-movement leader Madan Mohan Malaviya, it serves as a key regional technical institute for eastern Uttar Pradesh.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.0 L total" },
  ],
  placement: { avgPackage: "₹7 LPA", highestPackage: "₹34 LPA (indicative)", placedPct: "76" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "L&T", "Cognizant", "HCL"],
  highlights: [
    "Traces to MMM Engineering College (1962), state university status since 2013",
    "Named after educationist and freedom-movement leader Madan Mohan Malaviya",
    "Key regional technical institute for eastern Uttar Pradesh",
    "Admission via JEE Main score/UP state counselling",
  ],
  faqs: [
    { question: "Is MMMUT a good option?", answer: "MMMUT carries a long regional history as MMM Engineering College and now holds full state university status, serving as a key technical institute for eastern Uttar Pradesh with steady CSE and Electronics placement outcomes." },
    { question: "How is admission to MMMUT done?", answer: "MMMUT admits B.Tech students based on JEE Main rank through Uttar Pradesh state counselling processes, with seats allotted based on rank and category." },
  ],
  sections: [
    { tab: "info", heading: "About MMMUT", body: "Madan Mohan Malaviya University of Technology traces its origins to 1962, when it was established as MMM Engineering College in Gorakhpur, Uttar Pradesh. It was elevated to full state university status in 2013, becoming MMMUT, named after the noted educationist and freedom-movement leader Madan Mohan Malaviya. The university runs undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, and Civil Engineering.\n\nMMMUT serves as a key regional technical institute for eastern Uttar Pradesh, an area historically underserved relative to the state's western and central regions." },
    { tab: "info", heading: "Campus & Location", body: "The MMMUT campus spans a substantial site in Gorakhpur, eastern Uttar Pradesh, with academic blocks, hostels, a central library, and workshop facilities built up over more than six decades." },
    { tab: "info", heading: "Why Choose MMMUT", body: "- Long regional history dating to 1962, with full state university status since 2013\n- Key technical institute for eastern Uttar Pradesh\n- Comparatively accessible admission cutoffs relative to NITs\n- Government fee structure keeps costs low relative to private universities" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.0 L |\n| Electronics & Communication | 4 years | 90 | ₹5.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.0 L |\n| Civil Engineering | 4 years | 70 | ₹5.0 L |\n\nFees follow Uttar Pradesh state government university norms; SC/ST/OBC/EWS domicile students receive fee concessions under state policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Uttar Pradesh state government fee-reimbursement schemes apply for SC/ST/OBC/EWS domicile students. Fees are payable per semester through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "MMMUT admits B.Tech students based on JEE Main rank through Uttar Pradesh state counselling processes. Applicants apply through the relevant state counselling portal alongside their JEE Main application, with seats allotted based on rank and category." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per state norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "MMMUT's placement cell runs campus drives concentrated in IT services with core-engineering participation. CSE and Electronics graduates post the strongest outcomes; overall placement percentage has generally stayed in the high 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- Amazon for select CSE roles\n- L&T (core engineering)\n- Regional Uttar Pradesh infrastructure and manufacturing firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "MMMUT's JEE Main-based cutoffs have generally been more accessible than NITs given its state-university status; CSE seats fill first. These figures shift year to year — confirm current-year cutoffs on the official MMMUT/UP counselling portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Uttar Pradesh state government fee-reimbursement schemes for SC/ST/OBC/EWS domicile students\n- Merit scholarships for top academic performers\n- Institute-level need-based financial assistance\n- Central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "MMMUT is ranked #84 in NIRF 2024 Engineering, holding steady as a key regional technical institute for eastern Uttar Pradesh." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MMMUT provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const iiitDelhi: CollegeContentPack = {
  slug: "indraprastha-institute-of-information-technology-delhi",
  college: {
    estd: 2008,
    website: "https://www.iiitd.ac.in",
    feesNum: 900000,
    feesLabel: "₹9.0 L",
    packageLabel: "₹18 LPA",
    affiliation: "State University, Delhi",
    approvedBy: "UGC, AICTE",
    metaTitle: "IIIT Delhi — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIIT Delhi NIRF #85 engineering: B.Tech CSE/ECE courses, fees, JEE Main admission, placement package, hostel and scholarship details.",
    about:
      "Indraprastha Institute of Information Technology, Delhi (IIIT-D), established in 2008 as a state university by the Delhi government, is a research-focused, elite computer science institute with a comparatively small, highly selective undergraduate intake. Its placement outcomes are among the strongest of any institute outside the IIT system, driven by its Delhi location and a curriculum built around close industry-academia collaboration.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹9.0 L total" },
    { name: "B.Tech Electronics & Communication Engineering", duration: "4 years", seats: "60", feesLabel: "₹9.0 L total" },
    { name: "B.Tech Computer Science & Applied Mathematics", duration: "4 years", seats: "40", feesLabel: "₹9.0 L total" },
    { name: "B.Tech Computer Science & Design", duration: "4 years", seats: "30", feesLabel: "₹9.0 L total" },
  ],
  placement: { avgPackage: "₹18 LPA", highestPackage: "₹75 LPA (indicative)", placedPct: "93" },
  recruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "Adobe", "Sprinklr", "Rubrik", "Uber"],
  highlights: [
    "Delhi state university, founded 2008, elite research-focused CS institute",
    "Small, highly selective batches with placement outcomes among the strongest outside the IIT system",
    "Distinctive interdisciplinary programmes (CS & Applied Math, CS & Design)",
    "Admission via JEE Main score for its limited B.Tech seats",
  ],
  faqs: [
    { question: "How selective is IIIT Delhi's B.Tech programme?", answer: "IIIT-D's B.Tech intake is deliberately small (around 250 seats total across its programmes), making admission highly competitive with JEE Main cutoffs that rival several IITs for Computer Science." },
    { question: "What is CS & Applied Mathematics at IIIT Delhi?", answer: "It's a distinctive interdisciplinary B.Tech programme combining core computer science with applied mathematics, designed for students interested in algorithmic, quantitative, and research-oriented careers." },
  ],
  sections: [
    { tab: "info", heading: "About IIIT Delhi", body: "Indraprastha Institute of Information Technology, Delhi was established in 2008 as a state university by the Government of Delhi, built as a research-focused institute dedicated to information technology and computer science. It runs a comparatively small B.Tech intake across Computer Science & Engineering, Electronics & Communication Engineering, and two distinctive interdisciplinary programmes — Computer Science & Applied Mathematics, and Computer Science & Design.\n\nIIIT-D has built a reputation, particularly within the past decade, as one of the strongest computer science undergraduate programmes in India outside the IIT system, driven by close industry-academia collaboration and its Delhi location." },
    { tab: "info", heading: "Campus & Location", body: "The IIIT-D campus is located in Okhla, New Delhi, giving students direct access to the capital's dense corporate, consulting, and technology-company base — a significant advantage for internships and placement drives." },
    { tab: "info", heading: "Why Choose IIIT Delhi", body: "- Elite, research-focused CS institute with placement outcomes among the strongest outside the IIT system\n- Distinctive interdisciplinary programmes (CS & Applied Math, CS & Design)\n- Small, highly selective batches with close faculty access\n- Delhi location gives direct access to a dense recruiter ecosystem" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹9.0 L |\n| Electronics & Communication Engineering | 4 years | 60 | ₹9.0 L |\n| Computer Science & Applied Mathematics | 4 years | 40 | ₹9.0 L |\n| Computer Science & Design | 4 years | 30 | ₹9.0 L |\n\nFees are charged per year; confirm current-year figures on the official IIIT-D admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "IIIT-D offers need-based and merit-based fee waivers, including concessions for Delhi-domicile students under state policy. Fees are payable per semester through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "IIIT-D admits its B.Tech students based on JEE Main rank, with a portion of seats reserved for Delhi-domicile candidates under the state government quota system alongside an all-India quota portion. Applicants apply through the institute's own centralised admission process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per IIIT-D norms\n- Valid JEE Main rank for the admission year\n- Delhi domicile certificate (for home-quota seats)\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIIT-D posts placement outcomes among the strongest of any institute outside the IIT system, with the large majority of its small B.Tech batch placed in software engineering, product, and research roles at leading technology and finance firms. High selectivity at admission combined with close industry ties contributes to consistently strong average and median packages." },
    { tab: "placements", heading: "Top Recruiters", body: "- Google, Microsoft, Amazon, Adobe (software/product)\n- Goldman Sachs (quant/analytics)\n- Sprinklr, Rubrik, Uber (high-growth product companies)\n- A dense base of Delhi-NCR technology and consulting recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "Given the very small B.Tech intake, JEE Main cutoff percentiles for CSE have typically required a percentile in the high 90s to low-mid 99s in recent years, rivaling several IITs for competitiveness. These figures are indicative — IIIT-D publishes exact cutoffs after each admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Need-based and merit-based fee waivers for eligible students\n- Delhi-domicile fee concessions under state policy\n- Research assistantships for students engaged in faculty-led projects\n- Institute merit scholarships for top JEE Main rank-holders" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIIT Delhi is ranked #85 in NIRF 2024 Engineering, a ranking that understates its reputation specifically within computer science circles, where it is regarded as one of India's stronger CS-focused undergraduate programmes." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIIT-D provides on-campus hostel accommodation for the large majority of students, though some Delhi-domicile students commute. Student life includes a dense calendar of hackathons, research talks, and industry-interaction events reflecting the institute's CS-research-first identity." },
  ],
};

const velTech: CollegeContentPack = {
  slug: "vel-tech-rangarajan-dr-sagunthala-randd-institute-of-science-and-technology",
  college: {
    estd: 1997,
    website: "https://www.veltech.edu.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹4 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Vel Tech R&D Institute — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Vel Tech Chennai NIRF #86 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology, founded in 1997 and granted deemed-university status, operates from a campus in Chennai, Tamil Nadu, and has built its identity around a strong research-publication output relative to its private-college fee level, alongside a wide engineering programme spread including Aeronautical and Robotics specialisations.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "360", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Aeronautical Engineering", duration: "4 years", seats: "90", feesLabel: "₹4.8 L total" },
    { name: "B.Tech Robotics & Automation", duration: "4 years", seats: "60", feesLabel: "₹4.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹4.5 L total" },
  ],
  placement: { avgPackage: "₹4 LPA", highestPackage: "₹34 LPA (indicative)", placedPct: "74" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)"],
  highlights: [
    "Deemed university since the early 2000s, founded 1997 in Chennai",
    "Strong research-publication output relative to private-college fee level",
    "Distinctive Aeronautical Engineering and Robotics & Automation programmes",
    "Admission via own entrance test or TNEA/JEE Main score",
  ],
  faqs: [
    { question: "Is Vel Tech good for Robotics?", answer: "Vel Tech's Robotics & Automation programme is one of its distinctive offerings, backed by the institute's broader research-publication focus, though prospective students should evaluate specific lab infrastructure and faculty before enrolling." },
    { question: "How is admission to Vel Tech done?", answer: "Vel Tech admits students through its own entrance examination, or directly via TNEA rank (Tamil Nadu domicile) or JEE Main score (out-of-state applicants)." },
  ],
  sections: [
    { tab: "info", heading: "About Vel Tech", body: "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology was founded in 1997 and granted deemed-to-be-university status, operating from a campus in Chennai, Tamil Nadu. The institute has built its identity substantially around research-publication output, investing heavily in faculty research activity relative to its private-college fee level, which has helped drive its NIRF ranking.\n\nVel Tech runs a wide engineering programme spread including Computer Science, Aeronautical Engineering, Robotics & Automation, and Electronics & Communication, among other specialisations." },
    { tab: "info", heading: "Campus & Facilities", body: "The Vel Tech campus in Chennai includes academic blocks, dedicated Aeronautical and Robotics labs, a central library, and sports facilities typical of an established private deemed university." },
    { tab: "info", heading: "Why Choose Vel Tech", body: "- Strong research-publication output relative to fee level, contributing to its NIRF ranking\n- Distinctive Aeronautical Engineering and Robotics & Automation programmes\n- Deemed-university flexibility in curriculum design\n- Multiple admission routes (own entrance test, TNEA, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 360 | ₹5.0 L |\n| Aeronautical Engineering | 4 years | 90 | ₹4.8 L |\n| Robotics & Automation | 4 years | 60 | ₹4.8 L |\n| Electronics & Communication | 4 years | 150 | ₹4.5 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Vel Tech admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Vel Tech offers merit-based fee waivers tied to entrance rank or Class 12 percentage at admission. Fees are payable in semester instalments through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Vel Tech admits B.Tech students through its own entrance examination, or directly via TNEA rank (Tamil Nadu domicile) or JEE Main score (out-of-state applicants). Applicants apply online, and seats are allotted through Vel Tech's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score/rank via the chosen admission route\n- Documents: Class 10/12 mark sheets, entrance scorecard/TNEA rank card, community certificate (Tamil Nadu candidates), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Vel Tech's placement cell runs drives concentrated in IT services, with CSE posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Amazon for select high-performing CSE graduates\n- Regional Chennai IT and aerospace-adjacent firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the TNEA route, CSE cutoff scores have typically required a moderate Class 12 cutoff (out of 200) in recent years for open category; for the university's own entrance test, cutoffs are set relative to the year's applicant pool. Confirm current-year cutoffs directly with Vel Tech admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/Class 12-percentage merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Tamil Nadu state government scholarship schemes for eligible domicile students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Vel Tech is ranked #86 in NIRF 2024 Engineering and also features in NIRF's Research and Overall University categories, reflecting its research-output-driven ranking strategy." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Vel Tech provides on-campus hostel accommodation for men and women across its Chennai campus. Student life includes technical fests centred on its aeronautical and robotics programmes, plus cultural events and sports facilities." },
  ],
};

const iiitAllahabad: CollegeContentPack = {
  slug: "indian-institute-of-information-technology-allahabad",
  college: {
    estd: 1999,
    website: "https://www.iiita.ac.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹16 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIIT Allahabad — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIIT Allahabad NIRF #87 engineering: B.Tech CSE/ECE/IT courses, fees, JoSAA admission, placement package, hostel details.",
    about:
      "Indian Institute of Information Technology, Allahabad (IIIT-A), established in 1999 and among the first IIITs founded, is a fully government-funded Institute of National Importance located in Prayagraj, Uttar Pradesh. Unlike the newer PPP-model IIITs, IIIT-A is entirely centrally funded, running well-regarded Computer Science, Electronics, and Information Technology B.Tech programmes admitted through JoSAA.",
  },
  courses: [
    { name: "B.Tech Information Technology", duration: "4 years", seats: "120", feesLabel: "₹7.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹7.0 L total" },
    { name: "B.Tech Computer Science & Engineering (IT dual-specialisation)", duration: "4 years", seats: "60", feesLabel: "₹7.0 L total" },
  ],
  placement: { avgPackage: "₹16 LPA", highestPackage: "₹58 LPA (indicative)", placedPct: "90" },
  recruiters: ["Amazon", "Microsoft", "Goldman Sachs", "Adobe", "Sprinklr", "Samsung R&D", "Deloitte", "Qualcomm"],
  highlights: [
    "Among the first IIITs founded (1999), fully government-funded Institute of National Importance",
    "Strong placement outcomes rivaling several NITs and some IITs",
    "Located in Prayagraj, Uttar Pradesh",
    "Admission via JEE Main rank through JoSAA",
  ],
  faqs: [
    { question: "Is IIIT Allahabad different from newer PPP-model IIITs?", answer: "Yes — IIIT Allahabad is fully government-funded and holds Institute of National Importance status, unlike many newer IIITs set up under a public-private partnership model, giving it a funding structure and prestige closer to NITs." },
    { question: "What is IIIT Allahabad's cutoff?", answer: "IT and CSE closing ranks at IIIT Allahabad have typically fallen in the 8,000-12,000 band (General) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About IIIT Allahabad", body: "Indian Institute of Information Technology, Allahabad was established in 1999, among the first IIITs founded in India. Unlike many newer IIITs set up under a public-private partnership model, IIIT-A is fully government-funded and holds Institute of National Importance status, located in Prayagraj (formerly Allahabad), Uttar Pradesh. It runs well-regarded B.Tech programmes in Information Technology, Electronics & Communication, and a dual-specialisation Computer Science & Engineering track.\n\nIIIT-A has built a strong reputation specifically within information technology and computer science circles, with placement outcomes that regularly compete with several NITs and even some IITs." },
    { tab: "info", heading: "Campus & Location", body: "The IIIT-A campus is located in Jhalwa, Prayagraj, Uttar Pradesh, with academic blocks, hostels, a central library, and specialised computing labs built around the institute's IT-and-CS focus." },
    { tab: "info", heading: "Why Choose IIIT Allahabad", body: "- Fully government-funded Institute of National Importance, unlike PPP-model IIITs\n- Strong placement outcomes rivaling several NITs and some IITs\n- Specialised, singularly IT-and-CS-focused curriculum\n- JoSAA-based admission credibility" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Information Technology | 4 years | 120 | ₹7.0 L |\n| Electronics & Communication | 4 years | 90 | ₹7.0 L |\n| Computer Science & Engineering (IT dual-specialisation) | 4 years | 60 | ₹7.0 L |\n\nFees follow a structure comparable to NITs given IIIT-A's Institute of National Importance status; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and General/OBC/EWS students with family income under the prescribed threshold, consistent with central-institute fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to IIIT-A's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, the same system used for NITs and older IIITs. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per JoSAA/IIIT norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIIT Allahabad's placement cell draws a strong base of software, product, and analytics recruiters given its focused IT-and-CS curriculum. Overall placement percentage has generally stayed around 90% across recent years, among the stronger outcomes of any institute in this ranking band." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Adobe, Sprinklr (software/product)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- Samsung R&D, Qualcomm (semiconductor/R&D)\n- A wide base of technology and consulting recruiters given its IT/CS focus" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Information Technology | 8,000 – 12,000 |\n| Computer Science & Engineering | 6,500 – 9,500 |\n| Electronics & Communication | 14,000 – 19,000 |\n\nRanges are indicative from recent JoSAA rounds; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIIT Allahabad is ranked #87 in NIRF 2024 Engineering, a ranking that understates its reputation specifically within IT and computer science circles among India's specialised information-technology institutes." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIIT-A provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical fests, hackathons, and cultural events reflecting the institute's IT-and-CS-focused identity." },
  ],
};

const jntuh: CollegeContentPack = {
  slug: "jawaharlal-nehru-technological-university-hyderabad",
  college: {
    estd: 1965,
    website: "https://www.jntuh.ac.in",
    feesNum: 400000,
    feesLabel: "₹4.0 L",
    packageLabel: "₹5 LPA",
    affiliation: "State Government University, Telangana",
    approvedBy: "UGC, AICTE",
    metaTitle: "JNTU Hyderabad — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "JNTUH NIRF #88 engineering: B.Tech affiliated colleges, fees, TS EAMCET admission, placement details, and scholarship info.",
    about:
      "Jawaharlal Nehru Technological University Hyderabad (JNTUH), established in 1965 and reconstituted as an independent university in 2008, is a state government affiliating university overseeing engineering education across a large network of colleges in Telangana. Like VTU, its NIRF ranking reflects the aggregate output of its vast affiliated-college system, named after India's first Prime Minister.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-3.5 L/year" },
    { name: "B.Tech Electronics & Communication (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-3 L/year" },
    { name: "B.Tech Mechanical Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-2.5 L/year" },
    { name: "B.Tech Civil Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1-2.5 L/year" },
  ],
  placement: { avgPackage: "₹5 LPA", highestPackage: "Varies significantly by affiliated college", placedPct: "68" },
  recruiters: ["TCS", "Infosys", "Wipro", "Cognizant", "Tech Mahindra", "HCL"],
  highlights: [
    "State affiliating university, established 1965, reconstituted independently in 2008",
    "Oversees engineering education across a large network of Telangana colleges",
    "Named after India's first Prime Minister, Jawaharlal Nehru",
    "Admission and outcomes vary significantly by individual affiliated college",
  ],
  faqs: [
    { question: "Is JNTUH a single college?", answer: "No — JNTUH is a state affiliating university, not a single-campus institute, overseeing curriculum, examinations, and degree conferral for a large network of engineering colleges across Telangana; outcomes vary substantially by the specific affiliated college." },
    { question: "How do I get admission to a JNTUH-affiliated college?", answer: "Admission to JNTUH-affiliated colleges is primarily through TS EAMCET (Telangana State Engineering, Agriculture and Medical Common Entrance Test), with individual colleges also running management-quota admissions." },
  ],
  sections: [
    { tab: "info", heading: "About JNTUH", body: "Jawaharlal Nehru Technological University Hyderabad was established in 1965 as part of the original JNTU system and was reconstituted as an independent university specific to the Hyderabad region in 2008, following the state's technical university restructuring. Named after India's first Prime Minister, JNTUH is a state affiliating university that sets curriculum, conducts examinations, and confers degrees across a large network of engineering colleges throughout Telangana.\n\nJNTUH's NIRF Engineering ranking reflects the aggregate academic output of this affiliated-college network rather than a single institutional campus, similar structurally to VTU in Karnataka." },
    { tab: "info", heading: "University Structure", body: "JNTUH's affiliated colleges span a wide quality range, from well-regarded institutions to smaller regional colleges. Prospective students should evaluate the specific affiliated college they are applying to — its placement record, faculty, and infrastructure — rather than relying solely on JNTUH's aggregate university-level ranking." },
    { tab: "info", heading: "Why Consider a JNTUH-Affiliated College", body: "- Wide choice of affiliated colleges across Telangana\n- Standardised curriculum and examination system across the network\n- Multiple admission routes (TS EAMCET, management quota) depending on the college\n- Fee levels generally lower than deemed/private universities outside the affiliating system" },
    { tab: "courses-fees", heading: "Programmes & Fee Structure (Varies by College)", body: "| Programme | Duration | Fee Range (approx., varies by college) |\n|---|---|---|\n| Computer Science & Engineering | 4 years | ₹1 L – ₹3.5 L per year |\n| Electronics & Communication | 4 years | ₹1 L – ₹3 L per year |\n| Mechanical Engineering | 4 years | ₹1 L – ₹2.5 L per year |\n| Civil Engineering | 4 years | ₹1 L – ₹2.5 L per year |\n\nFees vary substantially by the specific affiliated college and admission category (TS EAMCET convener quota vs management quota); confirm the exact figure with your chosen college." },
    { tab: "courses-fees", heading: "Fee Regulation", body: "TS EAMCET-counselled seats at JNTUH-affiliated colleges follow Telangana government-regulated fee slabs, which are typically lower than management-quota seats at the same college. Each affiliated college publishes its own fee structure per admission category." },
    { tab: "admissions", heading: "Admission Process", body: "Admission to JNTUH-affiliated colleges is primarily through TS EAMCET for Telangana-domicile students, with individual colleges also running a management-quota admission process directly. Applicants should apply to their specific college of choice through the relevant counselling process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per TS EAMCET norms\n- Valid TS EAMCET rank/score\n- Documents: Class 10/12 mark sheets, entrance scorecard, category/domicile certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Placement outcomes across JNTUH-affiliated colleges vary widely by institution — top affiliated colleges post strong IT-services placement, while smaller regional colleges see more modest outcomes. Prospective students should review the specific college's own placement report rather than relying on a university-wide aggregate." },
    { tab: "placements", heading: "Common Recruiters Across the Network", body: "- TCS, Infosys, Wipro, Cognizant, Tech Mahindra, HCL (the most common recruiters across JNTUH-affiliated colleges' IT-services drives)\n- Regional Telangana manufacturing and infrastructure firms for core branches\n- Product-company and analytics recruiters concentrate at the network's top-tier colleges" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative, Varies by College)", body: "TS EAMCET cutoff ranks vary enormously across JNTUH-affiliated colleges — top-tier colleges can require ranks in the low thousands for CSE, while many regional colleges admit at much higher (less competitive) ranks. Always check the specific college's cutoff trend rather than a university-wide figure." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Telangana state government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible TS EAMCET students\n- Individual affiliated colleges often run their own merit scholarships\n- Central government scholarship schemes for eligible students\n- Fee concessions vary by college — check directly with your chosen institution" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Jawaharlal Nehru Technological University Hyderabad is ranked #88 in NIRF 2024 Engineering as an aggregate university-level ranking; individual JNTUH-affiliated colleges may separately hold their own NIRF rankings and should be evaluated independently." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Hostel availability, quality, and campus life vary significantly by the specific JNTUH-affiliated college — most established colleges offer on-campus hostels, while smaller ones may have more limited accommodation. Check directly with your chosen college for specifics." },
  ],
};

export const engBatch7: CollegeContentPack[] = [
  sliet,
  coepPune,
  banasthali,
  nitSrinagar,
  rgipt,
  nitKurukshetra,
  nitAgartala,
  skcet,
  mmmut,
  iiitDelhi,
  velTech,
  iiitAllahabad,
  jntuh,
];
