import type { CollegeContentPack } from "./types";

// NIRF Engineering 2024 #51-63 — hand-authored, matches iit-madras.ts / eng-batch2-4.ts depth.

const iist: CollegeContentPack = {
  slug: "indian-institute-of-space-science-and-technology",
  college: {
    estd: 2007,
    website: "https://www.iist.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹12 LPA",
    affiliation: "Institute of National Importance, under ISRO",
    approvedBy: "Department of Space, Government of India",
    metaTitle: "IIST Thiruvananthapuram — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIST NIRF #51 engineering: B.Tech Aerospace/Avionics courses, fees, admission, ISRO recruitment, hostel and scholarship details.",
    about:
      "Indian Institute of Space Science and Technology (IIST), established in 2007 at Thiruvananthapuram, Kerala, is India's first institute dedicated exclusively to space science, technology, and applications, functioning as a constituent institute of the Department of Space (ISRO). Its B.Tech graduates are guaranteed a path into ISRO subject to performance, making it a uniquely mission-oriented engineering institute unlike any other on this list.",
  },
  courses: [
    { name: "B.Tech Aerospace Engineering", duration: "4 years", seats: "40", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Avionics", duration: "4 years", seats: "40", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electronics & Communication (Space)", duration: "4 years", seats: "30", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Engineering Physics", duration: "4 years", seats: "20", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹12 LPA", highestPackage: "₹40 LPA (indicative, non-ISRO offers)", placedPct: "95" },
  recruiters: ["ISRO", "DRDO", "Qualcomm", "Amazon", "Bosch", "Samsung R&D", "Analog Devices"],
  highlights: [
    "India's only institute of national importance dedicated solely to space science and technology",
    "Direct pathway into ISRO for graduates who clear performance criteria",
    "Admission via JEE rank-based merit list, distinct from standard JoSAA counselling",
    "Very small, highly selective batch sizes across Aerospace, Avionics, and Physics",
  ],
  faqs: [
    { question: "Do IIST graduates automatically join ISRO?", answer: "IIST B.Tech graduates who meet the required academic performance (typically maintaining a minimum CGPA) are entitled to ISRO recruitment; those who don't clear the bar, or who prefer other paths, are free to sit standard campus placements or pursue higher studies." },
    { question: "How is admission to IIST different from JoSAA?", answer: "IIST holds its own centralised counselling based on JEE (Advanced-linked) rank rather than being part of the standard JoSAA process used for IITs and NITs — applicants must separately register on the IIST admission portal." },
  ],
  sections: [
    { tab: "info", heading: "About IIST", body: "Indian Institute of Space Science and Technology was established in 2007 in Thiruvananthapuram, Kerala, as India's first institute of national importance built specifically around space science, technology, and applications. It functions as an autonomous institute under the Department of Space, working in close coordination with ISRO's research and mission programmes.\n\nIIST offers a distinctly narrow but deep curriculum: Aerospace Engineering, Avionics, Physical Sciences, and Chemistry, with Engineering Physics added as a newer option — all built around the specific talent needs of India's space programme rather than a general-purpose engineering menu." },
    { tab: "info", heading: "Campus & Location", body: "IIST's campus is located at Valiamala, near Thiruvananthapuram, Kerala, close to the Vikram Sarabhai Space Centre — one of ISRO's key research and development centres. This proximity allows for close collaboration on internships, projects, and eventual recruitment pathways into ISRO." },
    { tab: "info", heading: "Why Choose IIST", body: "- Only institute of national importance in India built specifically around space technology\n- Direct, performance-linked pathway into ISRO — a rare guaranteed-outcome track among Indian engineering institutes\n- Close physical and research proximity to ISRO's Vikram Sarabhai Space Centre\n- Small, highly selective batches with close faculty mentorship" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Aerospace Engineering | 4 years | 40 | ₹8.0 L |\n| Avionics | 4 years | 40 | ₹8.0 L |\n| Electronics & Communication (Space) | 4 years | 30 | ₹8.0 L |\n| Engineering Physics | 4 years | 20 | ₹8.0 L |\n\nFees follow a structure comparable to IITs given IIST's institute-of-national-importance status; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income under the prescribed threshold, consistent with central-institute fee-waiver policy. Fees are payable in two semester instalments through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Admission to IIST is based on rank in JEE (Advanced-linked merit), but candidates must separately register for IIST's own centralised counselling — it is not part of the standard JoSAA system used for IITs/NITs. Seats are allotted based on rank, category, and branch preference through IIST's dedicated admission portal." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE rank as per IIST's admission-year eligibility criteria\n- Documents: Class 10/12 mark sheets, JEE scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement & ISRO Pathway", body: "IIST's standout outcome is direct entry into ISRO for graduates who meet the required minimum CGPA — a guaranteed, performance-linked career pathway unique among Indian engineering institutes. Students who don't pursue or qualify for the ISRO track participate in campus placements or pursue postgraduate study, with strong outcomes given the institute's small, specialised talent pool." },
    { tab: "placements", heading: "Top Recruiters & ISRO", body: "- ISRO (primary pathway for eligible graduates)\n- DRDO (defence R&D)\n- Qualcomm, Analog Devices, Bosch (semiconductor/electronics)\n- Amazon, Samsung R&D (select roles for graduates opting outside the space sector)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "IIST's admission rank cutoffs have historically been competitive with mid-tier IITs given its small intake and the strong pull of a guaranteed ISRO pathway — Aerospace and Avionics seats fill first. These figures shift year to year; confirm current-year cutoffs on the official IIST admission portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute scholarships tied to strong academic performance\n- Department of Space-linked financial assistance schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIST is ranked #51 in NIRF 2024 Engineering — a strong position given its extremely narrow, specialised focus compared to general-purpose engineering institutes ranked around it." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIST provides on-campus hostel accommodation for its full undergraduate intake given the small batch sizes. Campus life is closely tied to space-sector academic culture, with strong participation in astronomy, rocketry, and satellite-building student projects and clubs." },
  ],
};

const grapicEra: CollegeContentPack = {
  slug: "graphic-era-university",
  college: {
    estd: 2008,
    website: "https://www.geu.ac.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹6 LPA",
    affiliation: "State Private University, Uttarakhand",
    approvedBy: "UGC, AICTE",
    metaTitle: "Graphic Era University — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Graphic Era University Dehradun NIRF #52 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Graphic Era University, founded in Dehradun, Uttarakhand and granted state private university status in 2008 (building on the earlier Graphic Era Institute of Technology established in 1993), has grown into one of North India's more placement-active private universities, with a large School of Computer Science alongside core engineering branches.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "480", feesLabel: "₹7.0 L total" },
    { name: "B.Tech CSE (AI & Data Science)", duration: "4 years", seats: "180", feesLabel: "₹7.2 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "120", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹6 LPA", highestPackage: "₹48 LPA (indicative)", placedPct: "80" },
  recruiters: ["Amazon", "TCS", "Infosys", "Wipro", "Cognizant", "HCL", "Capgemini", "ICICI Bank"],
  highlights: [
    "Founded 1993 as an institute, university status since 2008, based in Dehradun",
    "Large School of Computer Science with strong regional placement drive",
    "Growing NIRF presence for a relatively young private university",
    "Admission via JEE Main score or Graphic Era's own entrance test",
  ],
  faqs: [
    { question: "How is admission to Graphic Era University done?", answer: "Graphic Era admits students through JEE Main score or its own entrance-cum-merit process based on Class 12 marks, with branch-wise merit lists released across multiple rounds." },
    { question: "Is Graphic Era good for CSE?", answer: "Graphic Era's School of Computer Science is its largest and most placement-active department, drawing the bulk of the university's top recruiters and packages relative to its other engineering branches." },
  ],
  sections: [
    { tab: "info", heading: "About Graphic Era University", body: "Graphic Era University traces back to Graphic Era Institute of Technology, founded in 1993 in Dehradun, Uttarakhand, and was granted state private university status in 2008. It has grown into one of North India's more active private engineering universities, with a large School of Computer Science and Engineering as its flagship department, alongside Electronics, Mechanical, Civil, and allied branches.\n\nThe university has invested in building placement infrastructure and industry partnerships, helping it post a comparatively strong NIRF ranking for a relatively young institution founded within the past three decades." },
    { tab: "info", heading: "Campus & Facilities", body: "The Graphic Era campus in Dehradun includes academic blocks, computer labs, hostels, and sports facilities, situated in Uttarakhand's capital with its cooler hill-adjacent climate. The university has also expanded into a Hill University campus for select programmes." },
    { tab: "info", heading: "Why Choose Graphic Era University", body: "- Large, placement-active School of Computer Science and Engineering\n- Comparatively strong NIRF ranking for a university founded in the 1990s/2000s\n- Multiple admission routes (JEE Main, own entrance/merit) for flexibility\n- Dehradun location with a cooler climate than plains-based private universities" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 480 | ₹7.0 L |\n| CSE — AI & Data Science | 4 years | 180 | ₹7.2 L |\n| Electronics & Communication | 4 years | 120 | ₹6.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Graphic Era admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Graphic Era offers merit-based fee waivers tied to JEE Main percentile or Class 12 marks at admission. Fees are payable in semester instalments via the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Graphic Era University admits B.Tech students through JEE Main score-based merit or its own entrance-cum-merit process using Class 12 marks. Applicants apply online, and the university releases branch-wise merit lists across multiple counselling rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by branch/category)\n- Valid JEE Main score or qualifying Class 12 percentage as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard (if applicable), category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Graphic Era's placement cell runs campus drives concentrated in IT services with a growing base of analytics and BFSI recruiters. CSE and its AI/Data Science specialisation post the strongest outcomes; overall placement percentage has generally stayed around 80% across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Wipro, Cognizant, HCL, Capgemini (bulk IT-services hiring)\n- ICICI Bank and other BFSI recruiters\n- Regional Uttarakhand and North India IT/service firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a percentile in the 75-85 range in recent years; for the merit route, Class 12 aggregate requirements are typically 60%+ for CSE. These are indicative — confirm current-year cutoffs with Graphic Era admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Merit scholarships up to substantial tuition waiver based on JEE Main percentile/Class 12% at admission\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Education loan facilitation cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Graphic Era University is ranked #52 in NIRF 2024 Engineering and also features in NIRF's Overall University category, a notable result for a university that only received that status in 2008." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Graphic Era provides on-campus hostel accommodation for men and women with multiple mess-plan options. Student life includes technical fests, cultural events, and active sports facilities on the Dehradun campus." },
  ],
};

const saveethaTech: CollegeContentPack = {
  slug: "saveetha-institute-of-medical-and-technical-sciences",
  college: {
    estd: 2005,
    website: "https://www.saveetha.com",
    feesNum: 650000,
    feesLabel: "₹6.5 L",
    packageLabel: "₹4.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Saveetha Institute of Medical and Technical Sciences — Courses, Fees, Placements 2026",
    metaDescription: "SIMATS Chennai NIRF #53 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Saveetha Institute of Medical and Technical Sciences (SIMATS), founded in 2005 and granted deemed-university status, operates from Thandalam near Chennai, Tamil Nadu, combining a large medical and dental education ecosystem with an engineering school (Saveetha School of Engineering). The institute has invested heavily in research output, which has driven a notably fast rise in NIRF rankings across multiple categories.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹6.5 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "120", feesLabel: "₹6.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "120", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Biomedical Engineering", duration: "4 years", seats: "60", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹4.5 LPA", highestPackage: "₹38 LPA (indicative)", placedPct: "75" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)", "Zoho"],
  highlights: [
    "Deemed university combining a large medical/dental ecosystem with engineering (SIMATS)",
    "Fast-rising NIRF presence across Engineering, Dental, Medical, and Overall categories",
    "Distinctive Biomedical Engineering programme benefiting from the institute's medical-sciences base",
    "Admission via own entrance test or TNEA/JEE Main score",
  ],
  faqs: [
    { question: "Is Saveetha good for Biomedical Engineering?", answer: "Saveetha's engineering school benefits from the institute's large medical and dental education ecosystem, giving its Biomedical Engineering programme unusually close ties to clinical research and healthcare-technology projects." },
    { question: "What is SIMATS?", answer: "SIMATS stands for Saveetha Institute of Medical and Technical Sciences, the deemed-university umbrella covering Saveetha Medical College, Dental College, and Saveetha School of Engineering, all on the Thandalam campus near Chennai." },
  ],
  sections: [
    { tab: "info", heading: "About Saveetha Institute of Medical and Technical Sciences", body: "Saveetha Institute of Medical and Technical Sciences (SIMATS) was founded in 2005 and granted deemed-to-be-university status, operating from a large campus at Thandalam, near Chennai, Tamil Nadu. It is best known for its medical and dental colleges, but its engineering arm — Saveetha School of Engineering — has grown substantially, offering Computer Science, Electronics, Biomedical, and allied engineering programmes.\n\nSIMATS has invested heavily in research output and publication volume across all its schools, which has driven a rapid rise in its NIRF rankings across Engineering, Dental, Medical, and Overall University categories within a relatively short span." },
    { tab: "info", heading: "Campus & Facilities", body: "The Thandalam campus houses medical, dental, and engineering schools together, giving engineering students access to a large multi-disciplinary research ecosystem uncommon among standalone engineering colleges. Facilities include dedicated engineering labs, a large central library, and extensive sports infrastructure." },
    { tab: "info", heading: "Why Choose Saveetha", body: "- Access to a large multi-disciplinary medical/dental/engineering research ecosystem\n- Distinctive Biomedical Engineering programme with clinical research ties\n- Fast-rising NIRF presence across multiple categories\n- Multiple admission routes (own entrance test, TNEA, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 300 | ₹6.5 L |\n| CSE — AI & ML | 4 years | 120 | ₹6.8 L |\n| Electronics & Communication | 4 years | 120 | ₹6.0 L |\n| Biomedical Engineering | 4 years | 60 | ₹6.0 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official SIMATS admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "SIMATS offers merit-based fee waivers tied to entrance rank or Class 12 percentage at admission. Fees are payable in semester instalments through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "SIMATS admits B.Tech students through its own entrance examination, or directly via TNEA rank (Tamil Nadu domicile) or JEE Main score (out-of-state applicants). Applicants apply online, and seats are allotted through SIMATS's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score/rank via the chosen admission route\n- Documents: Class 10/12 mark sheets, entrance scorecard/TNEA rank card, community certificate (Tamil Nadu candidates), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Saveetha School of Engineering's placement cell runs drives concentrated in IT services, with CSE and its AI/ML specialisation posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Zoho (select product-engineering roles)\n- Amazon for select high-performing CSE graduates\n- Regional Chennai IT and healthcare-technology firms (aided by the medical/dental ecosystem)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the TNEA route, CSE cutoff scores have typically required a strong Class 12 cutoff (out of 200) in recent years for open category; for the university's own entrance test, ranks within the top few thousand test-takers are typically needed for CSE. Confirm current-year cutoffs directly with SIMATS admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/Class 12-percentage merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Tamil Nadu state government scholarship schemes for eligible domicile students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Saveetha Institute of Medical and Technical Sciences is ranked #53 in NIRF 2024 Engineering, alongside strong rankings in NIRF's Dental, Medical, and Overall University categories — reflecting its research-output-driven, multi-disciplinary growth strategy." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SIMATS provides on-campus hostel accommodation for men and women across its large Thandalam campus. Student life includes technical and cultural fests, plus access to healthcare and wellness events tied to the institute's medical-sciences base." },
  ],
};

const iitBhubaneswar: CollegeContentPack = {
  slug: "indian-institute-of-technology-bhubaneswar",
  college: {
    estd: 2008,
    website: "https://www.iitbbs.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹15 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Bhubaneswar — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Bhubaneswar NIRF #54 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Bhubaneswar, established in 2008 among the first batch of new-generation IITs, operates from a permanent campus at Argul, near Bhubaneswar, Odisha. It has built a research profile spanning Computer Science, Earth and Ocean Sciences, and Metallurgical Engineering, drawing students through JEE Advanced.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "90", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "80", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "80", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "50", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹15 LPA", highestPackage: "₹50 LPA (indicative)", placedPct: "84" },
  recruiters: ["Amazon", "Microsoft", "Qualcomm", "Goldman Sachs", "ONGC", "Samsung R&D", "Deloitte", "Tata Steel"],
  highlights: [
    "Second-generation IIT (2008), permanent campus at Argul near Bhubaneswar",
    "Notable research strength in Earth and Ocean Sciences alongside core engineering",
    "JEE Advanced is the sole admission route for B.Tech",
    "Growing placement network across software, core, and analytics recruiters",
  ],
  faqs: [
    { question: "Is IIT Bhubaneswar a good choice?", answer: "IIT Bhubaneswar offers the IIT brand, faculty, and placement network at a JEE Advanced cutoff more accessible than the older IITs, with particular research strength in Earth and Ocean Sciences alongside solid CSE and core-branch outcomes." },
    { question: "What is IIT Bhubaneswar's CSE cutoff?", answer: "CSE closing ranks at IIT Bhubaneswar have typically fallen in the 4,000-6,000 band (General) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Bhubaneswar", body: "Indian Institute of Technology Bhubaneswar was established in 2008 as one of the first batch of new IITs sanctioned that decade. Its permanent campus is located at Argul, roughly 25 km from Bhubaneswar, Odisha, running B.Tech programmes across Computer Science, Electrical, Mechanical, Civil, Metallurgical and Materials Engineering, alongside an interdisciplinary School of Earth, Ocean and Climate Sciences.\n\nThe institute has built a distinctive research niche in Earth and Ocean Sciences uncommon among IITs, alongside steadily growing strength in Computer Science and core engineering research." },
    { tab: "info", heading: "Campus & Location", body: "The Argul campus spans several hundred acres and includes academic blocks, hostels, a central library, and research centres built out over the institute's history. Its location near Bhubaneswar gives students access to Odisha's capital city and its growing IT and industrial base." },
    { tab: "info", heading: "Why Choose IIT Bhubaneswar", body: "- IIT pedigree and placement network at an accessible JEE Advanced cutoff\n- Distinctive Earth and Ocean Sciences research strength\n- Growing CSE and core-branch placement outcomes\n- Compact batch sizes with close faculty interaction" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 90 | ₹8.0 L |\n| Electrical Engineering | 4 years | 80 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 80 | ₹8.0 L |\n| Civil Engineering | 4 years | 50 | ₹8.0 L |\n\nFees follow the standard IIT structure; full tuition waivers apply for SC/ST, PwD, and income-eligible General/OBC students." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and General/OBC students with family income under ₹5 lakh/year, per common IIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "B.Tech admission is exclusively via JEE Advanced rank through JoSAA counselling. Candidates must qualify JEE Main, rank in the top ~2.5 lakh to be eligible for JEE Advanced, and register their preferences on JoSAA for seat allotment across multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Bhubaneswar's placement cell draws software, core engineering, and analytics recruiters, with CSE and Electrical graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 80s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Qualcomm, Samsung R&D (software/semiconductor)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- ONGC, Tata Steel (core/PSU)\n- Regional Odisha manufacturing and infrastructure firms" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 4,000 – 6,000 |\n| Electrical Engineering | 8,500 – 11,500 |\n| Mechanical Engineering | 12,000 – 16,000 |\n| Civil Engineering | 15,000 – 19,000 |\n\nRanges are indicative from recent JoSAA rounds; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Bhubaneswar is ranked #54 in NIRF 2024 Engineering, reflecting steady growth in research output and placement metrics since its 2008 founding." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "The Argul campus provides separate hostel blocks for undergraduate men and women with mess facilities on a rotating menu. Student life includes technical and cultural fests, along with active sports and departmental clubs." },
  ],
};

const nitPatna: CollegeContentPack = {
  slug: "national-institute-of-technology-patna",
  college: {
    estd: 1886,
    website: "https://www.nitp.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹8.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Patna — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Patna NIRF #55 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Patna, tracing its origins to Bihar College of Engineering founded in 1886 (making it one of India's oldest engineering colleges) and elevated to NIT status in 2004, is Bihar's premier technical institute. Located in Patna, it draws students nationwide through JoSAA with programmes spanning Computer Science, Electronics, Mechanical, and Civil Engineering.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "110", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹8.5 LPA", highestPackage: "₹40 LPA (indicative)", placedPct: "78" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "L&T", "ONGC", "Cognizant", "Deloitte"],
  highlights: [
    "Traces to 1886 as Bihar College of Engineering — among India's oldest engineering institutes",
    "NIT status since 2004, Bihar's premier technical institute",
    "Steady CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "How old is NIT Patna?", answer: "NIT Patna traces its origins to Bihar College of Engineering, founded in 1886, making it one of the oldest engineering institutions in India, though it only received NIT (Institute of National Importance) status in 2004." },
    { question: "What is NIT Patna's CSE cutoff?", answer: "CSE closing ranks at NIT Patna have typically fallen in the 15,000-20,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Patna", body: "National Institute of Technology, Patna traces its history to Bihar College of Engineering, founded in 1886 — making it one of the oldest engineering institutions in India, predating even most of the older IITs by decades. It was elevated to National Institute of Technology status in 2004, gaining Institute of National Importance recognition, and now runs undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, and Civil Engineering.\n\nAs Bihar's premier technical institute, NIT Patna carries significant regional prestige alongside its national NIT standing, drawing students from across eastern India." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Patna campus is located in Patna, Bihar's capital, giving it strong connectivity relative to some other regional NITs. The campus includes academic blocks, hostels, a central library, and workshop facilities built up over its long institutional history." },
    { tab: "info", heading: "Why Choose NIT Patna", body: "- Among India's oldest engineering institutions, with nearly 140 years of history\n- NIT brand and placement network at accessible JoSAA cutoffs relative to older NITs\n- Central Patna location with strong regional connectivity\n- Steady CSE and Electronics placement outcomes" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 110 | ₹5.5 L |\n| Electronics & Communication | 4 years | 90 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n| Civil Engineering | 4 years | 70 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Patna's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Patna's placement cell runs campus drives across IT services with growing core-sector and analytics participation. CSE and Electronics graduates post the strongest outcomes; overall placement percentage has generally stayed in the high 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant (bulk IT-services hiring)\n- Amazon for select CSE roles\n- L&T, ONGC (core/PSU)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 15,000 – 20,000 |\n| Electronics & Communication | 25,000 – 32,000 |\n| Mechanical Engineering | 35,000 – 45,000 |\n| Civil Engineering | 45,000 – 55,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Bihar state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Patna is ranked #55 in NIRF 2024 Engineering, holding steady as Bihar's top-ranked technical institute." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Patna provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const manipalInstitute: CollegeContentPack = {
  slug: "manipal-institute-of-technology",
  college: {
    estd: 1957,
    website: "https://manipal.edu/mit.html",
    feesNum: 1200000,
    feesLabel: "₹12.0 L",
    packageLabel: "₹8 LPA",
    affiliation: "Deemed University (MAHE)",
    approvedBy: "UGC, AICTE",
    metaTitle: "Manipal Institute of Technology — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "MIT Manipal NIRF #56 engineering: B.Tech courses, fees, MET admission, placement stats, hostel and scholarship details.",
    about:
      "Manipal Institute of Technology (MIT Manipal), founded in 1957, is the founding constituent institution of Manipal Academy of Higher Education (MAHE) and one of India's earliest private engineering colleges. Its Manipal, Karnataka campus is part of a large, self-contained university town, and MIT has built one of the most recognised private-engineering brands in India, particularly for Computer Science and Information Technology.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹12.0 L total" },
    { name: "B.Tech Information Technology", duration: "4 years", seats: "120", feesLabel: "₹11.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹10.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹9.5 L total" },
  ],
  placement: { avgPackage: "₹8 LPA", highestPackage: "₹58 LPA (indicative)", placedPct: "85" },
  recruiters: ["Amazon", "Microsoft", "Goldman Sachs", "TCS", "Infosys", "Deloitte", "Qualcomm", "Cisco"],
  highlights: [
    "Founding institute of Manipal Academy of Higher Education (MAHE), established 1957",
    "One of India's most recognised private-engineering brands, especially for CSE/IT",
    "Part of a large, self-contained university town in coastal Karnataka",
    "Admission via MET (Manipal Entrance Test) or JEE Main score",
  ],
  faqs: [
    { question: "What is MET?", answer: "MET (Manipal Entrance Test) is MIT Manipal's own online entrance examination; applicants can alternatively use their JEE Main score for admission to select programmes, depending on the year's admission policy." },
    { question: "Is MIT Manipal a good private engineering college?", answer: "MIT Manipal is widely regarded as one of India's top private engineering institutes, particularly for Computer Science and IT, with a well-established placement network and one of the longest track records among private engineering colleges founded before Independence-era expansion." },
  ],
  sections: [
    { tab: "info", heading: "About MIT Manipal", body: "Manipal Institute of Technology was founded in 1957 by Dr. T. M. A. Pai as the founding constituent institution of what later became Manipal Academy of Higher Education (MAHE), a deemed university. It is among India's oldest private engineering colleges, and its long track record has helped it build one of the most recognised private-engineering brands nationally, particularly in Computer Science, Information Technology, and Electronics.\n\nMIT Manipal operates as part of MAHE's large, multi-disciplinary Manipal campus in coastal Karnataka, alongside medical, dental, and other professional schools under the same university umbrella." },
    { tab: "info", heading: "Campus & Location", body: "The Manipal campus is a large, self-contained university town in coastal Karnataka, near Udupi, with academic blocks, extensive hostel infrastructure, hospitals, and a full campus ecosystem shared across MAHE's various schools. The setting gives students access to both a quiet coastal environment and a dense multi-disciplinary academic community." },
    { tab: "info", heading: "Why Choose MIT Manipal", body: "- Among India's oldest and most recognised private-engineering brands\n- Strong placement network, particularly for CSE, IT, and Electronics\n- Access to MAHE's large multi-disciplinary university ecosystem\n- Multiple admission routes (MET, JEE Main) for flexibility" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 300 | ₹12.0 L |\n| Information Technology | 4 years | 120 | ₹11.0 L |\n| Electronics & Communication | 4 years | 150 | ₹10.5 L |\n| Mechanical Engineering | 4 years | 120 | ₹9.5 L |\n\nFees are among the higher end of private engineering colleges given MIT's brand strength; confirm current-year figures on the official Manipal admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "MIT Manipal offers merit-based fee waivers tied to MET/JEE Main rank at admission, along with continuing merit scholarships for top academic performers. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "MIT Manipal offers admission through MET (Manipal Entrance Test), its own computer-based test held across multiple cities, or direct admission based on JEE Main rank for a portion of seats. Applicants apply online, sit MET if choosing that route, and are allotted seats through MAHE's own counselling process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by category)\n- Valid MET rank or JEE Main score/rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "MIT Manipal's Training and Placement Cell runs one of the strongest placement drives among private engineering colleges, with CSE and IT drawing top-tier product-company and analytics offers. Overall placement percentage has stayed in the mid-to-high 80s across recent years per institute placement reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Qualcomm, Cisco (product/software)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- TCS, Infosys (bulk IT-services hiring)\n- Additional strong presence from core-engineering and consulting recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the MET route, CSE admissions have typically required a rank within the top few thousand test-takers in recent years; for the JEE Main route, CSE cutoff percentiles have generally fallen in the 92-97 range. These are indicative — MIT Manipal publishes exact cutoffs after each admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- MET/JEE Main rank-based merit scholarships up to substantial tuition waivers for top ranks\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Education loan facilitation cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "MIT Manipal is ranked #56 in NIRF 2024 Engineering, and MAHE as a whole ranks highly in NIRF's Overall University, Medical, and Dental categories, reflecting its multi-disciplinary scale." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MIT Manipal provides extensive on-campus hostel accommodation as part of MAHE's large residential university town. Campus life includes the annual Revels cultural fest — one of India's larger college festivals — plus strong sports and international student community given MAHE's global exchange programmes." },
  ],
};

const nsut: CollegeContentPack = {
  slug: "netaji-subhas-university-of-technology",
  college: {
    estd: 1983,
    website: "https://www.nsut.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹13 LPA",
    affiliation: "State University, Delhi",
    approvedBy: "UGC, AICTE",
    metaTitle: "NSUT Delhi — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Netaji Subhas University of Technology NIRF #57 engineering: B.Tech courses, fees, JEE Main cutoffs, placement package, hostel details.",
    about:
      "Netaji Subhas University of Technology (NSUT), founded in 1983 as Delhi Institute of Technology and later Netaji Subhas Institute of Technology before being granted university status in 2018, is one of Delhi's most sought-after government engineering institutions. Located in Dwarka, New Delhi, it draws students through JEE Main via a Delhi-specific admission process, with a placement record among the strongest of any non-IIT government institute.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "180", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Information Technology", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "120", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.0 L total" },
  ],
  placement: { avgPackage: "₹13 LPA", highestPackage: "₹60 LPA (indicative)", placedPct: "88" },
  recruiters: ["Amazon", "Microsoft", "Goldman Sachs", "Adobe", "Deloitte", "Samsung R&D", "Sprinklr", "Uber"],
  highlights: [
    "Delhi government university, founded 1983, university status since 2018",
    "Among the strongest non-IIT government engineering placement records in India",
    "Dwarka, New Delhi campus with strong recruiter access given the capital location",
    "Admission via JEE Main score, largely through Delhi-specific admission rounds",
  ],
  faqs: [
    { question: "Is NSUT as good as an NIT?", answer: "NSUT's placement outcomes, particularly in Computer Science, are widely regarded as on par with or exceeding several NITs, helped significantly by its Delhi location and proximity to major tech and consulting recruiters." },
    { question: "What was NSUT called before?", answer: "NSUT was earlier known as Delhi Institute of Technology and then Netaji Subhas Institute of Technology (NSIT) before being granted full university status and renamed Netaji Subhas University of Technology in 2018." },
  ],
  sections: [
    { tab: "info", heading: "About NSUT", body: "Netaji Subhas University of Technology traces its origins to 1983, when it was established as Delhi Institute of Technology. It was later renamed Netaji Subhas Institute of Technology (NSIT) and eventually granted full state university status in 2018, becoming NSUT. Located in Dwarka, New Delhi, it is a Delhi government institution running undergraduate programmes across Computer Science, Information Technology, Electronics, Mechanical, and allied branches.\n\nNSUT has built a placement reputation that is unusually strong for a non-IIT, non-NIT government institute, driven substantially by its capital-city location and dense recruiter access." },
    { tab: "info", heading: "Campus & Location", body: "The NSUT campus in Dwarka, New Delhi, provides direct access to the capital's dense corporate, consulting, and technology-company base, a significant advantage for internships and placement drives relative to institutes in smaller cities." },
    { tab: "info", heading: "Why Choose NSUT", body: "- Among the strongest non-IIT government engineering placement records in India\n- Delhi location gives direct access to a dense recruiter and internship ecosystem\n- University status since 2018 with growing research programmes\n- Comparatively lower fees than most private universities given its government status" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 180 | ₹5.0 L |\n| Information Technology | 4 years | 90 | ₹5.0 L |\n| Electronics & Communication | 4 years | 120 | ₹5.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.0 L |\n\nFees follow Delhi government university norms, kept comparatively low relative to private institutes; confirm current-year figures on the official NSUT admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Fee concessions apply for SC/ST/OBC/EWS Delhi-domicile students per Delhi government policy. Fees are payable per semester through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "NSUT admits B.Tech students primarily through JEE Main rank, with a significant share of seats reserved for Delhi-domicile candidates under the Delhi government quota system, alongside an all-India quota portion. Applicants register through the relevant Delhi counselling process alongside their JEE Main application." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per NSUT norms\n- Valid JEE Main rank for the admission year\n- Delhi domicile certificate (for the home-quota seats)\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NSUT's placement cell draws a dense base of software, product, and consulting recruiters, aided significantly by its Delhi location. CSE and IT graduates post packages that compete with top NITs and some IITs; overall placement percentage has generally stayed in the mid-to-high 80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Adobe, Sprinklr, Uber (software/product)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- Samsung R&D (semiconductor/R&D)\n- A wide base of Delhi-NCR corporate and consulting recruiters" },
    { tab: "cutoffs", heading: "JoSAA/Delhi Quota Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 3,500 – 5,500 |\n| Information Technology | 5,000 – 7,500 |\n| Electronics & Communication | 8,000 – 11,000 |\n| Mechanical Engineering | 12,000 – 16,000 |\n\nRanges are indicative and differ meaningfully between Delhi-domicile and all-India quota seats; confirm current-year cutoffs on the official NSUT admissions portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Fee concessions for SC/ST/OBC/EWS Delhi-domicile students per government policy\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Central and Delhi government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NSUT is ranked #57 in NIRF 2024 Engineering, a strong position that reflects its placement strength and Delhi-location advantage relative to several NITs ranked around it." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NSUT provides on-campus hostel accommodation, though a meaningful share of Delhi-domicile students commute given the university's NCR location. Student life includes technical fests, cultural events, and active sports facilities on the Dwarka campus." },
  ],
};

const nitJalandhar: CollegeContentPack = {
  slug: "dr-b-r-ambedkar-national-institute-of-technology-jalandhar",
  college: {
    estd: 1987,
    website: "https://www.nitj.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹9.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Jalandhar — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Dr B R Ambedkar NIT Jalandhar NIRF #58 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel details.",
    about:
      "Dr. B R Ambedkar National Institute of Technology, Jalandhar, established in 1987 as a Regional Engineering College and elevated to NIT status in 2002, is Punjab's premier technical institute. Located in Jalandhar, it draws students nationwide through JoSAA, with programmes spanning Computer Science, Electronics, Mechanical, and Civil Engineering.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "100", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹9.5 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "82" },
  recruiters: ["Amazon", "TCS", "Infosys", "Wipro", "L&T", "Cognizant", "HCL", "Deloitte"],
  highlights: [
    "Punjab's premier NIT, founded 1987, NIT status since 2002",
    "Named after Dr. B R Ambedkar, located in Jalandhar",
    "Solid CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Jalandhar a good NIT?", answer: "NIT Jalandhar is Punjab's top-ranked NIT, with solid placement outcomes in Computer Science and Electronics and a well-established regional reputation across North India." },
    { question: "What is NIT Jalandhar's CSE cutoff?", answer: "CSE closing ranks at NIT Jalandhar have typically fallen in the 8,000-11,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Jalandhar", body: "Dr. B R Ambedkar National Institute of Technology, Jalandhar was established in 1987 as a Regional Engineering College and was granted National Institute of Technology status in 2002, later formally named after Dr. B R Ambedkar. Located in Jalandhar, Punjab, it serves as the state's premier technical institute, running undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, Civil, and Chemical Engineering.\n\nNIT Jalandhar has built a solid regional reputation across Punjab and neighbouring states, with a growing research profile alongside its undergraduate placement outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Jalandhar campus spans a substantial site in Jalandhar city, Punjab, with academic blocks, hostels, a central library, and workshop facilities. Its location provides good connectivity to Punjab's industrial and IT hubs." },
    { tab: "info", heading: "Why Choose NIT Jalandhar", body: "- Punjab's premier NIT with strong regional recognition\n- Solid CSE and Electronics placement outcomes\n- NIT brand and infrastructure at accessible JoSAA cutoffs relative to older NITs\n- Central Jalandhar location with strong North India connectivity" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.5 L |\n| Electronics & Communication | 4 years | 100 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n| Civil Engineering | 4 years | 70 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Jalandhar's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Jalandhar's placement cell runs solid campus drives across IT services, core engineering, and analytics recruiters, with CSE and Electronics posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s to low 80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- L&T (core engineering)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 8,000 – 11,000 |\n| Electronics & Communication | 14,000 – 18,000 |\n| Mechanical Engineering | 20,000 – 26,000 |\n| Civil Engineering | 26,000 – 34,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Punjab state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Jalandhar is ranked #58 in NIRF 2024 Engineering, holding steady as Punjab's top-ranked technical institute." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Jalandhar provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const svnitSurat: CollegeContentPack = {
  slug: "sardar-vallabhbhai-national-institute-of-technology",
  college: {
    estd: 1961,
    website: "https://www.svnit.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹11 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "SVNIT Surat — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Sardar Vallabhbhai NIT Surat NIRF #59 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel details.",
    about:
      "Sardar Vallabhbhai National Institute of Technology, Surat, established in 1961 as a Regional Engineering College and elevated to NIT status in 2002, is Gujarat's premier technical institute. Located in Surat's textile and diamond-trading business hub, it draws students nationwide through JoSAA, with recognised strength in Computer Science, Chemical, and Electrical Engineering.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "100", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Chemical Engineering", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹11 LPA", highestPackage: "₹46 LPA (indicative)", placedPct: "85" },
  recruiters: ["Amazon", "Microsoft", "L&T", "Reliance Industries", "ONGC", "Deloitte", "Cognizant", "Adani Group"],
  highlights: [
    "Gujarat's premier NIT, founded 1961, NIT status since 2002",
    "Located in Surat, a major business and industrial hub of Gujarat",
    "Strong CSE and Chemical Engineering outcomes, aided by nearby petrochemical industry",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is SVNIT Surat a good NIT?", answer: "SVNIT Surat is consistently ranked among the top 15-20 NITs nationally, with strong CSE outcomes and a well-regarded Chemical Engineering programme benefiting from Gujarat's petrochemical and industrial base." },
    { question: "What is SVNIT's CSE cutoff?", answer: "CSE closing ranks at SVNIT Surat have typically fallen in the 5,000-7,500 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About SVNIT Surat", body: "Sardar Vallabhbhai National Institute of Technology, Surat was established in 1961 as a Regional Engineering College and was granted National Institute of Technology status in 2002, named after India's first Deputy Prime Minister, Sardar Vallabhbhai Patel. Located in Surat, Gujarat — a major hub for textiles, diamond trading, and increasingly IT and industrial services — SVNIT runs undergraduate programmes across Computer Science, Electronics, Chemical, Mechanical, and Civil Engineering.\n\nSVNIT has built particular strength in Chemical Engineering, benefiting from Gujarat's dense petrochemical and industrial corridor, alongside solid Computer Science outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The SVNIT campus spans a substantial site in Surat, Gujarat, with academic blocks, hostels, a central library, and workshop facilities. Surat's status as a major business and industrial hub gives the institute strong regional recruiter access." },
    { tab: "info", heading: "Why Choose SVNIT Surat", body: "- Among the top 20 NITs nationally, with strong CSE and Chemical Engineering outcomes\n- Located in Surat, a major Gujarat business and industrial hub\n- Solid placement network aided by Gujarat's petrochemical corridor\n- NIT brand and infrastructure with accessible JoSAA cutoffs relative to older NITs" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.5 L |\n| Electronics & Communication | 4 years | 100 | ₹5.5 L |\n| Chemical Engineering | 4 years | 60 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to SVNIT Surat's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "SVNIT Surat's placement cell draws strong participation from software, petrochemical, and core-engineering recruiters given Gujarat's industrial base. CSE and Chemical Engineering post the strongest outcomes; overall placement percentage has stayed in the low-to-mid 80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft (software)\n- Reliance Industries, Adani Group, ONGC (petrochemical/energy — key for Chemical Engineering)\n- L&T, Deloitte (core engineering/consulting)\n- Cognizant and other IT-services recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 5,000 – 7,500 |\n| Electronics & Communication | 10,000 – 13,500 |\n| Chemical Engineering | 20,000 – 26,000 |\n| Mechanical Engineering | 16,000 – 21,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Gujarat state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "SVNIT Surat is ranked #59 in NIRF 2024 Engineering, holding a consistent position among the top 20 NITs nationally." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SVNIT provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes the annual technical fest Advitiya and cultural fest Ecstasy, plus active sports and departmental clubs." },
  ],
};

const mnnitAllahabad: CollegeContentPack = {
  slug: "motilal-nehru-national-institute-of-technology",
  college: {
    estd: 1961,
    website: "https://www.mnnit.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹10.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "MNNIT Allahabad — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Motilal Nehru NIT Prayagraj NIRF #60 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel details.",
    about:
      "Motilal Nehru National Institute of Technology (MNNIT), established in 1961 as a Regional Engineering College and elevated to NIT status in 2002, is Uttar Pradesh's premier technical institute, located in Prayagraj (formerly Allahabad). Named after India's first Prime Minister's father, MNNIT draws students nationwide through JoSAA, with well-regarded Computer Science and Electrical Engineering programmes.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "100", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹10.5 LPA", highestPackage: "₹44 LPA (indicative)", placedPct: "84" },
  recruiters: ["Amazon", "Microsoft", "TCS", "Infosys", "L&T", "ONGC", "Deloitte", "Samsung R&D"],
  highlights: [
    "Uttar Pradesh's premier NIT, founded 1961, NIT status since 2002",
    "Located in Prayagraj (formerly Allahabad), named after Motilal Nehru",
    "Solid CSE and Electrical Engineering placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is MNNIT Allahabad a good NIT?", answer: "MNNIT is consistently ranked among the top 15-20 NITs nationally, with solid CSE and Electrical Engineering placement outcomes and a strong regional reputation across Uttar Pradesh." },
    { question: "What is MNNIT's CSE cutoff?", answer: "CSE closing ranks at MNNIT have typically fallen in the 6,000-8,500 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About MNNIT Allahabad", body: "Motilal Nehru National Institute of Technology was established in 1961 as a Regional Engineering College and was granted National Institute of Technology status in 2002, named after Motilal Nehru, an eminent freedom-movement leader. Located in Prayagraj (formerly Allahabad), Uttar Pradesh, MNNIT is the state's premier technical institute, running undergraduate programmes across Computer Science, Electrical, Mechanical, Civil, and allied branches.\n\nMNNIT has built a strong regional reputation across Uttar Pradesh and neighbouring states, with steady research output alongside its undergraduate placement outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The MNNIT campus spans a substantial site in Prayagraj, a historic city known for its confluence of the Ganga and Yamuna rivers, with academic blocks, hostels, a central library, and workshop facilities." },
    { tab: "info", heading: "Why Choose MNNIT Allahabad", body: "- Among the top 20 NITs nationally, with solid CSE and Electrical Engineering outcomes\n- Uttar Pradesh's premier technical institute with strong regional recognition\n- NIT brand and infrastructure with accessible JoSAA cutoffs relative to older NITs\n- Historic Prayagraj location with rich cultural heritage" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.5 L |\n| Electrical Engineering | 4 years | 100 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n| Civil Engineering | 4 years | 70 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to MNNIT's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "MNNIT's placement cell runs solid campus drives across software, core engineering, and analytics recruiters, with CSE and Electrical graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the low-to-mid 80s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Samsung R&D (software/semiconductor)\n- TCS, Infosys (bulk IT-services hiring)\n- L&T, ONGC (core/PSU)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 6,000 – 8,500 |\n| Electrical Engineering | 12,000 – 16,000 |\n| Mechanical Engineering | 18,000 – 23,000 |\n| Civil Engineering | 24,000 – 30,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Uttar Pradesh state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "MNNIT Allahabad is ranked #60 in NIRF 2024 Engineering, holding a consistent position among the top 20 NITs nationally." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MNNIT provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes technical and cultural fests, plus active sports and departmental clubs." },
  ],
};

const iitTirupati: CollegeContentPack = {
  slug: "indian-institute-of-technology-tirupati",
  college: {
    estd: 2015,
    website: "https://www.iittp.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹13 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Tirupati — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Tirupati NIRF #61 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Tirupati, established in 2015 as part of the third wave of new IITs, operates from a developing permanent campus at Yerpedu, near Tirupati, Andhra Pradesh. As one of the youngest IITs, it carries the full IIT brand and JEE Advanced admission process while still building out its permanent infrastructure and research profile.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "70", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Civil & Infrastructure Engineering", duration: "4 years", seats: "40", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹13 LPA", highestPackage: "₹44 LPA (indicative)", placedPct: "80" },
  recruiters: ["Amazon", "TCS", "Infosys", "Qualcomm", "Deloitte", "ONGC", "Cognizant", "Samsung R&D"],
  highlights: [
    "Third-generation IIT (2015), developing campus at Yerpedu near Tirupati",
    "IIT brand and JEE Advanced admission at the most accessible cutoffs among IITs",
    "Growing research and placement infrastructure as a young institute",
    "JEE Advanced is the sole admission route for B.Tech",
  ],
  faqs: [
    { question: "Is IIT Tirupati a good choice despite being new?", answer: "As one of the youngest IITs, infrastructure and research depth are still developing relative to older IITs, but the core IIT brand, faculty quality, and placement network remain strong — and JEE Advanced cutoffs are among the most accessible in the IIT system." },
    { question: "What is IIT Tirupati's CSE cutoff?", answer: "CSE closing ranks at IIT Tirupati have typically fallen in the 6,000-8,500 band (General) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Tirupati", body: "Indian Institute of Technology Tirupati was established in 2015 as part of the third wave of new IITs sanctioned by the Government of India. It operates from a developing permanent campus at Yerpedu, near the temple town of Tirupati in Andhra Pradesh, running B.Tech programmes across Computer Science, Electrical, Mechanical, and Civil & Infrastructure Engineering.\n\nAs a young institute, IIT Tirupati is still expanding its permanent infrastructure and research centres, but it carries the full weight of the IIT brand, faculty hiring standards, and JEE Advanced-based admission process from day one." },
    { tab: "info", heading: "Campus & Location", body: "The Yerpedu campus is being developed in phases near Tirupati, Andhra Pradesh, a city with strong rail and air connectivity given its status as a major pilgrimage destination. Academic and hostel infrastructure continues to expand as the institute matures." },
    { tab: "info", heading: "Why Choose IIT Tirupati", body: "- IIT brand and JEE Advanced admission at among the most accessible cutoffs in the IIT system\n- Growing faculty and research base typical of newer IITs\n- Smaller batch sizes allowing closer faculty-student interaction\n- Andhra Pradesh location with good regional connectivity" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 70 | ₹8.0 L |\n| Electrical Engineering | 4 years | 60 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 60 | ₹8.0 L |\n| Civil & Infrastructure Engineering | 4 years | 40 | ₹8.0 L |\n\nFees follow the standard IIT structure; full tuition waivers apply for SC/ST, PwD, and income-eligible General/OBC students." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and General/OBC students with family income under ₹5 lakh/year, per common IIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "B.Tech admission is exclusively via JEE Advanced rank through JoSAA counselling. Candidates must qualify JEE Main, rank in the top ~2.5 lakh to be eligible for JEE Advanced, and register their preferences on JoSAA for seat allotment across multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Tirupati's placement cell draws software, core engineering, and analytics recruiters, with CSE graduates posting the strongest outcomes. Overall placement percentage has generally stayed around 80% across recent years as the institute's placement network continues to mature." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Qualcomm, Samsung R&D (software/semiconductor)\n- TCS, Infosys, Cognizant (IT services)\n- Deloitte (consulting/analytics)\n- ONGC and other core/PSU recruiters" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 6,000 – 8,500 |\n| Electrical Engineering | 11,000 – 15,000 |\n| Mechanical Engineering | 15,000 – 20,000 |\n| Civil & Infrastructure Engineering | 20,000 – 26,000 |\n\nRanges are indicative from recent JoSAA rounds; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Tirupati is ranked #61 in NIRF 2024 Engineering, a solid position for one of the newer IITs founded in 2015." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIT Tirupati provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity as the campus matures." },
  ],
};

const iitJammu: CollegeContentPack = {
  slug: "indian-institute-of-technology-jammu",
  college: {
    estd: 2016,
    website: "https://www.iitjammu.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹12.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Jammu — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Jammu NIRF #62 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Jammu, established in 2016 as part of the third wave of new IITs, operates from a developing permanent campus at Jagti, near Jammu. As one of the newest IITs, it serves as the flagship technical institute for the Jammu region, running core B.Tech programmes admitted via JEE Advanced.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "70", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "40", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹12.5 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Deloitte", "Cognizant", "ONGC", "L&T", "Samsung R&D"],
  highlights: [
    "Third-generation IIT (2016), developing campus at Jagti near Jammu",
    "Flagship technical institute for the Jammu and Kashmir/Ladakh region",
    "IIT brand and JEE Advanced admission at accessible cutoffs given its youth",
    "Growing research and placement infrastructure as a young institute",
  ],
  faqs: [
    { question: "Where is IIT Jammu located?", answer: "IIT Jammu operates from a developing campus at Jagti, near Jammu city, serving as the flagship technical institute for the Jammu and Kashmir region." },
    { question: "What is IIT Jammu's CSE cutoff?", answer: "CSE closing ranks at IIT Jammu have typically fallen in the 7,000-9,500 band (General) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Jammu", body: "Indian Institute of Technology Jammu was established in 2016 as part of the third wave of new IITs sanctioned by the Government of India. It operates from a developing permanent campus at Jagti, near Jammu city, running B.Tech programmes across Computer Science, Electrical, Mechanical, and Civil Engineering.\n\nAs the flagship technical institute for the Jammu and Kashmir region, IIT Jammu carries strategic importance for regional STEM education, alongside the standard IIT brand, faculty hiring standards, and JEE Advanced-based admission process." },
    { tab: "info", heading: "Campus & Location", body: "The Jagti campus near Jammu is being developed in phases, with academic and hostel infrastructure expanding as the institute matures. Jammu's connectivity to North India provides reasonable regional access despite the institute's relative youth." },
    { tab: "info", heading: "Why Choose IIT Jammu", body: "- IIT brand and JEE Advanced admission at among the most accessible cutoffs in the IIT system\n- Flagship technical institute for the Jammu and Kashmir region\n- Smaller batch sizes allowing closer faculty-student interaction\n- Growing faculty and research base typical of newer IITs" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 70 | ₹8.0 L |\n| Electrical Engineering | 4 years | 60 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 60 | ₹8.0 L |\n| Civil Engineering | 4 years | 40 | ₹8.0 L |\n\nFees follow the standard IIT structure; full tuition waivers apply for SC/ST, PwD, and income-eligible General/OBC students." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and General/OBC students with family income under ₹5 lakh/year, per common IIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "B.Tech admission is exclusively via JEE Advanced rank through JoSAA counselling. Candidates must qualify JEE Main, rank in the top ~2.5 lakh to be eligible for JEE Advanced, and register their preferences on JoSAA for seat allotment across multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Jammu's placement cell draws software, core engineering, and analytics recruiters, with CSE graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s across recent years as the institute's placement network continues to mature." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Samsung R&D (software/semiconductor)\n- TCS, Infosys, Cognizant (IT services)\n- Deloitte (consulting/analytics)\n- ONGC, L&T (core/PSU)" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 7,000 – 9,500 |\n| Electrical Engineering | 12,000 – 16,500 |\n| Mechanical Engineering | 16,000 – 21,000 |\n| Civil Engineering | 21,000 – 27,000 |\n\nRanges are indicative from recent JoSAA rounds; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Jammu is ranked #62 in NIRF 2024 Engineering, a solid position for one of the newest IITs founded in 2016." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIT Jammu provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity as the campus matures." },
  ],
};

const diatPune: CollegeContentPack = {
  slug: "defence-institute-of-advanced-technology",
  college: {
    estd: 1952,
    website: "https://www.diat.ac.in",
    feesNum: 600000,
    feesLabel: "₹6.0 L",
    packageLabel: "₹10 LPA",
    affiliation: "Deemed University, under Ministry of Defence",
    approvedBy: "UGC, Ministry of Defence",
    metaTitle: "DIAT Pune — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Defence Institute of Advanced Technology Pune NIRF #63 engineering: B.Tech courses, fees, admission, DRDO recruitment, hostel details.",
    about:
      "Defence Institute of Advanced Technology (DIAT), Pune, tracing its history to 1952 and operating under India's Ministry of Defence as a deemed university, is a specialised institute focused on defence and dual-use technologies. Its undergraduate programmes are comparatively small and niche, feeding directly into India's defence research and production ecosystem alongside civilian technology careers.",
  },
  courses: [
    { name: "B.Tech Electronics & Communication (Defence-focused)", duration: "4 years", seats: "40", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "40", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Mechanical Engineering (Armament-focused)", duration: "4 years", seats: "30", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹10 LPA", highestPackage: "₹38 LPA (indicative)", placedPct: "88" },
  recruiters: ["DRDO", "ISRO", "HAL", "BEL", "Amazon", "Qualcomm", "TCS"],
  highlights: [
    "Operates under India's Ministry of Defence, tracing history to 1952",
    "Specialised, defence-and-dual-use-technology-focused curriculum",
    "Strong DRDO and public-sector defence recruitment pipeline",
    "Small, highly focused undergraduate batch sizes",
  ],
  faqs: [
    { question: "What makes DIAT different from a regular engineering college?", answer: "DIAT operates under the Ministry of Defence and focuses its curriculum and research on defence and dual-use technologies, giving graduates a distinctive pathway into DRDO, defence PSUs, and related research organisations alongside standard private-sector careers." },
    { question: "How do I get admission to DIAT?", answer: "DIAT admits undergraduate students primarily through JEE Main rank-based merit, with its own centralised counselling process distinct from JoSAA — check the official DIAT admission notification for the current year's exact process." },
  ],
  sections: [
    { tab: "info", heading: "About DIAT Pune", body: "Defence Institute of Advanced Technology traces its institutional history to 1952 and functions today as a deemed university under India's Ministry of Defence, located in Pune, Maharashtra. Unlike most engineering institutes on this list, DIAT's curriculum and research agenda are explicitly built around defence and dual-use technologies, spanning armament engineering, defence electronics, and related specialisations alongside more conventional Computer Science and core engineering.\n\nDIAT's affiliation with the Ministry of Defence gives it close working relationships with DRDO and India's broader defence research ecosystem, shaping both its curriculum and its placement outcomes." },
    { tab: "info", heading: "Campus & Location", body: "The DIAT campus is located in Pune, Maharashtra — a city with a significant existing defence-research and manufacturing presence — with academic blocks, specialised defence-technology labs, hostels, and research centres." },
    { tab: "info", heading: "Why Choose DIAT Pune", body: "- Unique defence-and-dual-use-technology curriculum focus, unavailable at conventional engineering colleges\n- Strong DRDO and defence-PSU recruitment pipeline\n- Small, highly focused batch sizes with close faculty-student interaction\n- Pune location within Maharashtra's established defence-research ecosystem" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Electronics & Communication (Defence-focused) | 4 years | 40 | ₹6.0 L |\n| Computer Science & Engineering | 4 years | 40 | ₹6.0 L |\n| Mechanical Engineering (Armament-focused) | 4 years | 30 | ₹6.0 L |\n\nFees are charged per year; confirm current-year figures on the official DIAT admissions portal, as fee structures for Ministry of Defence-affiliated institutes are periodically revised." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "DIAT offers fee concessions and scholarships tied to merit and, in some cases, defence-personnel family background, consistent with its Ministry of Defence affiliation. Fees are payable per semester through the institute's designated channels." },
    { tab: "admissions", heading: "Admission Process", body: "DIAT admits undergraduate students primarily through JEE Main rank-based merit via its own centralised counselling process. Applicants apply through the DIAT admission portal, and seats are allotted based on rank, category, and branch preference across the institute's own counselling rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per DIAT norms\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "DIAT's placement outcomes are shaped significantly by its defence-technology focus, with strong recruitment from DRDO, defence PSUs, and related research organisations, alongside conventional private-sector software and core-engineering recruiters for students choosing that path. Overall placement percentage has generally been strong given the institute's small, specialised talent pool." },
    { tab: "placements", heading: "Top Recruiters", body: "- DRDO (Defence Research and Development Organisation — a primary recruiter)\n- HAL, BEL (defence public-sector undertakings)\n- ISRO (space-technology overlap roles)\n- Amazon, Qualcomm, TCS (private-sector software/electronics roles for graduates opting outside defence)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "DIAT's JEE Main-based cutoffs have historically been competitive given its small, specialised intake and the appeal of its unique defence-technology and DRDO pathway; Computer Science and Electronics seats fill first. These figures shift year to year — confirm current-year cutoffs on the official DIAT admission portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Merit-based fee concessions for top JEE Main rank-holders\n- Scholarships tied to defence-personnel family background, where applicable\n- Institute-level need-based financial assistance\n- Central government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Defence Institute of Advanced Technology is ranked #63 in NIRF 2024 Engineering, reflecting its specialised research strength in defence and dual-use technologies relative to conventional general-purpose engineering institutes." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "DIAT provides on-campus hostel accommodation for its full undergraduate intake given the small batch sizes. Campus life includes technical events tied closely to defence-technology themes, alongside standard sports and cultural activities typical of a compact, focused campus." },
  ],
};

export const engBatch5: CollegeContentPack[] = [
  iist,
  grapicEra,
  saveethaTech,
  iitBhubaneswar,
  nitPatna,
  manipalInstitute,
  nsut,
  nitJalandhar,
  svnitSurat,
  mnnitAllahabad,
  iitTirupati,
  iitJammu,
  diatPune,
];
