import type { CollegeContentPack } from "./types";

// NIRF Engineering 2024 #31-50 — hand-authored, matches iit-madras.ts / eng-batch2.ts depth.

const iitMandi: CollegeContentPack = {
  slug: "indian-institute-of-technology-mandi",
  college: {
    estd: 2009,
    website: "https://www.iitmandi.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹16 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Mandi — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Mandi NIRF #31 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Mandi, established in 2009 as one of the second-generation IITs, sits on a hillside campus in the Kamand valley of Himachal Pradesh. Built around a residential, research-driven model from day one, IIT Mandi has carved a niche in Computer Science, Data Science, and its interdisciplinary Human-Centred Design programme. Its campus master plan — spread across a series of ridgeline sites connected by shuttle roads — is unusual among IITs and shapes a close-knit, outdoors-oriented student culture.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "80", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "70", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "70", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "50", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹16 LPA", highestPackage: "₹58 LPA (indicative)", placedPct: "85" },
  recruiters: ["Microsoft", "Amazon", "Qualcomm", "Samsung R&D", "Goldman Sachs", "ONGC", "Sprinklr", "Adobe"],
  highlights: [
    "Second-generation IIT (2009), campus in the Kamand valley, Himachal Pradesh",
    "Strong Computer Science and Data Science placement record",
    "Unique School of Humanities and Social Sciences alongside core engineering",
    "JEE Advanced is the sole admission route for B.Tech",
  ],
  faqs: [
    { question: "Is IIT Mandi good for CSE?", answer: "Yes — CSE at IIT Mandi consistently posts the institute's highest packages and closing ranks tighter than most non-Delhi/Bombay/Madras IITs, reflecting strong recruiter interest." },
    { question: "What is the JEE Advanced cutoff for IIT Mandi?", answer: "CSE closing ranks for General category have typically fallen in the 3,500-5,500 band in recent JoSAA rounds; other branches close higher. Confirm the current year's cutoff on the JoSAA portal." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Mandi", body: "Indian Institute of Technology Mandi was established in 2009 in Himachal Pradesh as part of the second wave of new IITs. Its permanent campus, spread across the hills around Kamand village near Mandi town, is built as a series of interconnected zones rather than one flat quadrangle — a deliberate design that has shaped a hiking, outdoors-oriented campus culture unusual among Indian engineering institutes.\n\nThe institute runs B.Tech programmes in Computer Science, Electrical, Mechanical, and Civil Engineering, plus a distinctive interdisciplinary B.Tech in Data Science and Engineering. IIT Mandi is also known for its Catalysis and Sensing for Health (CASH) research cluster and for the School of Humanities and Social Sciences, which gives undergraduates broader elective options than most engineering-only institutes." },
    { tab: "info", heading: "Campus & Location", body: "The campus sits roughly 15 km from Mandi town in Himachal Pradesh, at an elevation that gives it a cooler climate than plains-based IITs. Facilities are distributed across the North Campus (academic blocks, library) and South Campus (some hostels and research centres), connected by a campus shuttle service. The setting is remote relative to Delhi or Bombay, which is both a draw (quiet, scenic, low-distraction) and an adjustment for students used to urban campuses." },
    { tab: "info", heading: "Why Choose IIT Mandi", body: "- IIT brand and faculty quality at a lower JEE Advanced cutoff than the older IITs\n- Strong CSE and Data Science outcomes, competitive with older IITs for top tech recruiters\n- Small batch sizes mean closer faculty-student interaction\n- Growing research output in AI, biotechnology, and renewable energy" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 80 | ₹8.0 L |\n| Electrical Engineering | 4 years | 70 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 70 | ₹8.0 L |\n| Civil Engineering | 4 years | 50 | ₹8.0 L |\n\nFees follow the standard IIT fee structure (~₹2 L/year tuition plus hostel and mess); SC/ST/PwD and income-eligible students receive full tuition waivers under the Ministry of Education's fee-waiver scheme." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "As with all IITs, tuition is waived for SC/ST students, PwD students, and General/OBC students from families with annual income below ₹5 lakh. Remaining students pay fees in two instalments per year through the institute's online portal; an education-loan support cell assists with bank loan documentation." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "Admission to all B.Tech programmes is exclusively through JEE Advanced rank and the JoSAA centralised counselling process. Candidates must first qualify JEE Main and rank within the top ~2.5 lakh to sit JEE Advanced, then register on JoSAA and list IIT Mandi branches in their choice order. Seats are allotted over multiple rounds based on rank, category, and seat availability." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Passed Class 12 (or equivalent) with Physics, Chemistry, and Mathematics\n- Valid JEE Advanced rank in the given admission year\n- Age and attempt-limit criteria as prescribed by JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Mandi's placement season regularly draws technology majors, core engineering firms, and analytics/finance recruiters. CSE and Data Science graduates report the strongest outcomes, with software and quant roles forming the bulk of high-package offers; core branches see steady public-sector and manufacturing recruitment alongside private-sector interest. Placement percentage across branches has stayed in the mid-to-high 80s in recent years, per institute placement reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Microsoft, Amazon, Adobe, Sprinklr (software)\n- Qualcomm, Samsung R&D (semiconductor/R&D)\n- Goldman Sachs, and other analytics/quant firms\n- ONGC and core PSU recruiters for Electrical/Mechanical/Civil branches" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 3,500 – 5,500 |\n| Electrical Engineering | 7,000 – 10,000 |\n| Mechanical Engineering | 10,000 – 14,000 |\n| Civil Engineering | 13,000 – 17,000 |\n\nRanges are indicative based on recent JoSAA rounds and vary by round and category; always verify against the official JoSAA seat-matrix for the current admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students (family income below ₹5 L/year)\n- Merit-cum-Means scholarships covering partial hostel/mess costs for economically weaker students\n- Institute Free Studentship for continuing students who maintain strong academic standing\n- External scholarships (state government, corporate CSR programmes) that many IIT Mandi students also access" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Mandi is ranked #31 in the NIRF 2024 Engineering category — a strong placement for an IIT founded as recently as 2009, reflecting fast-growing research output and placement outcomes relative to older, larger IITs." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Hostel accommodation is available across North and South Campus blocks, with mess facilities run on a rotating multi-cuisine basis. Campus life leans heavily on the surrounding hills — trekking and outdoor clubs are unusually active for an engineering campus — alongside standard technical and cultural fests (Spring Fest, Explorance)." },
  ],
};

const chandigarhUniversity: CollegeContentPack = {
  slug: "chandigarh-university",
  college: {
    estd: 2012,
    website: "https://www.cuchd.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹6.5 LPA",
    affiliation: "UGC recognised (State Private University, Punjab)",
    approvedBy: "UGC, AICTE",
    metaTitle: "Chandigarh University — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Chandigarh University NIRF #32 engineering: B.Tech courses, fees, admission criteria, placement drive numbers, hostel and scholarships.",
    about:
      "Chandigarh University, established in 2012 at Gharuan near Mohali, Punjab, has grown rapidly into one of India's largest private university campuses by placement volume, running an aggressive corporate-outreach placement model that puts thousands of students through campus drives each season. Its University Institute of Engineering and Technology (UIET) offers a wide spread of B.Tech specialisations, from core branches to newer programmes in AI, blockchain, and IoT.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "1200", feesLabel: "₹7.0 L total" },
    { name: "B.Tech CSE (AI & Machine Learning)", duration: "4 years", seats: "300", feesLabel: "₹7.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "240", feesLabel: "₹6.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "180", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹6.5 LPA", highestPackage: "₹1.28 Cr (indicative, Amazon/Microsoft top offers)", placedPct: "80" },
  recruiters: ["Amazon", "Microsoft", "Infosys", "TCS", "Wipro", "Accenture", "Capgemini", "ICICI Bank"],
  highlights: [
    "One of India's largest private-university placement drives by sheer offer count",
    "Wide branch spread including AI/ML, IoT, and blockchain specialisations",
    "NAAC A+ accredited, NIRF-ranked in both Engineering and University categories",
    "Sprawling single campus at Gharuan near Mohali, Punjab",
  ],
  faqs: [
    { question: "Is Chandigarh University good for placements?", answer: "CU runs one of the highest-volume campus placement drives among Indian private universities, with total offers regularly in the thousands each year, though the median/average package is moderate compared to top-tier institutes — check branch-wise placement reports for realistic expectations." },
    { question: "What is the admission process for Chandigarh University B.Tech?", answer: "Admission is via CUCET (Chandigarh University Common Entrance Test) score, JEE Main score, or Class 12 merit, depending on the programme and category — CU accepts multiple entry routes rather than a single mandatory exam." },
  ],
  sections: [
    { tab: "info", heading: "About Chandigarh University", body: "Chandigarh University (CU) was established in 2012 under the Chandigarh University Act as a state private university, with its main campus at Gharuan, roughly 20 km from Chandigarh in Mohali district, Punjab. It has since expanded into one of India's largest single-campus private universities by enrolment, with the University Institute of Engineering and Technology (UIET) as its flagship engineering school.\n\nCU's growth strategy has centred on scale — large batch sizes, a wide menu of specialisations (AI & ML, Data Science, IoT, Blockchain, Cyber Security alongside core CSE/ECE/Mechanical/Civil), and an unusually large in-house placement cell that runs high-volume recruiter drives each season." },
    { tab: "info", heading: "Campus & Facilities", body: "The Gharuan campus spans over 65 acres and houses academic blocks, an innovation and incubation centre, sports complexes, and multiple hostel blocks. CU markets itself heavily on infrastructure scale — large lecture theatres, dedicated labs per specialisation, and a campus-wide Wi-Fi and ERP system for academic administration." },
    { tab: "info", heading: "Why Choose Chandigarh University", body: "- Very high placement drive volume — more recruiters visit campus than at most private universities\n- Broad specialisation choice within CSE (AI/ML, Data Science, Cyber Security, IoT)\n- Multiple admission routes (CUCET, JEE Main, Class 12 merit) widen access\n- NAAC A+ accreditation and strong NIRF presence for a 2012-founded university" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 1200 | ₹7.0 L |\n| CSE — AI & Machine Learning | 4 years | 300 | ₹7.5 L |\n| Electronics & Communication | 4 years | 240 | ₹6.5 L |\n| Mechanical Engineering | 4 years | 180 | ₹6.0 L |\n\nFees are charged per year (roughly ₹1.5-1.9 L/year depending on branch) and vary by specialisation; CU periodically revises fee slabs, so confirm the current year's figure on the official CU admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "CU offers merit-based fee waivers ranging from 10% to 100% based on Class 12 percentage or CUCET/JEE Main score at the time of admission, plus an education-loan tie-up cell. Fees can be paid semester-wise through the university's online payment gateway." },
    { tab: "admissions", heading: "Admission Process", body: "Chandigarh University accepts three main routes for B.Tech admission: (1) CUCET, its own entrance test; (2) JEE Main score, used directly for merit-based admission to select branches; (3) Class 12 marks-based direct admission for certain programmes/categories. Applicants apply online, and CU releases branch-wise merit lists across several rounds through the admission season." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50% aggregate (varies by branch/category)\n- CUCET score, JEE Main score, or qualifying Class 12 percentage as per the chosen admission route\n- Documents: Class 10/12 mark sheets, entrance scorecard (if applicable), category certificate, transfer/migration certificate, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "CU's Training & Placement Cell runs one of the highest-volume drives among Indian private universities, with total offer counts regularly cited in the thousands across all programmes each placement season. CSE and AI/ML specialisations post the strongest packages; the university publishes branch-wise placement statistics each year, and prospective students should review those rather than relying on headline aggregate numbers, which blend a wide range of packages." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft (select high-package roles)\n- Infosys, TCS, Wipro, Accenture, Capgemini (mass IT recruitment — bulk of offers)\n- ICICI Bank and other BFSI recruiters\n- A wide base of regional and mid-size IT/service firms across drives" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "CU's multiple admission routes mean there is no single JoSAA-style cutoff. For the JEE Main-based route, CSE admissions have typically required a percentile in the 75-85 range in recent years; for the CUCET/merit route, Class 12 aggregate requirements are typically 60%+ for CSE and somewhat lower for other branches. These are indicative — confirm current-year cutoffs directly with CU admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Merit scholarships up to 100% tuition waiver based on Class 12%/entrance score at admission\n- Continuing merit scholarships for students maintaining top academic ranks each year\n- Sports and extracurricular quota scholarships\n- Education loan assistance cell for bank loan processing" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Chandigarh University is ranked #32 in NIRF 2024 Engineering and also features in NIRF's overall University and Innovation categories — a fast rise for an institution founded in 2012, driven largely by its placement volume and research-output growth." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "CU offers separate hostel blocks for men and women on the Gharuan campus with multiple room-sharing and mess-plan options. The campus runs an active technical-fest and cultural-fest calendar (Kalgidhar Cultural Fest, technical symposiums) and has a large in-house sports infrastructure including a cricket stadium." },
  ],
};

const amu: CollegeContentPack = {
  slug: "aligarh-muslim-university",
  college: {
    estd: 1920,
    website: "https://www.amu.ac.in",
    feesNum: 150000,
    feesLabel: "₹1.5 L",
    packageLabel: "₹7 LPA",
    affiliation: "Central University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Aligarh Muslim University (ZHCET) — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "AMU Zakir Husain College of Engineering NIRF #33: B.Tech courses, low fees, admission via AMUEEE, placement and hostel details.",
    about:
      "Aligarh Muslim University, founded in 1920 (building on the Muhammadan Anglo-Oriental College established in 1875), is one of India's oldest central universities. Engineering education is delivered through the Zakir Husain College of Engineering and Technology (ZHCET), one of the country's oldest engineering colleges, known for heavily subsidised government fees and a historic, self-contained residential campus in Aligarh, Uttar Pradesh.",
  },
  courses: [
    { name: "B.Tech Computer Engineering", duration: "4 years", seats: "60", feesLabel: "₹1.5 L total" },
    { name: "B.Tech Electronics Engineering", duration: "4 years", seats: "60", feesLabel: "₹1.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹1.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "60", feesLabel: "₹1.5 L total" },
  ],
  placement: { avgPackage: "₹7 LPA", highestPackage: "₹45 LPA (indicative)", placedPct: "70" },
  recruiters: ["TCS", "Infosys", "Wipro", "L&T", "ONGC", "Adobe", "Samsung", "Amazon"],
  highlights: [
    "One of India's oldest engineering colleges — ZHCET traces to 1920",
    "Government-subsidised fee structure among the lowest for a central university",
    "Historic residential campus with a century of engineering education heritage",
    "Admission via AMUEEE, AMU's own entrance exam",
  ],
  faqs: [
    { question: "How do I get admission to AMU engineering?", answer: "Admission to ZHCET B.Tech is through AMUEEE (AMU Engineering Entrance Exam), AMU's own entrance test — JEE Main/Advanced scores are not used for the main B.Tech intake." },
    { question: "What are AMU engineering fees?", answer: "AMU is a central university with heavily subsidised fees — B.Tech total fees are typically under ₹2 lakh for the full 4-year programme, among the lowest of any NIRF top-50 engineering institute." },
  ],
  sections: [
    { tab: "info", heading: "About AMU / ZHCET", body: "Aligarh Muslim University was established in 1920, evolving from the Muhammadan Anglo-Oriental College founded by Sir Syed Ahmad Khan in 1875. Engineering education at AMU is housed in the Zakir Husain College of Engineering and Technology (ZHCET), named after India's third President and one of the oldest engineering colleges in the country, with departments spanning Computer Engineering, Electronics, Mechanical, Civil, Chemical, and Petrochemical Engineering.\n\nAs a central university, AMU is directly funded by the Government of India, which keeps fees exceptionally low relative to private and even many state institutions, while its century-long academic heritage gives it a strong regional and national reputation, particularly across North India." },
    { tab: "info", heading: "Campus & Location", body: "The AMU campus in Aligarh, Uttar Pradesh spans over 400 acres and is one of India's most complete residential university towns, with its own schools, hospital (JN Medical College), mosques, and extensive hostel network. ZHCET occupies a dedicated section of this campus with departmental buildings, workshops, and laboratories built up over decades." },
    { tab: "info", heading: "Why Choose AMU Engineering", body: "- Among the lowest total fees of any NIRF top-50 engineering institute\n- Century-old academic heritage and strong alumni network across India and abroad\n- Self-contained residential campus with extensive non-academic infrastructure\n- Diverse specialisations including Petrochemical Engineering, uncommon at most institutes" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Engineering | 4 years | 60 | ₹1.5 L |\n| Electronics Engineering | 4 years | 60 | ₹1.5 L |\n| Mechanical Engineering | 4 years | 60 | ₹1.5 L |\n| Civil Engineering | 4 years | 60 | ₹1.5 L |\n\nAs a centrally funded university, AMU's fees are government-subsidised and among the lowest of any top-tier engineering institute in India — total 4-year fees typically fall under ₹2 lakh including hostel charges." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "Fees are paid semester-wise via the AMU online portal. Additional fee concessions apply for economically weaker sections and for wards of AMU employees, on top of the already low base fee structure." },
    { tab: "admissions", heading: "Admission Process (AMUEEE)", body: "Admission to ZHCET's B.Tech programmes is through AMUEEE — the AMU Engineering Entrance Exam — a computer-based test conducted by the university itself. Candidates apply online, sit the exam (typically covering Physics, Chemistry, and Mathematics), and are allotted seats through AMU's own counselling process based on AMUEEE rank and category, with a portion of seats reserved for internal AMU students under university rules." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 (or equivalent) pass with Physics, Chemistry, Mathematics, minimum aggregate as per AMU norms\n- Valid AMUEEE score in the admission year\n- Age criteria as prescribed by AMU\n- Documents: Class 10/12 mark sheets, AMUEEE admit card/scorecard, domicile/category certificate where applicable, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "ZHCET's Training & Placement Office conducts campus drives across IT services, core engineering, and public-sector recruiters. Placement outcomes are respectable for a central university with modest fees, with computer and electronics branches drawing the strongest recruiter interest; the placement percentage has generally stayed in the 65-75% range across branches in recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro (IT services)\n- L&T, ONGC (core/PSU)\n- Adobe, Samsung, Amazon (select roles for CS/Electronics graduates)\n- Regional manufacturing and infrastructure firms for Mechanical/Civil" },
    { tab: "cutoffs", heading: "AMUEEE Cutoffs (Indicative)", body: "| Branch | Approx. AMUEEE Rank Cutoff (General) |\n|---|---|\n| Computer Engineering | 200 – 500 |\n| Electronics Engineering | 500 – 1,000 |\n| Mechanical Engineering | 1,000 – 2,000 |\n| Civil Engineering | 1,500 – 2,500 |\n\nRanges are indicative based on recent years' closing ranks; AMU publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Central-government post-matric scholarships for SC/ST/OBC/minority students\n- AMU's own need-based fee concessions and freeships\n- Merit scholarships for top rank-holders in each department\n- Hostel fee concessions for economically weaker students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "AMU is ranked #33 in NIRF 2024 Engineering; AMU as a whole also ranks highly in NIRF's University and overall categories, reflecting its scale across law, medicine, and humanities alongside engineering." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "AMU has one of India's largest university hostel systems, with dozens of halls of residence across the campus, several dedicated substantially to engineering students. Campus life is deeply woven into AMU's century-old traditions — students' union elections, an active sports culture, and a full academic-year calendar of cultural and technical events." },
  ],
};

const iitPatna: CollegeContentPack = {
  slug: "indian-institute-of-technology-patna",
  college: {
    estd: 2008,
    website: "https://www.iitp.ac.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹14 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIT Patna — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIT Patna NIRF #34 engineering: B.Tech courses, fees, JEE Advanced cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Technology Patna, established in 2008 among the first batch of new-generation IITs, operates from a permanent campus at Bihta on the outskirts of Patna, Bihar. In under two decades it has built a research profile in areas like VLSI design, computational science, and materials engineering, while drawing students primarily through JEE Advanced to its core engineering branches.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "90", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "80", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "80", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "50", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹14 LPA", highestPackage: "₹52 LPA (indicative)", placedPct: "82" },
  recruiters: ["Amazon", "Microsoft", "Qualcomm", "Deloitte", "ONGC", "Samsung R&D", "Goldman Sachs", "Zomato"],
  highlights: [
    "First-generation of new IITs (2008), permanent campus at Bihta, Patna",
    "Growing research strength in VLSI design and computational engineering",
    "JEE Advanced sole admission route for B.Tech",
    "Compact batch sizes with a research-focused postgraduate ecosystem",
  ],
  faqs: [
    { question: "Is IIT Patna a good option?", answer: "IIT Patna offers the IIT brand, faculty, and placement network at a JEE Advanced cutoff lower than the older IITs, making it a strong option for students just outside the range for IIT Delhi/Bombay/Madras/Kanpur/Kharagpur." },
    { question: "What is IIT Patna's campus like?", answer: "IIT Patna operates from a permanent campus at Bihta, about 30 km from Patna city, with academic blocks, hostels, and research centres built out over the past decade." },
  ],
  sections: [
    { tab: "info", heading: "About IIT Patna", body: "Indian Institute of Technology Patna was established in 2008 as one of the first batch of new IITs sanctioned that decade. After operating from a transit campus, it moved to its permanent campus at Bihta on the western outskirts of Patna, Bihar, where it now runs undergraduate, postgraduate, and doctoral programmes across Computer Science, Electrical, Mechanical, Civil, Chemical, and Materials Science Engineering.\n\nThe institute has built research strength particularly in VLSI and semiconductor design, computational and data sciences, and structural/geotechnical engineering, supported by dedicated centres of excellence and sponsored research funding from government bodies." },
    { tab: "info", heading: "Campus & Location", body: "The Bihta campus spans several hundred acres and includes academic blocks, a central library, hostels, sports facilities, and a growing set of research centres. Its location outside central Patna gives it room for expansion but means students rely on institute transport for city access." },
    { tab: "info", heading: "Why Choose IIT Patna", body: "- IIT pedigree and placement network at a comparatively accessible JEE Advanced cutoff\n- Growing VLSI/semiconductor and computational research focus\n- Smaller batch sizes than older IITs, allowing closer faculty interaction\n- Central location for students from Bihar, Jharkhand, and eastern UP" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 90 | ₹8.0 L |\n| Electrical Engineering | 4 years | 80 | ₹8.0 L |\n| Mechanical Engineering | 4 years | 80 | ₹8.0 L |\n| Civil Engineering | 4 years | 50 | ₹8.0 L |\n\nFees follow the uniform IIT structure (~₹2 L/year), with full tuition waivers for SC/ST, PwD, and income-eligible General/OBC students." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST/PwD students and for General/OBC students with family income under ₹5 lakh/year, per the common IIT fee-waiver policy. Fees are paid in two semester instalments through the institute's online ERP portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced)", body: "B.Tech admission is exclusively via JEE Advanced rank through JoSAA counselling. Candidates must qualify JEE Main, rank in the top ~2.5 lakh to be eligible for JEE Advanced, and then register their branch/institute preferences on JoSAA for seat allotment across multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIT Patna's placement cell runs campus drives across software, core engineering, consulting, and analytics recruiters. CSE and Electrical graduates see the strongest package outcomes; overall placement percentage has generally stayed in the low-to-mid 80s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Zomato (software)\n- Qualcomm, Samsung R&D (semiconductor/R&D)\n- Deloitte, Goldman Sachs (consulting/analytics)\n- ONGC and core PSU recruiters for Mechanical/Civil/Electrical" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Engineering | 4,500 – 6,500 |\n| Electrical Engineering | 8,000 – 11,000 |\n| Mechanical Engineering | 11,000 – 15,000 |\n| Civil Engineering | 14,000 – 18,000 |\n\nRanges are indicative from recent JoSAA rounds; confirm the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full tuition waiver for SC/ST, PwD, and income-eligible General/OBC students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute Free Studentship for high-performing continuing students\n- MHRD/government scholarship schemes accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIT Patna is ranked #34 in NIRF 2024 Engineering, reflecting steady improvement in research output, faculty quality, and placement metrics since its 2008 founding." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "The Bihta campus provides separate hostel blocks for undergraduate men and women with mess facilities on a rotating menu system. Student life includes technical fest Anwesan and cultural fest Anugoonj, along with active sports and coding clubs." },
  ],
};

const klUniversity: CollegeContentPack = {
  slug: "koneru-lakshmaiah-education-foundation-university",
  college: {
    estd: 1980,
    website: "https://www.kluniversity.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹6 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "KL University (KLEF) — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "KL University Vaddeswaram NIRF #35 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Koneru Lakshmaiah Education Foundation (KL University), founded in 1980 and granted deemed-university status in 2009, operates a large campus at Vaddeswaram on the banks of the Krishna river near Vijayawada, Andhra Pradesh. It has grown into one of South India's largest private engineering deemed universities, with a strong emphasis on research output, industry tie-ups, and a wide spread of CSE specialisations.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "600", feesLabel: "₹5.5 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "240", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "180", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹4.5 L total" },
  ],
  placement: { avgPackage: "₹6 LPA", highestPackage: "₹52 LPA (indicative)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Cognizant", "Wipro", "Capgemini", "Deloitte", "Tech Mahindra"],
  highlights: [
    "Deemed-university status since 2009, campus on the Krishna riverbank near Vijayawada",
    "Strong research output relative to fee levels — NIRF-ranked in Engineering, Research, and Overall categories",
    "Wide CSE specialisation menu including AI/ML, IoT, Cyber Security",
    "Admission via KLUEEE (own entrance test) or JEE Main/EAMCET score",
  ],
  faqs: [
    { question: "How is admission done at KL University?", answer: "KL University admits students through its own KLUEEE entrance exam, or directly via JEE Main / AP EAMCET / TS EAMCET scores, giving applicants multiple routes into its B.Tech programmes." },
    { question: "Is KL University good for research?", answer: "KL University has built a comparatively strong research and publication output for a private deemed university, which is part of why it ranks in NIRF's Research and Overall categories in addition to Engineering." },
  ],
  sections: [
    { tab: "info", heading: "About KL University", body: "Koneru Lakshmaiah Education Foundation (KLEF), commonly known as KL University, traces back to 1980 and received deemed-to-be-university status from the UGC in 2009. Its main campus sits at Vaddeswaram on the banks of the Krishna river, close to Vijayawada and Guntur in Andhra Pradesh, with a secondary campus in Hyderabad.\n\nThe university has invested heavily in research infrastructure and faculty publication output, which has helped it climb NIRF's Engineering, Research, and Overall university rankings faster than many peer private institutions, alongside a large-scale B.Tech programme spanning CSE and its many specialisations, ECE, Mechanical, Civil, and allied branches." },
    { tab: "info", heading: "Campus & Facilities", body: "The Vaddeswaram campus spans over 100 acres along the Krishna riverfront, with academic blocks, research centres, an incubation cell, sports facilities, and multiple hostel complexes. The university has also built out significant digital-learning and smart-classroom infrastructure as part of its NAAC A++ accreditation push." },
    { tab: "info", heading: "Why Choose KL University", body: "- Deemed-university flexibility in curriculum design and industry collaboration\n- Comparatively strong research output for a private university at this fee level\n- Multiple admission routes (KLUEEE, JEE Main, EAMCET) widen access\n- Riverside campus with modern infrastructure investment" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 600 | ₹5.5 L |\n| CSE — AI & ML | 4 years | 240 | ₹6.0 L |\n| Electronics & Communication | 4 years | 180 | ₹5.0 L |\n| Mechanical Engineering | 4 years | 120 | ₹4.5 L |\n\nFees are charged per year and vary by specialisation and campus (Vaddeswaram vs Hyderabad); confirm current-year figures on the official KLUEEE admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "KL University offers merit-based fee waivers tied to KLUEEE rank or qualifying exam score, along with sibling and alumni-family discounts. Fees are typically payable in two instalments per academic year." },
    { tab: "admissions", heading: "Admission Process", body: "KL University offers three main entry routes for B.Tech: KLUEEE (its own online entrance test), direct admission via JEE Main rank/score, or via AP/TS EAMCET rank. Applicants register online, appear for KLUEEE if choosing that route, and are allotted seats through KL's own counselling process based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by category)\n- Valid KLUEEE score, JEE Main rank, or EAMCET rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "KL University's placement cell runs large-scale IT-services recruitment drives alongside a smaller but growing set of product-company and analytics offers for top CSE/AI-ML performers. Overall placement percentage has stayed in the high 70s to low 80s in recent years, with CSE branches significantly outperforming core branches on both offer count and package." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Cognizant, Wipro, Capgemini, Tech Mahindra (bulk IT-services hiring)\n- Deloitte (analytics/consulting roles)\n- Regional Andhra Pradesh/Telangana IT and infrastructure firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the KLUEEE route, CSE admissions have typically required a rank within the top 5,000-10,000 among test takers in recent years; for the EAMCET route, CSE cutoff ranks have generally fallen in a similarly competitive band for AP/TS candidates. These are indicative — KL University publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- KLUEEE rank-based merit scholarships (up to 100% tuition waiver for top ranks)\n- Continuing merit scholarships tied to CGPA performance\n- Sports quota and cultural-achievement scholarships\n- Education loan facilitation cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "KL University (KLEF) is ranked #35 in NIRF 2024 Engineering and also features in NIRF's Research and Overall University categories — a notable achievement for a private deemed university, reflecting sustained investment in research output." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "The Vaddeswaram campus has separate hostel blocks for men and women with AC and non-AC room options and multiple mess plans. Campus life includes technical fests, a National Service Scheme wing, and riverside recreational spaces unique to the campus's Krishna riverbank setting." },
  ],
};

const kalasalingam: CollegeContentPack = {
  slug: "kalasalingam-academy-of-research-and-education",
  college: {
    estd: 1984,
    website: "https://www.klu.ac.in",
    feesNum: 450000,
    feesLabel: "₹4.5 L",
    packageLabel: "₹4.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Kalasalingam Academy of Research and Education — Courses, Fees, Placements 2026",
    metaDescription: "KARE Srivilliputhur NIRF #36 engineering: B.Tech courses, fees, admission process, placement details, hostel and scholarships.",
    about:
      "Kalasalingam Academy of Research and Education (KARE), founded in 1984 and granted deemed-university status in 2006, operates from a large rural campus at Krishnankoil near Srivilliputhur in Tamil Nadu's Virudhunagar district. Started by the Kalasalingam family's philanthropic trust, it has grown into a research-oriented deemed university with programmes across engineering, arts and science, and management.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "360", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "180", feesLabel: "₹4.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹3.8 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "90", feesLabel: "₹3.8 L total" },
  ],
  placement: { avgPackage: "₹4.5 LPA", highestPackage: "₹41 LPA (indicative)", placedPct: "75" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)", "Zoho", "Ashok Leyland"],
  highlights: [
    "Deemed university since 2006, rural campus at Krishnankoil, Tamil Nadu",
    "Strong regional placement network for Tamil Nadu's IT and manufacturing corridors",
    "Research-oriented deemed university with NIRF presence across multiple categories",
    "Admission via own entrance test or TNEA/JEE Main score",
  ],
  faqs: [
    { question: "Where is KARE located?", answer: "Kalasalingam Academy of Research and Education is located at Krishnankoil, near Srivilliputhur in Virudhunagar district, Tamil Nadu — a rural campus roughly 80 km from Madurai." },
    { question: "What is the admission process at KARE?", answer: "KARE admits students through its own entrance examination or directly via TNEA (Tamil Nadu Engineering Admissions) rank or JEE Main score, depending on the applicant's home state and preference." },
  ],
  sections: [
    { tab: "info", heading: "About KARE", body: "Kalasalingam Academy of Research and Education was founded in 1984 by the Kalasalingam family's educational trust and elevated to deemed-university status by the UGC in 2006. Its campus at Krishnankoil, near Srivilliputhur in Tamil Nadu, hosts engineering, arts and science, and management schools under one administration.\n\nKARE has positioned itself as a research-oriented deemed university, investing in sponsored research projects, patent filings, and doctoral programmes alongside its undergraduate engineering intake, which spans Computer Science, Electronics, Mechanical, Civil, and allied branches." },
    { tab: "info", heading: "Campus & Location", body: "The Krishnankoil campus spans over 400 acres in a rural setting roughly 80 km from Madurai, giving it room for extensive sports facilities, hostels, and a largely self-contained residential ecosystem including a campus hospital and shopping complex." },
    { tab: "info", heading: "Why Choose KARE", body: "- Deemed-university status with research-focused academic culture\n- Large, self-contained residential campus with extensive facilities\n- Strong regional recruiter network across Tamil Nadu's IT and auto-manufacturing corridors\n- Multiple admission routes (own entrance test, TNEA, JEE Main) for flexibility" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 360 | ₹4.5 L |\n| Electronics & Communication | 4 years | 180 | ₹4.0 L |\n| Mechanical Engineering | 4 years | 120 | ₹3.8 L |\n| Civil Engineering | 4 years | 90 | ₹3.8 L |\n\nFees vary modestly by branch and are charged per year; confirm the current year's exact figures with KARE admissions, as deemed universities revise fee slabs periodically." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "KARE offers merit scholarships based on entrance rank or Class 12 percentage, along with sibling-discount and alumni-family concessions. Fees are typically payable in two instalments per academic year via the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "KARE offers admission through its own entrance examination, or directly via TNEA rank (for Tamil Nadu domicile students) or JEE Main score (for out-of-state applicants). Applicants apply online, and seats are allotted via KARE's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score/rank via the chosen admission route\n- Documents: Class 10/12 mark sheets, entrance scorecard/TNEA rank card, community certificate (Tamil Nadu candidates), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "KARE's placement cell focuses heavily on Tamil Nadu's dense IT-services and automotive-manufacturing recruiter base, given its proximity to Madurai and the broader southern Tamil Nadu industrial corridor. CSE placement percentage has generally outperformed core branches, with overall placement rates in the mid-70s in recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Zoho (select CSE/product roles)\n- Ashok Leyland and regional auto-component manufacturers (Mechanical/core branches)\n- Amazon and other product companies for select high-performing CSE graduates" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For TNEA-route admissions, CSE cutoff ranks have typically required a strong Class 12 cutoff score (out of 200) in the high 150s-170s in recent years for open category; for the university's own entrance test, ranks within the top few thousand test-takers are typically needed for CSE. Confirm current-year cutoffs directly with KARE admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/Class 12-percentage merit scholarships up to full tuition waiver for top performers\n- Continuing merit scholarships tied to annual CGPA\n- State government scholarship schemes accessible to eligible Tamil Nadu students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Kalasalingam Academy of Research and Education is ranked #36 in NIRF 2024 Engineering and also features in NIRF's Research and Overall University categories, reflecting its research-oriented deemed-university positioning." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "The Krishnankoil campus provides separate hostel blocks for men and women, along with a campus hospital, shopping complex, and extensive sports facilities given the large rural footprint. Student life includes technical symposiums, cultural fests, and NSS/NCC activities typical of a self-contained residential campus." },
  ],
};

const kiit: CollegeContentPack = {
  slug: "kalinga-institute-of-industrial-technology",
  college: {
    estd: 1992,
    website: "https://kiit.ac.in",
    feesNum: 750000,
    feesLabel: "₹7.5 L",
    packageLabel: "₹7 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "KIIT University — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "KIIT Bhubaneswar NIRF #37 engineering: B.Tech courses, fees, KIITEE admission, placement stats, hostel and scholarship details.",
    about:
      "Kalinga Institute of Industrial Technology (KIIT), founded in 1992 by Dr. Achyuta Samanta and granted deemed-university status in 2004, has grown into one of eastern India's largest private deemed universities. Its sprawling Bhubaneswar campus, twinned with the KISS free residential school for tribal children under the same trust, runs a large School of Computer Engineering alongside core engineering branches, medicine, law, and management.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "1000", feesLabel: "₹7.5 L total" },
    { name: "B.Tech CSE (AI, ML, Data Science tracks)", duration: "4 years", seats: "400", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electronics & Telecommunication", duration: "4 years", seats: "240", feesLabel: "₹6.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "180", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹7 LPA", highestPackage: "₹51 LPA (indicative)", placedPct: "85" },
  recruiters: ["Amazon", "Microsoft", "Goldman Sachs", "TCS", "Infosys", "Deloitte", "Samsung R&D", "Tata Steel"],
  highlights: [
    "Deemed university since 2004, large integrated campus in Bhubaneswar",
    "One of the largest School of Computer Engineering intakes among Indian private universities",
    "Twinned with KISS, a free residential school for tribal children, under the same founding trust",
    "Admission via KIITEE (own entrance test) or JEE Main score",
  ],
  faqs: [
    { question: "What is KIITEE?", answer: "KIITEE (KIIT Entrance Examination) is KIIT's own computer-based entrance test for B.Tech admission; applicants can alternatively use their JEE Main score for direct admission to certain programmes." },
    { question: "Is KIIT good for placements?", answer: "KIIT posts strong placement numbers for a private deemed university, particularly in its School of Computer Engineering, with overall placement percentage regularly reported in the mid-to-high 80s across recent years." },
  ],
  sections: [
    { tab: "info", heading: "About KIIT", body: "Kalinga Institute of Industrial Technology was founded in 1992 by Dr. Achyuta Samanta and received deemed-to-be-university status in 2004. Its campus in Bhubaneswar, Odisha has grown into a large multi-disciplinary institution spanning engineering, medicine (KIIT Medical College), law, management, biotechnology, and more, with the School of Computer Engineering as its flagship and largest engineering programme by intake.\n\nKIIT is closely associated with the Kalinga Institute of Social Sciences (KISS), a free residential school and higher-education institution for tribal children run by the same founding trust — a distinctive social-impact dimension to the KIIT group's identity." },
    { tab: "info", heading: "Campus & Facilities", body: "The KIIT campus spans multiple contiguous blocks in Bhubaneswar, with dedicated schools of engineering, computer engineering, biotechnology, and more, plus an international student wing, sports infrastructure including cricket and football grounds, and a large auditorium complex used for its annual international education conferences." },
    { tab: "info", heading: "Why Choose KIIT", body: "- Large, well-resourced School of Computer Engineering with strong placement pipeline\n- Deemed-university flexibility and multi-disciplinary campus (engineering, medicine, law, management)\n- Significant international student population and global exchange tie-ups\n- Multiple admission routes (KIITEE, JEE Main) for flexibility" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 1000 | ₹7.5 L |\n| CSE — AI/ML/Data Science tracks | 4 years | 400 | ₹8.0 L |\n| Electronics & Telecommunication | 4 years | 240 | ₹6.5 L |\n| Mechanical Engineering | 4 years | 180 | ₹6.0 L |\n\nFees are charged per year and revised periodically; confirm the current year's exact figures on the official KIIT admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "KIIT offers merit-based fee waivers tied to KIITEE rank or JEE Main percentile at the time of admission, along with continuing merit scholarships. Fees are payable in semester instalments through the KIIT ERP portal." },
    { tab: "admissions", heading: "Admission Process", body: "KIIT offers two main routes for B.Tech admission: KIITEE, its own computer-based entrance test held across multiple cities, or direct admission based on JEE Main rank/percentile. Applicants register online, appear for KIITEE if choosing that route, and are allotted seats through KIIT's own counselling process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by category)\n- Valid KIITEE rank or JEE Main score/percentile as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "KIIT's Training and Placement Cell runs one of eastern India's largest private-university placement drives, with the School of Computer Engineering drawing the bulk of top-tier product-company and analytics offers. Overall placement percentage has stayed in the mid-to-high 80s across recent years per institute placement reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Samsung R&D (product/software)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- TCS, Infosys (bulk IT-services hiring)\n- Tata Steel and other core/manufacturing recruiters for Mechanical/Electronics branches" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the KIITEE route, CSE admissions have typically required a rank within the top few thousand test-takers in recent years; for the JEE Main route, CSE cutoff percentiles have generally fallen in the 90-96 range. These are indicative — KIIT publishes exact cutoffs after each admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- KIITEE/JEE Main rank-based merit scholarships up to full tuition waiver for top ranks\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Fee concessions linked to the KISS social-impact trust for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "KIIT is ranked #37 in NIRF 2024 Engineering and also ranks in NIRF's Overall University, Management, and Law categories, reflecting its scale as a multi-disciplinary deemed university." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "KIIT provides extensive on-campus hostel accommodation for both Indian and international students, with dedicated international student housing. Campus life includes the annual KIIT International Student Festival, large-scale technical and cultural fests, and a strong sports programme with dedicated stadium facilities." },
  ],
};

const sastra: CollegeContentPack = {
  slug: "shanmugha-arts-science-technology-and-research-academy",
  college: {
    estd: 1984,
    website: "https://www.sastra.edu",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹5.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "SASTRA Deemed University — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "SASTRA Thanjavur NIRF #38 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Shanmugha Arts, Science, Technology & Research Academy (SASTRA), founded in 1984 and granted deemed-university status in 2001, is located in Thanjavur, Tamil Nadu — a historic temple town rather than a metro hub. SASTRA has built a reputation for consistently strong NIRF rankings relative to its size, driven by disciplined academics, a research-oriented culture, and steady placement outcomes in its School of Computing.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "180", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹4.2 L total" },
    { name: "B.Tech Chemical Engineering", duration: "4 years", seats: "60", feesLabel: "₹4.2 L total" },
  ],
  placement: { avgPackage: "₹5.5 LPA", highestPackage: "₹44 LPA (indicative)", placedPct: "82" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Zoho", "Amazon (select roles)", "Cisco", "HCL", "Standard Chartered"],
  highlights: [
    "Deemed university since 2001, historic temple-town campus in Thanjavur, Tamil Nadu",
    "Consistently strong NIRF ranking relative to size — regularly among the top private deemed universities",
    "Solid placement record in its School of Computing with steady top recruiters",
    "Admission via SASTRA's own merit-cum-entrance process using Class 12 marks and an aptitude test",
  ],
  faqs: [
    { question: "How is SASTRA's admission process different?", answer: "SASTRA primarily uses a combination of Class 12 marks and its own online aptitude test (or JEE Main score, at the applicant's option) rather than relying on a single all-India entrance exam." },
    { question: "Is SASTRA a good deemed university?", answer: "SASTRA is widely regarded as one of the more academically disciplined private deemed universities in India, with a NIRF Engineering ranking that has stayed consistently within the top 40-45 for several years running." },
  ],
  sections: [
    { tab: "info", heading: "About SASTRA", body: "SASTRA was founded in 1984 and granted deemed-to-be-university status by the UGC in 2001. Its main campus is in Thanjavur, Tamil Nadu — historically significant as the seat of the Chola dynasty and home to the UNESCO World Heritage Brihadeeswarar Temple — giving SASTRA a distinctive setting compared to metro-based private universities.\n\nSASTRA runs its School of Computing as its flagship engineering unit alongside Electrical & Electronics, Mechanical, Chemical, and Civil Engineering departments, and has built a reputation for disciplined academics and a research culture that punches above its size in national rankings." },
    { tab: "info", heading: "Campus & Location", body: "The Thanjavur campus spans a large integrated site with academic blocks, a well-regarded central library, and campus housing for a significant share of both students and faculty. SASTRA also runs a secondary campus (Srinivasa Ramanujan Centre) in Kumbakonam focused on select programmes." },
    { tab: "info", heading: "Why Choose SASTRA", body: "- Consistently strong, stable NIRF Engineering ranking year over year\n- Disciplined academic culture with strong internal assessment rigour\n- Distinctive historic Thanjavur setting away from metro distractions\n- Flexible admission route accepting either JEE Main score or SASTRA's own aptitude test" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 300 | ₹5.0 L |\n| Electronics & Communication | 4 years | 180 | ₹4.5 L |\n| Mechanical Engineering | 4 years | 120 | ₹4.2 L |\n| Chemical Engineering | 4 years | 60 | ₹4.2 L |\n\nFees are charged per year and vary modestly by branch; confirm the current year's exact figures on the official SASTRA admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "SASTRA offers merit-based fee waivers tied to Class 12 percentage or JEE Main rank at the time of admission. Fees are payable in semester instalments through the university's online payment system." },
    { tab: "admissions", heading: "Admission Process", body: "SASTRA admits B.Tech students via a combination of Class 12 marks and either JEE Main score or SASTRA's own online aptitude test, whichever the applicant prefers to submit. Applicants apply online, and merit lists are released branch-wise based on the combined score across multiple counselling rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by branch/category)\n- JEE Main score or SASTRA aptitude test score, as per chosen route\n- Documents: Class 10/12 mark sheets, entrance/aptitude scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "SASTRA's placement cell runs steady campus drives concentrated in IT services and analytics, with its School of Computing posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s to mid-80s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, HCL (bulk IT-services hiring)\n- Zoho, Cisco (select product/engineering roles)\n- Standard Chartered (analytics/banking-tech roles)\n- Amazon for select high-performing CSE graduates" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a percentile in the 85-92 range in recent years; for SASTRA's own aptitude-test route, cutoffs are set relative to the applicant pool each year. These figures are indicative — confirm current-year cutoffs with SASTRA admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Merit scholarships based on Class 12%/JEE Main rank at admission, up to substantial tuition waivers for top performers\n- Continuing merit scholarships tied to semester GPA\n- Sports and cultural-achievement scholarships\n- Education loan assistance cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "SASTRA is ranked #38 in NIRF 2024 Engineering, continuing a multi-year streak of stable top-45 rankings that is unusually consistent among private deemed universities, and also features in NIRF's Overall University category." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SASTRA provides extensive on-campus hostel accommodation for both men and women, with most students living on campus given Thanjavur's distance from major metro hubs. Student life includes the annual technical fest and a strong emphasis on NSS and community outreach programmes tied to the local Thanjavur community." },
  ],
};

const vnitNagpur: CollegeContentPack = {
  slug: "visvesvaraya-national-institute-of-technology-nagpur",
  college: {
    estd: 1960,
    website: "https://www.vnit.ac.in",
    feesNum: 600000,
    feesLabel: "₹6.0 L",
    packageLabel: "₹12 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "VNIT Nagpur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "VNIT Nagpur NIRF #39 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "Visvesvaraya National Institute of Technology, Nagpur, established in 1960 as a Regional Engineering College and elevated to National Institute of Technology status in 2002 (renamed after engineer-statesman Sir M. Visvesvaraya), is among the oldest and most respected NITs. Its Nagpur campus in central India draws students nationwide through JoSAA, with particular strength in Metallurgical and Materials Engineering alongside core Computer Science and Electrical branches.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Metallurgical & Materials Engineering", duration: "4 years", seats: "60", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹12 LPA", highestPackage: "₹50 LPA (indicative)", placedPct: "88" },
  recruiters: ["Amazon", "Microsoft", "L&T", "Tata Steel", "Deloitte", "Bajaj Auto", "ZS Associates", "Qualcomm"],
  highlights: [
    "One of India's oldest NITs, founded 1960, NIT status since 2002",
    "Particular strength in Metallurgical and Materials Engineering",
    "Consistently high placement percentage among NITs",
    "JEE Main is the sole route to admission via JoSAA",
  ],
  faqs: [
    { question: "Is VNIT Nagpur a good NIT?", answer: "VNIT Nagpur is consistently ranked among the top 5 NITs nationally, with strong core-branch reputation (especially Metallurgical Engineering) and a solid placement record across CSE, Electronics, and Mechanical branches." },
    { question: "What is VNIT's JEE Main cutoff?", answer: "CSE closing ranks at VNIT Nagpur have typically fallen in the 3,000-5,000 band (General, home state neutral) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About VNIT Nagpur", body: "Visvesvaraya National Institute of Technology, Nagpur was established in 1960 as a Regional Engineering College and was granted National Institute of Technology (Institute of National Importance) status in 2002, taking its name from the pioneering Indian engineer and statesman Sir M. Visvesvaraya. It is one of the oldest and most reputed NITs, located in Nagpur, Maharashtra — a centrally located city with strong rail and air connectivity to the rest of India.\n\nVNIT runs undergraduate programmes across Computer Science, Electronics & Communication, Electrical, Mechanical, Civil, and a particularly well-regarded Metallurgical & Materials Engineering department, alongside active postgraduate and doctoral research programmes." },
    { tab: "info", heading: "Campus & Location", body: "VNIT's campus in South Ambazari Road, Nagpur spans over 200 acres with academic blocks, a central library, workshops, and hostels. Nagpur's central location in India — often called the country's geographic centre — makes it accessible from most major cities." },
    { tab: "info", heading: "Why Choose VNIT Nagpur", body: "- Among the top 5 NITs nationally with strong faculty and infrastructure\n- Distinguished Metallurgical & Materials Engineering programme, uncommon among NITs\n- High and consistent placement percentage across branches\n- Central Indian location with strong national connectivity" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹6.0 L |\n| Electronics & Communication | 4 years | 90 | ₹6.0 L |\n| Metallurgical & Materials Engineering | 4 years | 60 | ₹6.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹6.0 L |\n\nFees follow the standard NIT fee structure (~₹1.5 L/year tuition); SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, consistent with the common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to VNIT Nagpur's B.Tech programmes is through JEE Main rank via the JoSAA centralised counselling process, alongside the home-state/other-state quota system common to all NITs. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds based on rank, category, and quota." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile in respective board) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "VNIT Nagpur posts one of the highest placement percentages among NITs, with CSE and Electronics graduates drawing strong software and core-tech offers, and Metallurgical/Mechanical graduates recruited heavily by manufacturing and materials companies. Overall placement percentage has stayed in the high 80s in recent years per institute placement reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Qualcomm (software/semiconductor)\n- L&T, Tata Steel, Bajaj Auto (core/manufacturing)\n- Deloitte, ZS Associates (consulting/analytics)\n- A broad base of PSU and core-sector recruiters for Metallurgical and Civil branches" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Home State) |\n|---|---|\n| Computer Science & Engineering | 3,000 – 5,000 |\n| Electronics & Communication | 6,000 – 9,000 |\n| Mechanical Engineering | 10,000 – 14,000 |\n| Metallurgical & Materials Engineering | 15,000 – 20,000 |\n\nRanges are indicative and vary meaningfully between home-state and other-state quotas; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- State and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "VNIT Nagpur is ranked #39 in NIRF 2024 Engineering, consistently placing among the top-tier NITs alongside NIT Trichy, NIT Surathkal, and NIT Warangal." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "VNIT provides on-campus hostel accommodation for the large majority of its students, with separate blocks for men and women and mess facilities on a rotating menu. Student life includes the technical fest Vidyut and cultural fest Rammersham, plus active sports and departmental technical clubs." },
  ],
};

const nitSilchar: CollegeContentPack = {
  slug: "national-institute-of-technology-silchar",
  college: {
    estd: 1967,
    website: "https://www.nits.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹9 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Silchar — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Silchar NIRF #40 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Silchar, established in 1967 as a Regional Engineering College and elevated to NIT status in 2002, is the premier technical institute of India's Northeast region. Located in Silchar, Assam, it draws students from across the Northeast and the rest of India through JoSAA, with a curriculum spanning Computer Science, Electronics, Mechanical, Civil, and Chemical Engineering.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "110", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹9 LPA", highestPackage: "₹42 LPA (indicative)", placedPct: "80" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "ONGC", "L&T", "Cognizant", "HCL"],
  highlights: [
    "Premier technical institute of India's Northeast region, NIT status since 2002",
    "Regional quota and outreach programmes support students from the Northeast",
    "Steady placement outcomes in CSE and Electronics branches",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Where is NIT Silchar located?", answer: "NIT Silchar is located in Silchar, in the Barak Valley region of southern Assam — the primary technical institute serving India's Northeast states." },
    { question: "What is NIT Silchar's placement record?", answer: "NIT Silchar reports overall placement percentages generally in the high 70s to low 80s in recent years, with CSE and Electronics graduates posting the strongest package outcomes." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Silchar", body: "National Institute of Technology, Silchar traces its origins to 1967 as a Regional Engineering College and was granted National Institute of Technology (Institute of National Importance) status in 2002. Located in Silchar in Assam's Barak Valley, it serves as the flagship technical institute for India's Northeast region, drawing students from Assam, Tripura, Manipur, Mizoram, and neighbouring states alongside applicants from across India.\n\nThe institute runs undergraduate programmes in Computer Science, Electronics & Communication, Electrical, Mechanical, Civil, and Chemical Engineering, with a growing research profile in areas like signal processing and structural engineering." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Silchar campus spans over 300 acres near Silchar town in southern Assam, with academic blocks, hostels, a central library, and sports facilities. Its Northeast location gives it a distinct regional student mix and connects it closely to the region's engineering talent pipeline." },
    { tab: "info", heading: "Why Choose NIT Silchar", body: "- Premier engineering institute for India's Northeast, with strong regional recognition\n- NIT brand and infrastructure at accessible JoSAA cutoffs relative to older NITs\n- Growing research profile alongside solid undergraduate placement outcomes\n- Diverse, pan-India and pan-Northeast student community" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 110 | ₹5.5 L |\n| Electronics & Communication | 4 years | 90 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n| Civil Engineering | 4 years | 70 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Silchar's B.Tech programmes is through JEE Main rank via the JoSAA centralised counselling process, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Silchar's placement cell runs campus drives concentrated in IT services with a growing share of product-company and PSU offers. CSE and Electronics graduates post the strongest outcomes; overall placement percentage has generally stayed in the high 70s to low 80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- Amazon for select CSE roles\n- ONGC, L&T (core/PSU recruitment)\n- Regional infrastructure and manufacturing firms for Civil/Mechanical branches" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 18,000 – 24,000 |\n| Electronics & Communication | 28,000 – 35,000 |\n| Mechanical Engineering | 40,000 – 50,000 |\n| Civil Engineering | 50,000 – 60,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Northeast-region specific government scholarship schemes for eligible students\n- Institute merit scholarships for top academic performers" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Silchar is ranked #40 in NIRF 2024 Engineering, holding steady as the top-ranked technical institute in India's Northeast region." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Silchar provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes the annual techno-cultural fest Amalgamation and Advitiya, plus active sports and regional cultural clubs reflecting the Northeast's diverse student community." },
  ],
};

const ictMumbai: CollegeContentPack = {
  slug: "institute-of-chemical-technology",
  college: {
    estd: 1933,
    website: "https://www.ictmumbai.edu.in",
    feesNum: 400000,
    feesLabel: "₹4.0 L",
    packageLabel: "₹14 LPA",
    affiliation: "Deemed University (Elite, State-funded)",
    approvedBy: "UGC, AICTE",
    metaTitle: "ICT Mumbai — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Institute of Chemical Technology Mumbai NIRF #41 engineering: B.Tech Chemical/allied courses, fees, admission, placement, hostel details.",
    about:
      "Institute of Chemical Technology (ICT), Mumbai, founded in 1933 as the Department of Chemical Technology at the University of Bombay and granted deemed-university status in 2008, is India's foremost institute for chemical engineering and technology. Located in Matunga, Mumbai, ICT is state-funded (Maharashtra government) yet holds elite deemed-university status, keeping fees low while delivering placement outcomes on par with top-tier engineering institutes, particularly in chemical, pharmaceutical, and petroleum-linked industries.",
  },
  courses: [
    { name: "B.Tech Chemical Engineering", duration: "4 years", seats: "120", feesLabel: "₹4.0 L total" },
    { name: "B.Tech Pharmaceutical Sciences & Technology", duration: "4 years", seats: "60", feesLabel: "₹4.0 L total" },
    { name: "B.Tech Food Engineering & Technology", duration: "4 years", seats: "40", feesLabel: "₹4.0 L total" },
    { name: "B.Tech Polymer & Surface Engineering", duration: "4 years", seats: "30", feesLabel: "₹4.0 L total" },
  ],
  placement: { avgPackage: "₹14 LPA", highestPackage: "₹65 LPA (indicative)", placedPct: "90" },
  recruiters: ["Reliance Industries", "Hindustan Unilever", "P&G", "ExxonMobil", "Cipla", "Sun Pharma", "Asian Paints", "ITC"],
  highlights: [
    "India's foremost chemical engineering institute, founded 1933, deemed university since 2008",
    "State-funded (Maharashtra) fee structure combined with elite placement outcomes",
    "Extremely strong industry ties across chemicals, pharma, FMCG, and petroleum sectors",
    "Admission via MHT-CET or JEE Main score, plus a separate all-India quota",
  ],
  faqs: [
    { question: "Is ICT Mumbai good for chemical engineering?", answer: "ICT Mumbai is widely regarded as India's top institute for chemical engineering and allied fields, with placement outcomes that rival top IITs specifically for chemical, pharma, and process-industry roles." },
    { question: "What is the admission process for ICT Mumbai?", answer: "ICT admits students through MHT-CET (Maharashtra quota) and JEE Main (All-India quota), with separate seat allocation for each category — check ICT's official admission notification for the current year's exact split." },
  ],
  sections: [
    { tab: "info", heading: "About ICT Mumbai", body: "Institute of Chemical Technology traces its origins to 1933, when it was established as the Department of Chemical Technology (UDCT) under the University of Bombay. It became an autonomous, state-funded deemed university in 2008, and has remained India's most respected institute specifically for chemical engineering and allied disciplines — Pharmaceutical Sciences, Food Engineering, Polymer Engineering, Oils & Fats, and more.\n\nDespite its deemed-university status, ICT is funded by the Government of Maharashtra, which keeps its fees exceptionally low relative to the placement outcomes it delivers — a combination that makes it one of the best value-for-money technical institutes in India." },
    { tab: "info", heading: "Campus & Location", body: "ICT's campus is located in Matunga, central Mumbai, in a compact urban setting rather than a sprawling suburban campus. Its city-centre location gives students easy access to Mumbai's chemical, pharmaceutical, and financial industry hubs, which feeds directly into its strong internship and placement network." },
    { tab: "info", heading: "Why Choose ICT Mumbai", body: "- India's top-ranked institute specifically for chemical engineering and allied technology fields\n- State-subsidised fees combined with placement outcomes on par with top-tier IITs for its core disciplines\n- Deep industry ties across FMCG, pharma, petrochemical, and specialty chemical sectors\n- Central Mumbai location with strong access to the city's industrial and corporate base" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Chemical Engineering | 4 years | 120 | ₹4.0 L |\n| Pharmaceutical Sciences & Technology | 4 years | 60 | ₹4.0 L |\n| Food Engineering & Technology | 4 years | 40 | ₹4.0 L |\n| Polymer & Surface Engineering | 4 years | 30 | ₹4.0 L |\n\nAs a state-funded deemed university, ICT's fees remain low relative to comparable private institutes; confirm the current year's exact figures on the official ICT admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "Fees are paid semester-wise via the ICT online portal. Additional concessions apply for Maharashtra-domicile SC/ST/OBC/EWS students under state government fee-reimbursement schemes." },
    { tab: "admissions", heading: "Admission Process", body: "ICT Mumbai admits B.Tech students through two parallel routes: MHT-CET score for Maharashtra-quota seats, and JEE Main score for All-India-quota seats. Applicants apply through the relevant counselling process (state CAP rounds for MHT-CET, or ICT's own All-India counselling for the JEE Main quota) and are allotted seats based on rank and category." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category/quota)\n- Valid MHT-CET or JEE Main score/rank as per chosen quota\n- Documents: Class 10/12 mark sheets, entrance scorecard, domicile certificate (for MHT-CET quota), category certificate, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "ICT Mumbai posts placement outcomes that are exceptionally strong for its niche — chemical, pharmaceutical, FMCG, and process industries recruit heavily and pay competitively for ICT graduates, with placement percentage regularly reported above 85-90% and average packages notably high for a chemical-engineering-focused institute." },
    { tab: "placements", heading: "Top Recruiters", body: "- Reliance Industries, ExxonMobil (petrochemical/energy)\n- Hindustan Unilever, P&G, ITC (FMCG)\n- Cipla, Sun Pharma (pharmaceutical)\n- Asian Paints and other specialty-chemical majors" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the MHT-CET route, Chemical Engineering admissions have typically required a percentile above 99 in recent years given the extremely limited seat count; for the JEE Main All-India quota, similarly high percentiles (95+) are generally needed. These figures are indicative — ICT publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Maharashtra state government fee-reimbursement schemes for SC/ST/OBC/EWS domicile students\n- Merit scholarships for top rank-holders in each department\n- Institute-level need-based financial assistance\n- Corporate-sponsored scholarships tied to ICT's strong industry partnerships" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "ICT Mumbai is ranked #41 in NIRF 2024 Engineering, and its Chemical Engineering programme specifically is widely regarded as the best in India, a reputation that predates and outlasts its NIRF ranking position." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "ICT provides on-campus hostel accommodation, though seats are limited given the compact Matunga campus, and many students rely on Mumbai's broader housing market as well. Student life includes the annual technical fest and strong industry-interaction events given ICT's close ties to Mumbai's chemical and pharma corporate base." },
  ],
};

export const engBatch3: CollegeContentPack[] = [
  iitMandi,
  chandigarhUniversity,
  amu,
  iitPatna,
  klUniversity,
  kalasalingam,
  kiit,
  sastra,
  vnitNagpur,
  nitSilchar,
  ictMumbai,
];
