import type { CollegeContentPack } from "./types";

// NIRF Engineering 2024 #89-100 — hand-authored, matches iit-madras.ts / eng-batch2-7.ts depth.
// Completes the top-100 NIRF Engineering enriched-content target.

const ggsipu: CollegeContentPack = {
  slug: "guru-gobind-singh-indraprastha-university",
  college: {
    estd: 1998,
    website: "https://ipu.ac.in",
    feesNum: 450000,
    feesLabel: "₹4.5 L",
    packageLabel: "₹6.5 LPA",
    affiliation: "State University, Delhi",
    approvedBy: "UGC, AICTE",
    metaTitle: "GGSIPU Delhi — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Guru Gobind Singh Indraprastha University NIRF #89: B.Tech USICT and affiliated college courses, fees, admission, placement details.",
    about:
      "Guru Gobind Singh Indraprastha University (GGSIPU), established in 1998 by the Delhi government, is a state university combining its own constituent schools — most notably the University School of Information and Communication Technology (USICT) — with a large network of affiliated private engineering colleges across Delhi-NCR, giving it a structure that blends single-campus and affiliating-university models.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering (USICT)", duration: "4 years", seats: "120", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Information Technology (USICT)", duration: "4 years", seats: "60", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Computer Science & Engineering (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1.5-3.5 L/year" },
    { name: "B.Tech Electronics & Communication (affiliated colleges)", duration: "4 years", seats: "Varies", feesLabel: "Varies by college, ~₹1.5-3 L/year" },
  ],
  placement: { avgPackage: "₹6.5 LPA", highestPackage: "₹42 LPA (indicative, USICT)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Deloitte", "Wipro", "Cognizant", "HCL"],
  highlights: [
    "Delhi state university, established 1998, combining constituent schools with affiliated colleges",
    "USICT (University School of Information and Communication Technology) is its flagship engineering school",
    "Delhi-NCR location gives strong recruiter access",
    "Admission via CUET/JEE Main-linked entrance process",
  ],
  faqs: [
    { question: "What is USICT?", answer: "USICT (University School of Information and Communication Technology) is GGSIPU's own constituent engineering school, distinct from its network of affiliated private colleges, and generally posts the university's strongest placement outcomes." },
    { question: "Is GGSIPU a single college or a university system?", answer: "GGSIPU is a hybrid — it runs its own constituent schools like USICT directly, while also affiliating a network of private engineering colleges across Delhi-NCR, so admission process and outcomes vary depending on which part of the university a student attends." },
  ],
  sections: [
    { tab: "info", heading: "About GGSIPU", body: "Guru Gobind Singh Indraprastha University was established in 1998 by the Government of Delhi as a state university. It runs a hybrid structure: its own constituent schools, most notably the University School of Information and Communication Technology (USICT), alongside a large network of affiliated private engineering colleges across Delhi-NCR.\n\nUSICT, GGSIPU's flagship engineering school, offers Computer Science and Information Technology programmes and generally posts the university's strongest academic and placement outcomes, distinct from the more variable results across its affiliated-college network." },
    { tab: "info", heading: "University Structure", body: "Prospective students should distinguish between USICT (GGSIPU's own constituent school, generally the strongest option) and its many affiliated private colleges, which vary significantly in quality, placement record, and fee structure. Researching the specific institution is essential before applying." },
    { tab: "info", heading: "Why Choose GGSIPU / USICT", body: "- USICT offers strong Computer Science and IT outcomes within a Delhi state-university structure\n- Delhi-NCR location gives direct access to a dense recruiter ecosystem\n- Comparatively lower fees than private universities, particularly at USICT\n- Wide choice of affiliated colleges for students seeking alternatives to USICT" },
    { tab: "courses-fees", heading: "Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (USICT) | 4 years | 120 | ₹4.5 L |\n| Information Technology (USICT) | 4 years | 60 | ₹4.5 L |\n| CSE (affiliated colleges) | 4 years | Varies | ₹1.5 L – ₹3.5 L per year |\n| Electronics & Communication (affiliated colleges) | 4 years | Varies | ₹1.5 L – ₹3 L per year |\n\nUSICT fees follow Delhi state university norms; affiliated-college fees vary by institution — confirm the specific college's fee structure." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "Fee concessions apply for SC/ST/OBC/EWS Delhi-domicile students at USICT per Delhi government policy. Affiliated colleges set their own fee-concession policies separately." },
    { tab: "admissions", heading: "Admission Process", body: "Admission to USICT and GGSIPU-affiliated colleges is based on a common entrance test (historically IPU CET, increasingly aligned with JEE Main/CUET-based processes as policy evolves), with a significant share of seats reserved for Delhi-domicile candidates. Applicants should check the current year's exact admission process on the official GGSIPU portal." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per GGSIPU norms\n- Valid entrance score/rank as per the current year's admission process\n- Delhi domicile certificate (for home-quota seats)\n- Documents: Class 10/12 mark sheets, entrance scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "USICT posts the strongest placement outcomes within the GGSIPU system, drawing software and analytics recruiters given its Delhi-NCR location; affiliated colleges see more variable outcomes depending on the specific institution. Overall CSE placement percentage at USICT has generally stayed in the high 70s to low 80s across recent years." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles, primarily USICT)\n- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring across the network)\n- Deloitte and other analytics/consulting recruiters\n- A wide base of Delhi-NCR corporate recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "USICT's CSE admissions have historically been highly competitive given the limited seat count and strong Delhi-NCR demand; affiliated-college cutoffs vary widely by institution. Confirm current-year cutoffs on the official GGSIPU admissions portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Fee concessions for SC/ST/OBC/EWS Delhi-domicile students at USICT per government policy\n- Merit-cum-Means scholarships for eligible students\n- Institute merit scholarships for top academic performers\n- Central and Delhi government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "GGSIPU is ranked #89 in NIRF 2024 Engineering as an aggregate university-level ranking, reflecting the combined output of USICT and its affiliated-college network." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "USICT offers limited on-campus hostel accommodation given its Delhi location, with many students commuting; hostel availability at affiliated colleges varies by institution. Student life includes technical and cultural fests typical of a Delhi-NCR university system." },
  ],
};

const auCollegeEngg: CollegeContentPack = {
  slug: "au-college-of-engineering",
  college: {
    estd: 1946,
    website: "https://aucoe.andhrauniversity.edu.in",
    feesNum: 200000,
    feesLabel: "₹2.0 L",
    packageLabel: "₹6 LPA",
    affiliation: "Constituent College, Andhra University",
    approvedBy: "UGC, AICTE",
    metaTitle: "AU College of Engineering Visakhapatnam — Courses, Fees, Placements 2026",
    metaDescription: "Andhra University College of Engineering NIRF #90: B.Tech courses, low fees, EAMCET admission, placement stats, hostel details.",
    about:
      "Andhra University College of Engineering (AU College of Engineering), founded in 1946, is one of the oldest engineering colleges in South India, functioning as a constituent college of Andhra University in Visakhapatnam. Its government-subsidised fee structure and long institutional history give it a distinctive value proposition among NIRF-ranked engineering institutes.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹2.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "100", feesLabel: "₹2.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹2.0 L total" },
    { name: "B.Tech Metallurgical Engineering", duration: "4 years", seats: "60", feesLabel: "₹2.0 L total" },
  ],
  placement: { avgPackage: "₹6 LPA", highestPackage: "₹32 LPA (indicative)", placedPct: "74" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Visakhapatnam Steel Plant", "L&T", "Cognizant"],
  highlights: [
    "Founded 1946 — one of the oldest engineering colleges in South India",
    "Government-subsidised fees, among the lowest of any NIRF top-100 engineering institute",
    "Constituent college of Andhra University in Visakhapatnam",
    "Admission via AP EAMCET score",
  ],
  faqs: [
    { question: "How old is AU College of Engineering?", answer: "AU College of Engineering was founded in 1946, making it one of the oldest engineering colleges in South India, predating India's independence." },
    { question: "How is admission to AU College of Engineering done?", answer: "Admission is primarily through AP EAMCET (Andhra Pradesh Engineering, Agriculture and Medical Common Entrance Test) rank, based on Andhra Pradesh's state counselling process." },
  ],
  sections: [
    { tab: "info", heading: "About AU College of Engineering", body: "Andhra University College of Engineering was founded in 1946, making it one of the oldest engineering colleges in South India, predating India's independence by a year. It functions as a constituent college of Andhra University, located in the port city of Visakhapatnam, Andhra Pradesh, running undergraduate programmes across Computer Science, Electronics, Mechanical, Civil, and a distinguished Metallurgical Engineering department.\n\nAs a government-subsidised constituent college, AU College of Engineering combines a rare depth of institutional history with fees far lower than most private and even deemed-university alternatives." },
    { tab: "info", heading: "Campus & Location", body: "The AU College of Engineering campus is located within the broader Andhra University campus in Visakhapatnam, a major port city and industrial hub on India's east coast, giving students access to the region's steel, shipping, and petrochemical industries." },
    { tab: "info", heading: "Why Choose AU College of Engineering", body: "- Among the oldest engineering colleges in South India, with nearly 80 years of history\n- Government-subsidised fees, among the lowest of any NIRF top-100 engineering institute\n- Distinguished Metallurgical Engineering programme tied to Visakhapatnam's industrial base\n- Constituent-college access to Andhra University's broader academic ecosystem" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹2.0 L |\n| Electronics & Communication | 4 years | 100 | ₹2.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹2.0 L |\n| Metallurgical Engineering | 4 years | 60 | ₹2.0 L |\n\nAs a government-subsidised constituent college, fees remain among the lowest of any NIRF-ranked engineering institute; confirm current-year figures on the official Andhra University admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "Additional fee concessions and reimbursements apply for Andhra Pradesh-domicile SC/ST/OBC/EWS students under state government schemes. Fees are payable per semester via the university's designated channels." },
    { tab: "admissions", heading: "Admission Process", body: "Admission to AU College of Engineering is primarily through AP EAMCET rank, Andhra Pradesh's state-level engineering entrance exam, with seats allotted through the state's centralised counselling process based on rank and category." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per EAMCET norms\n- Valid AP EAMCET rank for the admission year\n- Documents: Class 10/12 mark sheets, EAMCET rank card, domicile/category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "AU College of Engineering's placement cell draws IT-services and core-industrial recruiters given Visakhapatnam's steel and port-industry base. CSE graduates post the strongest outcomes; overall placement percentage has generally stayed in the low-to-mid 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Visakhapatnam Steel Plant, L&T (core/metallurgical — reflecting the Metallurgical Engineering programme's regional ties)\n- Regional Andhra Pradesh industrial and port-sector firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "AP EAMCET cutoff ranks for CSE at AU College of Engineering have typically required a rank within the top few thousand in recent years for open category. These figures shift year to year — confirm current-year cutoffs on the official EAMCET counselling portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Andhra Pradesh state government fee-reimbursement schemes for SC/ST/OBC/EWS-eligible students\n- Merit scholarships for top academic performers\n- Central government scholarship schemes for eligible students\n- Need-based financial assistance through university-level aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "AU College of Engineering is ranked #90 in NIRF 2024 Engineering, and Andhra University as a whole also ranks in NIRF's Overall University category, reflecting the institution's long combined academic history." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "AU College of Engineering provides on-campus hostel accommodation for men and women within the broader Andhra University campus. Student life includes technical and cultural fests, plus access to the university's wider sports and academic facilities." },
  ],
};

const vignan: CollegeContentPack = {
  slug: "vignan-s-foundation-for-science-technology-and-research",
  college: {
    estd: 1997,
    website: "https://www.vignan.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹4.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Vignan's Foundation for Science, Technology and Research — Courses, Fees, Placements 2026",
    metaDescription: "Vignan University Guntur NIRF #91 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Vignan's Foundation for Science, Technology and Research (Vignan University), founded in 1997 and granted deemed-university status in 2008, operates from a campus near Guntur, Andhra Pradesh, running a wide-ranging engineering programme spread with a growing research-publication focus that has helped drive its NIRF presence.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹5.0 L total" },
    { name: "B.Tech CSE (AI & Data Science)", duration: "4 years", seats: "120", feesLabel: "₹5.2 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "120", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹4.2 L total" },
  ],
  placement: { avgPackage: "₹4.5 LPA", highestPackage: "₹36 LPA (indicative)", placedPct: "76" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)"],
  highlights: [
    "Deemed university since 2008, founded 1997 near Guntur, Andhra Pradesh",
    "Growing research-publication focus contributing to its NIRF presence",
    "Wide engineering programme spread including AI & Data Science",
    "Admission via own entrance test or AP EAMCET/JEE Main score",
  ],
  faqs: [
    { question: "How is admission to Vignan University done?", answer: "Vignan admits students through its own entrance examination (VSAT), or directly via AP EAMCET rank or JEE Main score, depending on the applicant's home state and preference." },
    { question: "Is Vignan good for research?", answer: "Vignan has invested in building research-publication output as part of its NIRF ranking strategy, a common approach among newer deemed universities seeking to establish academic credibility." },
  ],
  sections: [
    { tab: "info", heading: "About Vignan University", body: "Vignan's Foundation for Science, Technology and Research was founded in 1997 and granted deemed-to-be-university status in 2008, operating from a campus near Guntur, Andhra Pradesh. It runs a wide-ranging engineering programme spread including Computer Science, Electronics, Mechanical, and Civil branches, alongside programmes in pharmacy, management, and agriculture.\n\nVignan has invested in growing its research-publication output as a deliberate ranking strategy, a common approach among newer deemed universities in South India seeking to establish academic credibility alongside placement outcomes." },
    { tab: "info", heading: "Campus & Facilities", body: "The Vignan campus near Guntur spans a substantial site with academic blocks, computer labs, hostels, and sports facilities built out since the university's 1997 founding." },
    { tab: "info", heading: "Why Choose Vignan University", body: "- Growing research-publication output contributing to a strengthening NIRF presence\n- Wide engineering programme spread including AI & Data Science specialisation\n- Deemed-university flexibility in curriculum design\n- Multiple admission routes (VSAT, AP EAMCET, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 300 | ₹5.0 L |\n| CSE — AI & Data Science | 4 years | 120 | ₹5.2 L |\n| Electronics & Communication | 4 years | 120 | ₹4.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹4.2 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Vignan admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Vignan offers merit-based fee waivers tied to VSAT/EAMCET/JEE Main rank at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Vignan admits B.Tech students through VSAT (Vignan's own entrance test), or directly via AP EAMCET rank or JEE Main score. Applicants apply online, and seats are allotted through Vignan's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid VSAT score, EAMCET rank, or JEE Main score as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Vignan's placement cell runs drives concentrated in IT services, with CSE and its AI & Data Science specialisation posting the strongest outcomes. Overall placement percentage has generally stayed in the mid-70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Amazon for select high-performing CSE graduates\n- Regional Andhra Pradesh IT and manufacturing firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the EAMCET route, CSE cutoff ranks have typically fallen within a moderately competitive band for open category in recent years; for VSAT, cutoffs are set relative to the year's applicant pool. Confirm current-year cutoffs directly with Vignan admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Andhra Pradesh state government scholarship schemes for eligible domicile students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Vignan's Foundation for Science, Technology and Research is ranked #91 in NIRF 2024 Engineering and also features in NIRF's Overall University category." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Vignan provides on-campus hostel accommodation for men and women across its Guntur-area campus. Student life includes technical and cultural fests, plus active sports facilities." },
  ],
};

const shoolini: CollegeContentPack = {
  slug: "shoolini-university-of-biotechnology-and-management-sciences",
  college: {
    estd: 2009,
    website: "https://www.shooliniuniversity.com",
    feesNum: 650000,
    feesLabel: "₹6.5 L",
    packageLabel: "₹5 LPA",
    affiliation: "State Private University, Himachal Pradesh",
    approvedBy: "UGC, AICTE",
    metaTitle: "Shoolini University — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Shoolini University Solan NIRF #92 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Shoolini University of Biotechnology and Management Sciences, founded in 2009 near Solan, Himachal Pradesh, has built one of India's fastest-rising research-publication profiles among private universities within a relatively short institutional history, driven by a deliberate strategy of hiring research-active faculty and prioritising high-impact publications, which now extends to its engineering programmes.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "180", feesLabel: "₹6.5 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "90", feesLabel: "₹6.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "60", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Biotechnology Engineering", duration: "4 years", seats: "60", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹5 LPA", highestPackage: "₹34 LPA (indicative)", placedPct: "74" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)"],
  highlights: [
    "Founded 2009 near Solan, Himachal Pradesh — one of India's fastest-rising research-output universities",
    "Deliberate research-publication-first strategy now extending to engineering",
    "Distinctive Biotechnology Engineering programme reflecting the university's biotech-research roots",
    "Admission via own entrance test or JEE Main score",
  ],
  faqs: [
    { question: "Why does Shoolini rank well despite being young?", answer: "Shoolini has pursued a deliberate strategy of hiring research-active faculty and prioritising high-impact academic publications since its 2009 founding, which has driven unusually fast NIRF ranking growth for a private university of its age, including within its engineering programmes." },
    { question: "How is admission to Shoolini done?", answer: "Shoolini admits B.Tech students through its own entrance test or directly via JEE Main score, with seats allotted through the university's own counselling process." },
  ],
  sections: [
    { tab: "info", heading: "About Shoolini University", body: "Shoolini University of Biotechnology and Management Sciences was founded in 2009 near Solan, Himachal Pradesh. The university has built its identity and rapid ranking growth around a deliberate research-publication-first strategy — hiring research-active faculty and prioritising high-impact academic output — which has extended from its founding biotechnology focus into its engineering programmes.\n\nShoolini's B.Tech offerings include Computer Science, Electronics, and a distinctive Biotechnology Engineering programme that draws on the university's original biotech-research strength." },
    { tab: "info", heading: "Campus & Location", body: "The Shoolini campus near Solan, Himachal Pradesh, sits in a cooler hill-state setting, with academic blocks, research labs, hostels, and sports facilities built out since the university's 2009 founding." },
    { tab: "info", heading: "Why Choose Shoolini University", body: "- Unusually fast research-output growth for a private university of its age\n- Distinctive Biotechnology Engineering programme drawing on the university's biotech-research roots\n- Himachal Pradesh hill-state campus setting\n- Multiple admission routes (own entrance test, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 180 | ₹6.5 L |\n| CSE — AI & ML | 4 years | 90 | ₹6.8 L |\n| Electronics & Communication | 4 years | 60 | ₹6.0 L |\n| Biotechnology Engineering | 4 years | 60 | ₹6.0 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Shoolini admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Shoolini offers merit-based fee waivers tied to entrance rank or JEE Main percentile at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Shoolini admits B.Tech students through its own entrance test or directly via JEE Main score. Applicants apply online, and seats are allotted through the university's own counselling process based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Shoolini's placement cell runs drives concentrated in IT services, with CSE and AI & ML posting the strongest outcomes. Overall placement percentage has generally stayed in the mid-70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Amazon for select high-performing CSE graduates\n- Regional biotech and pharma firms (Biotechnology Engineering graduates)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a moderate percentile in recent years; for the own entrance test, cutoffs are set relative to the year's applicant pool. Confirm current-year cutoffs directly with Shoolini admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/JEE Main-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Research-linked scholarships given the university's biotech-research focus\n- Himachal Pradesh state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Shoolini University is ranked #92 in NIRF 2024 Engineering and holds an unusually strong NIRF Research ranking for a private university of its age, reflecting its deliberate publication-focused strategy." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Shoolini provides on-campus hostel accommodation for men and women across its Solan-area campus. Student life includes technical and cultural fests, plus access to the region's hill-state outdoor and recreational activities." },
  ],
};

const christUniversity: CollegeContentPack = {
  slug: "christ-university",
  college: {
    estd: 1969,
    website: "https://christuniversity.in",
    feesNum: 800000,
    feesLabel: "₹8.0 L",
    packageLabel: "₹6 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Christ University Bengaluru — Engineering Courses, Fees, Placements 2026",
    metaDescription: "Christ University NIRF #93 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Christ University, founded in 1969 in Bengaluru and granted deemed-university status in 2008, is primarily known for its strength in commerce, management, and liberal arts, with a smaller, more recently developed engineering school that benefits from the university's broader academic reputation and Bengaluru's technology-industry base.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "180", feesLabel: "₹8.0 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "90", feesLabel: "₹8.3 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "60", feesLabel: "₹7.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹7.0 L total" },
  ],
  placement: { avgPackage: "₹6 LPA", highestPackage: "₹40 LPA (indicative)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Cognizant", "Deloitte", "Wipro", "HCL"],
  highlights: [
    "Deemed university since 2008, primarily known for commerce, management, and liberal arts",
    "Newer, growing engineering school benefiting from Bengaluru's tech-industry base",
    "Strong overall university brand recognition",
    "Admission via own entrance test (CUET-based process) or JEE Main score",
  ],
  faqs: [
    { question: "Is Christ University primarily an engineering college?", answer: "No — Christ University is primarily known for its commerce, management, and liberal arts programmes; its School of Engineering and Technology is a smaller, more recently developed unit that benefits from the university's broader brand and Bengaluru's tech-industry base." },
    { question: "How is admission to Christ University B.Tech done?", answer: "Christ University admits B.Tech students through its own entrance-cum-merit process or JEE Main score, with seats allotted through the university's own counselling rounds." },
  ],
  sections: [
    { tab: "info", heading: "About Christ University Engineering", body: "Christ University was founded in 1969 in Bengaluru and granted deemed-to-be-university status in 2008. It has built its primary academic reputation around commerce, management, and liberal arts programmes, with a smaller School of Engineering and Technology developed more recently to offer Computer Science, Electronics, and Mechanical Engineering B.Tech programmes.\n\nThe engineering school benefits from Christ University's broader brand recognition and its Bengaluru location within India's largest technology-industry hub, even as it remains a newer, smaller part of the university's overall academic portfolio." },
    { tab: "info", heading: "Campus & Facilities", body: "Christ University's Bengaluru campus includes academic blocks, computer labs, hostels, and sports facilities shared across its many schools, reflecting the university's broader multi-disciplinary scale." },
    { tab: "info", heading: "Why Choose Christ University Engineering", body: "- Strong overall university brand recognition despite engineering being a newer offering\n- Bengaluru location within India's largest technology-industry hub\n- Access to Christ University's broader multi-disciplinary academic ecosystem\n- Multiple admission routes (own entrance-cum-merit process, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 180 | ₹8.0 L |\n| CSE — AI & ML | 4 years | 90 | ₹8.3 L |\n| Electronics & Communication | 4 years | 60 | ₹7.5 L |\n| Mechanical Engineering | 4 years | 60 | ₹7.0 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Christ University admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Christ University offers merit-based fee waivers tied to entrance/JEE Main score at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Christ University admits B.Tech students through its own entrance-cum-merit process or directly via JEE Main score. Applicants apply online, and seats are allotted through the university's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by category)\n- Valid entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Christ University's engineering placement cell benefits from the university's broader Bengaluru-based recruiter network, with CSE and AI & ML posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Deloitte and other analytics/consulting recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a moderate-to-competitive percentile in recent years given the university's strong overall brand demand. Confirm current-year cutoffs directly with Christ University admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance/JEE Main-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Need-based financial assistance through university-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Christ University is ranked #93 in NIRF 2024 Engineering, a newer addition to its NIRF presence, which is stronger in its long-established Management and Overall University categories." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Christ University provides on-campus hostel accommodation across its Bengaluru campus. Student life includes a large, well-established calendar of technical, cultural, and management-focused events reflecting the university's broader multi-disciplinary scale." },
  ],
};

const chitkara: CollegeContentPack = {
  slug: "chitkara-university",
  college: {
    estd: 2010,
    website: "https://www.chitkara.edu.in",
    feesNum: 750000,
    feesLabel: "₹7.5 L",
    packageLabel: "₹6 LPA",
    affiliation: "State Private University, Punjab",
    approvedBy: "UGC, AICTE",
    metaTitle: "Chitkara University Punjab — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Chitkara University Rajpura NIRF #94 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Chitkara University, founded in 2010 near Rajpura, Punjab, has grown quickly into one of North India's more placement-active private universities, with a large School of Engineering and Technology offering an extensive menu of Computer Science specialisations alongside core branches, backed by significant investment in campus infrastructure.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "480", feesLabel: "₹7.5 L total" },
    { name: "B.Tech CSE (AI, Cyber Security, Cloud Computing)", duration: "4 years", seats: "240", feesLabel: "₹7.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "120", feesLabel: "₹6.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹6 LPA", highestPackage: "₹52 LPA (indicative)", placedPct: "82" },
  recruiters: ["Amazon", "TCS", "Infosys", "Wipro", "Cognizant", "Deloitte", "HCL", "Capgemini"],
  highlights: [
    "Founded 2010 near Rajpura, Punjab — fast-growing private university",
    "Large School of Engineering with extensive Computer Science specialisation menu",
    "Significant investment in modern campus infrastructure",
    "Admission via CUCET-style own test or JEE Main score",
  ],
  faqs: [
    { question: "Is Chitkara University good for placements?", answer: "Chitkara has built a comparatively strong placement drive for a university founded as recently as 2010, particularly in its CSE and AI/Cyber Security specialisations, aided by significant investment in placement infrastructure." },
    { question: "How is admission to Chitkara University done?", answer: "Chitkara admits B.Tech students through its own entrance-cum-merit process (Chitkara University Admission Test) or directly via JEE Main score." },
  ],
  sections: [
    { tab: "info", heading: "About Chitkara University", body: "Chitkara University was founded in 2010 near Rajpura, Punjab, and has grown quickly into one of North India's more active private universities within a relatively short institutional history. Its School of Engineering and Technology is the university's flagship unit, running a large Computer Science programme with extensive specialisation options including AI, Cyber Security, and Cloud Computing, alongside core Electronics and Mechanical branches.\n\nChitkara has invested significantly in modern campus infrastructure and placement-cell capacity, helping it build a placement reputation that competes with several older private universities in the region." },
    { tab: "info", heading: "Campus & Facilities", body: "The Chitkara campus near Rajpura, Punjab, includes modern academic blocks, extensive computer labs, hostels, and sports facilities built largely from the ground up since the university's 2010 founding." },
    { tab: "info", heading: "Why Choose Chitkara University", body: "- Fast-growing placement reputation for a university founded as recently as 2010\n- Extensive Computer Science specialisation menu (AI, Cyber Security, Cloud Computing)\n- Modern, purpose-built campus infrastructure\n- Multiple admission routes (own entrance test, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 480 | ₹7.5 L |\n| CSE — AI, Cyber Security, Cloud Computing | 4 years | 240 | ₹7.8 L |\n| Electronics & Communication | 4 years | 120 | ₹6.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹6.0 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Chitkara admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Chitkara offers merit-based fee waivers tied to entrance/JEE Main score at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Chitkara admits B.Tech students through its own entrance-cum-merit process (Chitkara University Admission Test) or directly via JEE Main score. Applicants apply online, and seats are allotted through the university's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Chitkara's placement cell runs a growing drive across IT services with an increasing base of product-company and analytics recruiters, particularly for its AI and Cyber Security specialisations. Overall placement percentage has generally stayed around 82% across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Wipro, Cognizant, HCL, Capgemini (bulk IT-services hiring)\n- Deloitte and other analytics/consulting recruiters\n- Regional Punjab and North India IT/service firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a percentile in the 75-85 range in recent years; for the own entrance test, cutoffs are set relative to the year's applicant pool. Confirm current-year cutoffs directly with Chitkara admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance/JEE Main-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Education loan facilitation cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Chitkara University is ranked #94 in NIRF 2024 Engineering and also features in NIRF's Overall University category, a notable result for a university founded as recently as 2010." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Chitkara provides on-campus hostel accommodation across its Rajpura campus, with multiple room-sharing options. Student life includes technical and cultural fests, plus active sports facilities on the modern campus." },
  ],
};

const jainUniversity: CollegeContentPack = {
  slug: "jain-university",
  college: {
    estd: 1990,
    website: "https://www.jainuniversity.ac.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹5.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "Jain University Bengaluru — Engineering Courses, Fees, Placements 2026",
    metaDescription: "Jain University NIRF #95 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "Jain University, founded in 1990 and granted deemed-university status in 2009, operates from multiple campuses across Bengaluru, Karnataka, with a School of Engineering and Technology that benefits from the university's broader academic scale and Bengaluru's technology-industry base, alongside strong programmes in commerce, management, and sciences.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "240", feesLabel: "₹7.0 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "90", feesLabel: "₹7.3 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "60", feesLabel: "₹6.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹5.5 LPA", highestPackage: "₹38 LPA (indicative)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Cognizant", "Wipro", "Deloitte", "HCL"],
  highlights: [
    "Deemed university since 2009, multiple campuses across Bengaluru",
    "Growing engineering school benefiting from Bengaluru's tech-industry base",
    "Strong overall university brand across commerce, management, and sciences",
    "Admission via own entrance test or JEE Main score",
  ],
  faqs: [
    { question: "Is Jain University good for engineering?", answer: "Jain University's engineering programme is a growing part of a broader, well-established multi-disciplinary university, benefiting from Bengaluru's technology-industry base for placements even as its academic reputation is stronger in commerce and management." },
    { question: "How is admission to Jain University B.Tech done?", answer: "Jain University admits B.Tech students through its own entrance test or directly via JEE Main score, with seats allotted through the university's own counselling process." },
  ],
  sections: [
    { tab: "info", heading: "About Jain University Engineering", body: "Jain University was founded in 1990 and granted deemed-to-be-university status in 2009, operating from multiple campuses across Bengaluru, Karnataka. Its academic reputation has been built substantially around commerce, management, and sciences, with a School of Engineering and Technology offering Computer Science, Electronics, and Mechanical Engineering B.Tech programmes as a growing part of the university's broader portfolio.\n\nThe engineering school benefits from Jain University's Bengaluru location within India's largest technology-industry hub, aiding its placement outcomes even as its academic reputation remains stronger in commerce and management." },
    { tab: "info", heading: "Campus & Facilities", body: "Jain University's Bengaluru campuses include academic blocks, computer labs, hostels, and sports facilities shared across its many schools, reflecting the university's broader multi-disciplinary scale." },
    { tab: "info", heading: "Why Choose Jain University Engineering", body: "- Strong overall university brand recognition across commerce, management, and sciences\n- Bengaluru location within India's largest technology-industry hub\n- Access to Jain University's broader multi-disciplinary academic ecosystem\n- Multiple admission routes (own entrance test, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 240 | ₹7.0 L |\n| CSE — AI & ML | 4 years | 90 | ₹7.3 L |\n| Electronics & Communication | 4 years | 60 | ₹6.5 L |\n| Mechanical Engineering | 4 years | 60 | ₹6.0 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official Jain University admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "Jain University offers merit-based fee waivers tied to entrance/JEE Main score at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "Jain University admits B.Tech students through its own entrance test or directly via JEE Main score. Applicants apply online, and seats are allotted through the university's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by category)\n- Valid entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "Jain University's engineering placement cell benefits from the university's broader Bengaluru-based recruiter network, with CSE and AI & ML posting the strongest outcomes. Overall placement percentage has generally stayed in the high 70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Deloitte and other analytics/consulting recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a moderate-to-competitive percentile in recent years. Confirm current-year cutoffs directly with Jain University admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance/JEE Main-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Need-based financial assistance through university-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Jain University is ranked #95 in NIRF 2024 Engineering, a newer addition to its NIRF presence, which is stronger in its long-established Management and Overall University categories." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "Jain University provides on-campus hostel accommodation across its Bengaluru campuses. Student life includes a large, well-established calendar of technical, cultural, and management-focused events reflecting the university's broader multi-disciplinary scale." },
  ],
};

const cvRaman: CollegeContentPack = {
  slug: "c-v-raman-global-university",
  college: {
    estd: 1997,
    website: "https://cgu-odisha.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹4.2 LPA",
    affiliation: "State Private University, Odisha",
    approvedBy: "UGC, AICTE",
    metaTitle: "C.V. Raman Global University — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "C.V. Raman Global University Bhubaneswar NIRF #96 engineering: B.Tech courses, fees, admission, placement, hostel details.",
    about:
      "C.V. Raman Global University, founded in 1997 and granted state private university status, operates from a campus in Bhubaneswar, Odisha, named after the Nobel laureate physicist Sir C.V. Raman. It runs a wide-ranging engineering programme spread with a growing regional placement network across eastern India.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹5.0 L total" },
    { name: "B.Tech CSE (AI & Data Science)", duration: "4 years", seats: "90", feesLabel: "₹5.2 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹4.2 L total" },
  ],
  placement: { avgPackage: "₹4.2 LPA", highestPackage: "₹30 LPA (indicative)", placedPct: "74" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)"],
  highlights: [
    "Named after Nobel laureate Sir C.V. Raman, founded 1997 in Bhubaneswar",
    "State private university status with a growing eastern India placement network",
    "Wide engineering programme spread including AI & Data Science",
    "Admission via own entrance test or JEE Main score",
  ],
  faqs: [
    { question: "Is C.V. Raman Global University related to the physicist C.V. Raman?", answer: "The university is named in honour of the Nobel laureate physicist Sir C.V. Raman but is an independently run private university, not directly affiliated with his family or estate." },
    { question: "How is admission done?", answer: "C.V. Raman Global University admits B.Tech students through its own entrance test or directly via JEE Main score, with seats allotted through the university's own counselling process." },
  ],
  sections: [
    { tab: "info", heading: "About C.V. Raman Global University", body: "C.V. Raman Global University was founded in 1997 and granted state private university status, operating from a campus in Bhubaneswar, Odisha. Named in honour of the Nobel laureate physicist Sir C.V. Raman, the university runs a wide-ranging engineering programme spread including Computer Science, Electronics, and Mechanical Engineering, alongside programmes in pharmacy, management, and allied sciences.\n\nThe university has built a growing regional placement network across eastern India, benefiting from Bhubaneswar's developing IT and industrial base." },
    { tab: "info", heading: "Campus & Facilities", body: "The C.V. Raman Global University campus in Bhubaneswar includes academic blocks, computer labs, hostels, and sports facilities typical of an established regional private university." },
    { tab: "info", heading: "Why Choose C.V. Raman Global University", body: "- Growing regional placement network across eastern India\n- Wide engineering programme spread including AI & Data Science\n- State private university status with Bhubaneswar location\n- Multiple admission routes (own entrance test, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 300 | ₹5.0 L |\n| CSE — AI & Data Science | 4 years | 90 | ₹5.2 L |\n| Electronics & Communication | 4 years | 90 | ₹4.5 L |\n| Mechanical Engineering | 4 years | 60 | ₹4.2 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official C.V. Raman Global University admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "The university offers merit-based fee waivers tied to entrance/JEE Main score at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "C.V. Raman Global University admits B.Tech students through its own entrance test or directly via JEE Main score. Applicants apply online, and seats are allotted through the university's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "The university's placement cell runs drives concentrated in IT services, with CSE and its AI & Data Science specialisation posting the strongest outcomes. Overall placement percentage has generally stayed in the mid-70s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Amazon for select high-performing CSE graduates\n- Regional Odisha and eastern India IT firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a moderate percentile in recent years; for the own entrance test, cutoffs are set relative to the year's applicant pool. Confirm current-year cutoffs directly with C.V. Raman Global University admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance/JEE Main-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Odisha state government scholarship schemes for eligible domicile students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "C.V. Raman Global University is ranked #96 in NIRF 2024 Engineering and also features in NIRF's Overall University category." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "The university provides on-campus hostel accommodation for men and women across its Bhubaneswar campus. Student life includes technical and cultural fests, plus active sports facilities." },
  ],
};

const nitPuducherry: CollegeContentPack = {
  slug: "national-institute-of-technology-puducherry",
  college: {
    estd: 2010,
    website: "https://www.nitpy.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹8 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Puducherry — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Puducherry Karaikal NIRF #97 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Puducherry, established in 2010 as one of the newer NITs formed under the National Institutes of Technology Act, operates from a campus in Karaikal, a coastal region of the Puducherry union territory. As a young institute, it carries the full NIT brand and JoSAA-based admission process while continuing to develop its permanent infrastructure.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "40", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹8 LPA", highestPackage: "₹34 LPA (indicative)", placedPct: "76" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Cognizant", "HCL"],
  highlights: [
    "One of the newer NITs (2010), located in Karaikal, Puducherry",
    "Coastal campus setting in the Puducherry union territory",
    "Growing CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Puducherry a good option?", answer: "As one of the newer NITs, NIT Puducherry's infrastructure and placement network are still developing relative to older NITs, but it carries the NIT brand and JoSAA admission credibility, with a distinctive coastal campus setting." },
    { question: "What is NIT Puducherry's CSE cutoff?", answer: "CSE closing ranks at NIT Puducherry have typically fallen in the 20,000-26,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Puducherry", body: "National Institute of Technology, Puducherry was established in 2010 as one of the newer NITs sanctioned under the National Institutes of Technology Act, 2007. Located in Karaikal, a coastal region of the Puducherry union territory, it runs undergraduate programmes across Computer Science, Electronics & Communication, Mechanical, and Civil Engineering.\n\nAs a young institute, NIT Puducherry is still building out its permanent infrastructure and research profile, but its NIT brand and JoSAA-based admission give it strong national credibility." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Puducherry campus in Karaikal is being developed in phases, with academic blocks, hostels, and laboratory facilities expanding as the institute matures. Its coastal setting gives the campus a distinctive character among NITs." },
    { tab: "info", heading: "Why Choose NIT Puducherry", body: "- NIT brand and JoSAA admission credibility for a coastal Puducherry-region institute\n- Distinctive Karaikal coastal campus setting\n- Growing placement network as the institute matures\n- Comparatively accessible JoSAA cutoffs relative to older, more established NITs" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 70 | ₹5.5 L |\n| Electronics & Communication | 4 years | 60 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 60 | ₹5.5 L |\n| Civil Engineering | 4 years | 40 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Puducherry's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Puducherry's placement cell draws IT-services recruiters, with CSE graduates posting the strongest outcomes. Overall placement percentage has generally stayed in the mid-70s across recent years as the institute's placement network continues to grow." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant, HCL (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Regional Puducherry and Tamil Nadu industrial firms" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 20,000 – 26,000 |\n| Electronics & Communication | 30,000 – 38,000 |\n| Mechanical Engineering | 42,000 – 52,000 |\n| Civil Engineering | 48,000 – 58,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Puducherry is ranked #97 in NIRF 2024 Engineering, a solid position for one of the newer NITs founded in 2010." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Puducherry provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity as the campus matures." },
  ],
};

const srUniversity: CollegeContentPack = {
  slug: "sr-university",
  college: {
    estd: 2019,
    website: "https://sru.edu.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹4.5 LPA",
    affiliation: "State Private University, Telangana",
    approvedBy: "UGC, AICTE",
    metaTitle: "SR University Warangal — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "SR University Warangal NIRF #98 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "SR University, founded in 2019 in Warangal, Telangana, is one of the youngest institutes in this NIRF ranking band, having built its engineering programme and placement network from scratch within a short institutional history, reflecting a broader trend of newer Telangana private universities investing heavily in fast NIRF ranking growth.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "180", feesLabel: "₹5.5 L total" },
    { name: "B.Tech CSE (AI & ML)", duration: "4 years", seats: "90", feesLabel: "₹5.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "60", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "60", feesLabel: "₹4.8 L total" },
  ],
  placement: { avgPackage: "₹4.5 LPA", highestPackage: "₹28 LPA (indicative)", placedPct: "72" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)"],
  highlights: [
    "Founded 2019 in Warangal, Telangana — one of the youngest institutes in this ranking band",
    "Built its engineering programme and placement network from scratch within a short history",
    "Growing CSE and AI/ML specialisation focus",
    "Admission via own entrance test or TS EAMCET/JEE Main score",
  ],
  faqs: [
    { question: "How is SR University so new but already NIRF-ranked?", answer: "SR University has invested deliberately in building research output and placement infrastructure quickly since its 2019 founding, part of a broader pattern among newer Telangana private universities pursuing fast NIRF ranking growth." },
    { question: "How is admission to SR University done?", answer: "SR University admits B.Tech students through its own entrance test, or directly via TS EAMCET rank or JEE Main score." },
  ],
  sections: [
    { tab: "info", heading: "About SR University", body: "SR University was founded in 2019 in Warangal, Telangana, making it one of the youngest institutes in this NIRF ranking band. The university has built its engineering programme — spanning Computer Science, Electronics, and Mechanical branches — and its placement infrastructure from scratch within a short institutional history, part of a broader pattern among newer Telangana private universities investing heavily in fast NIRF ranking growth.\n\nSR University's rapid rise reflects a deliberate strategy of research-output investment and industry partnerships common among ambitious newer private institutions in South India." },
    { tab: "info", heading: "Campus & Facilities", body: "The SR University campus in Warangal includes modern academic blocks, computer labs, hostels, and sports facilities built entirely since the university's 2019 founding." },
    { tab: "info", heading: "Why Choose SR University", body: "- Fast-growing NIRF presence for a university founded as recently as 2019\n- Modern, purpose-built campus infrastructure\n- Growing CSE and AI/ML specialisation focus\n- Multiple admission routes (own entrance test, TS EAMCET, JEE Main)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 180 | ₹5.5 L |\n| CSE — AI & ML | 4 years | 90 | ₹5.8 L |\n| Electronics & Communication | 4 years | 60 | ₹5.0 L |\n| Mechanical Engineering | 4 years | 60 | ₹4.8 L |\n\nFees are charged per year and vary by specialisation; confirm current-year figures on the official SR University admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "SR University offers merit-based fee waivers tied to entrance/EAMCET/JEE Main score at admission. Fees are payable in semester instalments through the university's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "SR University admits B.Tech students through its own entrance test, or directly via TS EAMCET rank or JEE Main score. Applicants apply online, and seats are allotted through the university's own counselling rounds based on rank/score and branch preference." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by category)\n- Valid entrance score, TS EAMCET rank, or JEE Main score as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "SR University's placement cell runs a growing drive concentrated in IT services, with CSE and AI & ML posting the strongest outcomes. Overall placement percentage has generally stayed around 72% across recent years as the institute's placement network continues to develop." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Amazon for select high-performing CSE graduates\n- Regional Telangana IT and manufacturing firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the TS EAMCET route, CSE cutoff ranks have typically fallen within a moderately competitive band for open category in recent years; for the own entrance test, cutoffs are set relative to the year's applicant pool. Confirm current-year cutoffs directly with SR University admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to annual CGPA\n- Telangana state government scholarship schemes for eligible domicile students\n- Sibling and alumni-family fee concessions" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "SR University is ranked #98 in NIRF 2024 Engineering, a notably fast rise for a university founded as recently as 2019." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SR University provides on-campus hostel accommodation for men and women across its Warangal campus. Student life includes technical and cultural fests, plus active sports facilities on the modern campus." },
  ],
};

const rvce: CollegeContentPack = {
  slug: "r-v-college-of-engineering",
  college: {
    estd: 1963,
    website: "https://rvce.edu.in",
    feesNum: 600000,
    feesLabel: "₹6.0 L",
    packageLabel: "₹9 LPA",
    affiliation: "Autonomous College, VTU",
    approvedBy: "UGC, AICTE",
    metaTitle: "R.V. College of Engineering Bengaluru — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "RVCE Bengaluru NIRF #99 engineering: B.Tech courses, fees, KCET/COMEDK admission, placement stats, hostel and scholarship details.",
    about:
      "R.V. College of Engineering (RVCE), founded in 1963 in Bengaluru, is widely regarded as one of the best private engineering colleges in India, autonomous and affiliated with VTU. Its combination of academic rigour, strong faculty, and direct access to Bengaluru's technology-industry base has made it one of the most sought-after non-deemed private engineering colleges nationally.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "300", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Information Science & Engineering", duration: "4 years", seats: "180", feesLabel: "₹5.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "180", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "150", feesLabel: "₹5.0 L total" },
  ],
  placement: { avgPackage: "₹9 LPA", highestPackage: "₹56 LPA (indicative)", placedPct: "90" },
  recruiters: ["Amazon", "Microsoft", "Goldman Sachs", "TCS", "Infosys", "Cisco", "Deloitte", "Bosch"],
  highlights: [
    "Founded 1963, widely regarded as one of the best private engineering colleges in India",
    "Bengaluru location gives direct access to India's largest technology-industry hub",
    "Consistently among the highest placement percentages of any non-deemed private college nationally",
    "Admission via KCET or COMEDK UGET counselling",
  ],
  faqs: [
    { question: "Is RVCE one of the best engineering colleges in India?", answer: "RVCE is widely regarded as one of the top non-deemed private engineering colleges in India, with a reputation that rivals several NITs for Computer Science and Information Science, driven by strong faculty, academic rigour, and its Bengaluru location." },
    { question: "How is admission to RVCE done?", answer: "RVCE admits students primarily through Karnataka CET (KCET) for state-domicile candidates and COMEDK UGET for a broader applicant pool including out-of-state students." },
  ],
  sections: [
    { tab: "info", heading: "About RVCE", body: "R.V. College of Engineering was founded in 1963 in Bengaluru, Karnataka, and has grown into one of the most respected private engineering colleges in India. As an autonomous college affiliated with Visvesvaraya Technological University (VTU), RVCE combines academic rigour with direct access to Bengaluru's dense technology-industry base, running strong programmes across Computer Science, Information Science, Electronics, and Mechanical Engineering.\n\nRVCE's reputation is widely regarded as rivaling several NITs, particularly for Computer Science and Information Science, and it consistently ranks among the top choices for Karnataka's most competitive KCET and COMEDK applicants." },
    { tab: "info", heading: "Campus & Location", body: "The RVCE campus in Bengaluru spans a well-established site with departmental blocks, a central library, and workshop facilities built up over six decades. Its Bengaluru location places it in close proximity to major technology-company campuses across the city." },
    { tab: "info", heading: "Why Choose RVCE", body: "- Widely regarded as one of the best non-deemed private engineering colleges in India\n- Reputation rivaling several NITs for Computer Science and Information Science\n- Direct access to India's largest technology-industry hub\n- Consistently among the highest placement percentages nationally for a private college" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 300 | ₹6.0 L |\n| Information Science & Engineering | 4 years | 180 | ₹5.8 L |\n| Electronics & Communication | 4 years | 180 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 150 | ₹5.0 L |\n\nFees vary between KCET-counselled (government-regulated) and COMEDK/management-quota seats; confirm current-year figures with RVCE admissions." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "KCET-counselled seats follow Karnataka government-regulated fee slabs; COMEDK and management-quota seats carry a separate (higher) fee structure. Fees are payable per semester through the college's designated bank channels." },
    { tab: "admissions", heading: "Admission Process", body: "RVCE admits students primarily through Karnataka CET (KCET) for Karnataka-domicile candidates and COMEDK UGET for a broader applicant pool including out-of-state students, with a smaller management-quota admission process available. Applicants apply through the relevant counselling process and are allotted seats based on rank and category." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per KCET/COMEDK norms\n- Valid KCET or COMEDK UGET rank/score\n- Documents: Class 10/12 mark sheets, entrance scorecard, category/domicile certificate (for KCET), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "RVCE's placement cell runs one of the strongest drives among non-deemed private colleges nationally, drawing both dense IT-services hiring and a significant base of top-tier product-company and analytics recruiters. Overall placement percentage has generally stayed around 90% across recent years, among the best for a private college in India." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Cisco (product/software)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- TCS, Infosys (bulk IT-services hiring)\n- Bosch and other core-engineering/R&D recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the KCET route, CSE admissions have typically required a rank within the top 1,000-2,000 in recent years for open category, among the most competitive of any VTU-affiliated college; for COMEDK, similarly tight ranks are needed given very high demand. These figures are indicative — RVCE publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Karnataka state government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible KCET students\n- RVCE merit scholarships for top academic performers\n- Continuing merit scholarships tied to semester GPA\n- Need-based financial assistance through alumni-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "R.V. College of Engineering is ranked #99 in NIRF 2024 Engineering — a position that understates its reputation, which is widely regarded within Karnataka and nationally as among the very best non-deemed private engineering colleges in India." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "RVCE provides on-campus hostel accommodation for both men and women, though a significant share of students commute given the college's Bengaluru location. Student life includes the annual technical symposium and cultural fest, plus active sports and departmental clubs reflecting the college's six-decade history." },
  ],
};

const siddaganga: CollegeContentPack = {
  slug: "siddaganga-institute-of-technology",
  college: {
    estd: 1963,
    website: "https://www.sit.ac.in",
    feesNum: 500000,
    feesLabel: "₹5.0 L",
    packageLabel: "₹5.5 LPA",
    affiliation: "Autonomous College, VTU",
    approvedBy: "UGC, AICTE",
    metaTitle: "Siddaganga Institute of Technology Tumkur — Courses, Fees, Placements 2026",
    metaDescription: "SIT Tumkur NIRF #100 engineering: B.Tech courses, fees, KCET/COMEDK admission, placement stats, hostel and scholarship details.",
    about:
      "Siddaganga Institute of Technology (SIT), founded in 1963 in Tumkur, Karnataka, under the patronage of the Siddaganga Math, is a well-regarded autonomous engineering college affiliated with VTU, known for its academic discipline, strong alumni network, and steady placement outcomes despite being located outside Bengaluru's immediate metro area.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "240", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Information Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹4.8 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹4.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "120", feesLabel: "₹4.2 L total" },
  ],
  placement: { avgPackage: "₹5.5 LPA", highestPackage: "₹36 LPA (indicative)", placedPct: "82" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "HCL", "Amazon (select roles)", "L&T"],
  highlights: [
    "Founded 1963 under the patronage of the Siddaganga Math in Tumkur, Karnataka",
    "Well-regarded academic discipline and strong alumni network",
    "Steady placement outcomes despite being outside Bengaluru's immediate metro area",
    "Admission via KCET or COMEDK UGET counselling",
  ],
  faqs: [
    { question: "Where is SIT Tumkur located?", answer: "Siddaganga Institute of Technology is located in Tumkur, Karnataka, roughly 70 km from Bengaluru, and was founded under the patronage of the Siddaganga Math, a prominent regional religious and educational institution." },
    { question: "Is SIT Tumkur good for placements?", answer: "SIT Tumkur posts steady placement outcomes for a college located outside Bengaluru's immediate metro area, helped by its strong academic reputation and alumni network within Karnataka's engineering ecosystem." },
  ],
  sections: [
    { tab: "info", heading: "About SIT Tumkur", body: "Siddaganga Institute of Technology was founded in 1963 in Tumkur, Karnataka, under the patronage of the Siddaganga Math, a prominent regional religious and educational institution. As an autonomous college affiliated with Visvesvaraya Technological University (VTU), SIT runs undergraduate programmes across Computer Science, Information Science, Electronics, and Mechanical Engineering.\n\nSIT has built a reputation for academic discipline and a strong alumni network within Karnataka's engineering ecosystem, maintaining steady placement outcomes despite being located roughly 70 km from Bengaluru rather than within the city itself." },
    { tab: "info", heading: "Campus & Location", body: "The SIT campus in Tumkur spans a substantial site associated with the broader Siddaganga Math institution, with academic blocks, hostels, a central library, and workshop facilities built up over six decades." },
    { tab: "info", heading: "Why Choose SIT Tumkur", body: "- Well-regarded academic discipline and strong Karnataka alumni network\n- Steady placement outcomes despite being outside Bengaluru's immediate metro area\n- Association with the Siddaganga Math's broader educational reputation\n- Six decades of institutional history" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 240 | ₹5.0 L |\n| Information Science & Engineering | 4 years | 120 | ₹4.8 L |\n| Electronics & Communication | 4 years | 150 | ₹4.5 L |\n| Mechanical Engineering | 4 years | 120 | ₹4.2 L |\n\nFees vary between KCET-counselled (government-regulated) and COMEDK/management-quota seats; confirm current-year figures with SIT admissions." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "KCET-counselled seats follow Karnataka government-regulated fee slabs; COMEDK and management-quota seats carry a separate fee structure. Fees are payable per semester through the college's designated bank channels." },
    { tab: "admissions", heading: "Admission Process", body: "SIT admits students primarily through Karnataka CET (KCET) for Karnataka-domicile candidates and COMEDK UGET for a broader applicant pool including out-of-state students, with a smaller management-quota admission process available. Applicants apply through the relevant counselling process and are allotted seats based on rank and category." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per KCET/COMEDK norms\n- Valid KCET or COMEDK UGET rank/score\n- Documents: Class 10/12 mark sheets, entrance scorecard, category/domicile certificate (for KCET), passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "SIT's placement cell runs steady campus drives concentrated in IT services with core-engineering participation. CSE and Information Science post the strongest outcomes; overall placement percentage has generally stayed around 82% across recent years, solid for a college outside Bengaluru's immediate metro area." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring)\n- Amazon for select high-performing CSE graduates\n- L&T (core engineering)\n- Regional Karnataka manufacturing and infrastructure firms" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the KCET route, CSE admissions have typically required a moderately competitive rank in recent years for open category; for COMEDK, similarly competitive ranks are needed. These figures are indicative — SIT publishes exact cutoffs after each counselling round." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Karnataka state government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible KCET students\n- SIT merit scholarships for top academic performers\n- Continuing merit scholarships tied to semester GPA\n- Need-based financial assistance through Siddaganga Math-affiliated aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "Siddaganga Institute of Technology is ranked #100 in NIRF 2024 Engineering, rounding out the top-100 with a solid position for a self-financing, non-deemed private college with six decades of academic history." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SIT provides on-campus hostel accommodation for both men and women, particularly important given its location outside Bengaluru's immediate metro area. Student life includes the annual technical symposium and cultural fest, plus active sports and departmental clubs." },
  ],
};

export const engBatch8: CollegeContentPack[] = [
  ggsipu,
  auCollegeEngg,
  vignan,
  shoolini,
  christUniversity,
  chitkara,
  jainUniversity,
  cvRaman,
  nitPuducherry,
  srUniversity,
  rvce,
  siddaganga,
];
