import type { CollegeContentPack } from "./types";

// NIRF Engineering 2024 #42-50 — hand-authored, matches iit-madras.ts / eng-batch2.ts / eng-batch3.ts depth.

const upes: CollegeContentPack = {
  slug: "upes",
  college: {
    estd: 2003,
    website: "https://www.upes.ac.in",
    feesNum: 900000,
    feesLabel: "₹9.0 L",
    packageLabel: "₹7 LPA",
    affiliation: "State Private University, Uttarakhand",
    approvedBy: "UGC, AICTE",
    metaTitle: "UPES Dehradun — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "UPES Dehradun NIRF #42 engineering: B.Tech courses, fees, admission process, placement stats, hostel and scholarship details.",
    about:
      "University of Petroleum and Energy Studies (UPES), founded in 2003 in Dehradun, Uttarakhand, began with a specific focus on energy, petroleum, and automotive engineering sectors, backed by strong industry founding partners, and has since broadened into a full-spectrum private university with a large School of Computer Science alongside its original energy-sector specialisations.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "480", feesLabel: "₹9.0 L total" },
    { name: "B.Tech Petroleum Engineering", duration: "4 years", seats: "60", feesLabel: "₹8.5 L total" },
    { name: "B.Tech Mechanical (Automotive Design)", duration: "4 years", seats: "90", feesLabel: "₹8.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹8.0 L total" },
  ],
  placement: { avgPackage: "₹7 LPA", highestPackage: "₹56 LPA (indicative)", placedPct: "83" },
  recruiters: ["Amazon", "Microsoft", "ONGC", "Shell", "Deloitte", "TCS", "Maruti Suzuki", "EY"],
  highlights: [
    "Founded 2003 with an original focus on energy and petroleum sectors, backed by industry partners",
    "Now runs a large, placement-strong School of Computer Science",
    "Distinctive niche specialisations: Petroleum Engineering, Automotive Design",
    "Admission via UPESEAT (own test), JEE Main, or Board merit",
  ],
  faqs: [
    { question: "Is UPES good for Petroleum Engineering?", answer: "UPES is one of India's few private universities with a dedicated Petroleum Engineering programme and strong ties to energy-sector recruiters like ONGC and Shell, making it a recognised niche choice for that specialisation." },
    { question: "What is UPESEAT?", answer: "UPESEAT is UPES's own entrance aptitude test; applicants can alternatively use their JEE Main score or Class 12 board merit for admission, depending on the programme." },
  ],
  sections: [
    { tab: "info", heading: "About UPES", body: "University of Petroleum and Energy Studies (UPES) was established in 2003 in Dehradun, Uttarakhand, with founding industry backing oriented toward the energy and petroleum sector — a niche that gave it early differentiation from generic private engineering colleges. Since then, UPES has expanded substantially, building a large School of Computer Science that now accounts for the bulk of its engineering intake, alongside its original strengths in Petroleum Engineering, Automotive Design, and allied energy programmes.\n\nUPES has positioned itself around industry-integrated curricula, with several programmes co-designed with corporate partners and built-in industry certification tracks." },
    { tab: "info", heading: "Campus & Facilities", body: "UPES operates from the Energy Acres and Knowledge Acres campuses in Bidholi and Kandoli, Dehradun, with modern academic blocks, dedicated labs for automotive and energy specialisations, and a growing computer science infrastructure including AI/ML and gaming labs." },
    { tab: "info", heading: "Why Choose UPES", body: "- Distinctive niche programmes (Petroleum Engineering, Automotive Design) with direct energy/auto-sector industry ties\n- Large, well-placed School of Computer Science\n- Industry-integrated curriculum design with corporate co-created programmes\n- Multiple admission routes (UPESEAT, JEE Main, board merit)" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 480 | ₹9.0 L |\n| Petroleum Engineering | 4 years | 60 | ₹8.5 L |\n| Mechanical (Automotive Design) | 4 years | 90 | ₹8.0 L |\n| Electronics & Communication | 4 years | 90 | ₹8.0 L |\n\nFees are charged per year and vary by specialisation; UPES revises fee slabs periodically, so confirm the current year's figures on the official admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "UPES offers merit-based scholarships tied to UPESEAT rank, JEE Main percentile, or Class 12 percentage at admission. Fees are payable in semester instalments through the university's online portal, with education-loan tie-ups available." },
    { tab: "admissions", heading: "Admission Process", body: "UPES offers three main routes: UPESEAT (its own online aptitude test), direct admission via JEE Main score, or Class 12 board-merit-based admission for select programmes. Applicants apply online, and UPES releases branch-wise merit lists across multiple rounds based on the chosen route's score." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by branch/category)\n- Valid UPESEAT score, JEE Main rank, or qualifying board percentage as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard (if applicable), category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "UPES runs a placement drive spanning IT services, energy-sector firms, automotive majors, and consulting recruiters, reflecting its dual identity as both a computer-science-heavy and energy-sector-niche university. CSE placement outcomes lead the university; Petroleum Engineering and Automotive Design draw sector-specific recruiters with strong starting packages relative to batch size." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, TCS (software)\n- ONGC, Shell (petroleum/energy — key for the Petroleum Engineering programme)\n- Maruti Suzuki and other automotive majors (Automotive Design)\n- Deloitte, EY (consulting/analytics)" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a percentile in the 80-90 range in recent years; for UPESEAT, cutoffs are set relative to the year's applicant pool. Petroleum Engineering and Automotive Design typically have comparatively lower cutoffs given smaller applicant pools relative to CSE. Confirm current-year cutoffs with UPES admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- UPESEAT/JEE Main rank-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Corporate-sponsored scholarships tied to UPES's energy-sector industry partners" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "UPES is ranked #42 in NIRF 2024 Engineering and also features in NIRF's Overall University and Management categories, reflecting its multi-disciplinary growth beyond its original energy-sector focus." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "UPES provides on-campus hostel accommodation across its Bidholi and Kandoli campuses, with multiple room-sharing options. Campus life includes technical fests, an active automotive/racing club (relevant to its Automotive Design programme), and Dehradun's cooler, hill-adjacent climate as a backdrop." },
  ],
};

const mnitJaipur: CollegeContentPack = {
  slug: "malaviya-national-institute-of-technology",
  college: {
    estd: 1963,
    website: "https://www.mnit.ac.in",
    feesNum: 600000,
    feesLabel: "₹6.0 L",
    packageLabel: "₹12.5 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "MNIT Jaipur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "MNIT Jaipur NIRF #43 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "Malaviya National Institute of Technology, Jaipur, established in 1963 as a Regional Engineering College and elevated to NIT status in 2002 (named after Pandit Madan Mohan Malaviya), is Rajasthan's premier technical institute. Its Jaipur campus draws students nationwide through JoSAA, with recognised strength in Computer Science, Electronics, and Architecture programmes alongside core engineering branches.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "100", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "80", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹12.5 LPA", highestPackage: "₹48 LPA (indicative)", placedPct: "86" },
  recruiters: ["Amazon", "Microsoft", "Goldman Sachs", "Adobe", "L&T", "ONGC", "Deloitte", "Samsung R&D"],
  highlights: [
    "Rajasthan's premier NIT, founded 1963, NIT status since 2002",
    "Recognised architecture programme alongside core engineering branches",
    "Strong CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is MNIT Jaipur a good NIT?", answer: "MNIT Jaipur is consistently ranked among the top 10-15 NITs nationally, with strong CSE and Electronics placement outcomes and a well-regarded Architecture programme." },
    { question: "What is MNIT's JEE Main cutoff for CSE?", answer: "CSE closing ranks at MNIT Jaipur have typically fallen in the 4,000-6,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About MNIT Jaipur", body: "Malaviya National Institute of Technology, Jaipur was established in 1963 as a Regional Engineering College and was granted National Institute of Technology (Institute of National Importance) status in 2002, named after the educationist and freedom fighter Pandit Madan Mohan Malaviya. Located in Jaipur, Rajasthan, MNIT serves as the state's premier technical institute, running undergraduate programmes across Computer Science, Electronics, Electrical, Mechanical, Civil, Chemical, and a well-regarded Architecture programme.\n\nMNIT has built strong research and placement credentials over six decades, particularly in computer science, electronics, and materials-related research areas." },
    { tab: "info", heading: "Campus & Location", body: "MNIT's campus is located on JLN Marg in Jaipur, spanning a substantial urban campus with academic blocks, hostels, a central library, and workshop facilities. Jaipur's status as a major Rajasthan city gives the institute strong connectivity and access to a growing local IT and industrial base." },
    { tab: "info", heading: "Why Choose MNIT Jaipur", body: "- Among the top 15 NITs nationally, with strong CSE and Electronics outcomes\n- Recognised Architecture programme, uncommon among NITs\n- Six decades of academic heritage and alumni network\n- Central Jaipur location with strong city connectivity" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹6.0 L |\n| Electronics & Communication | 4 years | 100 | ₹6.0 L |\n| Mechanical Engineering | 4 years | 90 | ₹6.0 L |\n| Civil Engineering | 4 years | 80 | ₹6.0 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to MNIT Jaipur's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. The Architecture programme (B.Arch) uses JEE Main Paper 2 / NATA scores instead. Candidates register on JoSAA, list preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "MNIT Jaipur's placement cell runs strong campus drives across software, core engineering, and analytics recruiters, with CSE and Electronics posting the highest packages. Overall placement percentage has stayed in the mid-to-high 80s across recent years per institute placement reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft, Adobe, Samsung R&D (software/product)\n- Goldman Sachs, Deloitte (analytics/consulting)\n- L&T, ONGC (core/PSU)\n- A wide base of regional Rajasthan IT and infrastructure firms" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 4,000 – 6,000 |\n| Electronics & Communication | 8,000 – 11,000 |\n| Mechanical Engineering | 13,000 – 17,000 |\n| Civil Engineering | 17,000 – 22,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Rajasthan state government scholarship schemes for eligible domicile students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "MNIT Jaipur is ranked #43 in NIRF 2024 Engineering, holding a consistent position among the top 15 NITs nationally." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "MNIT provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes the annual technical fest Technosearch and cultural fest Manthan, plus active sports and departmental clubs." },
  ],
};

const nitDurgapur: CollegeContentPack = {
  slug: "national-institute-of-technology-durgapur",
  college: {
    estd: 1960,
    website: "https://www.nitdgp.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹10 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Durgapur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Durgapur NIRF #44 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Durgapur, established in 1960 as a Regional Engineering College and elevated to NIT status in 2002, is West Bengal's leading technical institute outside Kolkata. Located in the industrial city of Durgapur, it draws students nationwide through JoSAA, with particular strength in Mining Engineering and Metallurgy alongside core Computer Science and Electrical branches.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "120", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mining Engineering", duration: "4 years", seats: "40", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "90", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹10 LPA", highestPackage: "₹45 LPA (indicative)", placedPct: "84" },
  recruiters: ["Amazon", "TCS", "Infosys", "Tata Steel", "Coal India", "L&T", "Cognizant", "Deloitte"],
  highlights: [
    "West Bengal's leading NIT outside Kolkata, founded 1960, NIT status since 2002",
    "Distinctive Mining Engineering programme tied to the region's coal and steel industry",
    "Solid CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Durgapur good for Mining Engineering?", answer: "NIT Durgapur's Mining Engineering programme benefits from its location in West Bengal's coal and steel industrial belt, with strong recruiter ties to Coal India and Tata Steel among its core-sector placements." },
    { question: "What is NIT Durgapur's CSE cutoff?", answer: "CSE closing ranks at NIT Durgapur have typically fallen in the 12,000-16,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Durgapur", body: "National Institute of Technology, Durgapur was established in 1960 as a Regional Engineering College and was granted National Institute of Technology status in 2002. Located in Durgapur, an industrial city in West Bengal known for steel and coal production, the institute has built particular strength in Mining Engineering and Metallurgical Engineering alongside its core Computer Science, Electronics, Electrical, Mechanical, and Civil programmes.\n\nNIT Durgapur's proximity to major steel plants (Durgapur Steel Plant) and coal fields has historically shaped strong industry-academia ties for its core-branch students." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Durgapur campus spans over 200 acres in Durgapur, West Bengal, roughly 170 km from Kolkata. It includes academic blocks, hostels, a central library, and workshop facilities, with the region's industrial base providing regular internship and placement pipelines." },
    { tab: "info", heading: "Why Choose NIT Durgapur", body: "- Distinctive Mining Engineering programme with direct ties to the regional coal/steel industry\n- NIT brand and infrastructure with accessible JoSAA cutoffs relative to older NITs\n- Solid CSE and Electronics placement outcomes\n- Industrial-belt location providing regular core-sector internship opportunities" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 120 | ₹5.5 L |\n| Electronics & Communication | 4 years | 90 | ₹5.5 L |\n| Mining Engineering | 4 years | 40 | ₹5.5 L |\n| Mechanical Engineering | 4 years | 90 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Durgapur's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Durgapur's placement cell draws IT-services and core-industrial recruiters, with strong participation from steel, mining, and manufacturing companies alongside growing software-sector interest. Overall placement percentage has stayed in the low-to-mid 80s across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, TCS, Infosys, Cognizant (software/IT services)\n- Tata Steel, Coal India (core/mining — key for Mining and Metallurgical Engineering)\n- L&T, Deloitte (core engineering/consulting)\n- Regional steel and manufacturing firms across West Bengal and eastern India" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 12,000 – 16,000 |\n| Electronics & Communication | 20,000 – 26,000 |\n| Mechanical Engineering | 30,000 – 38,000 |\n| Mining Engineering | 45,000 – 55,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- West Bengal state government scholarship schemes for eligible domicile students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Durgapur is ranked #44 in NIRF 2024 Engineering, maintaining its position as West Bengal's leading NIT outside Kolkata." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Durgapur provides on-campus hostel accommodation for the large majority of students, with separate hostels for men and women. Student life includes the annual technical fest Incryptus and cultural fest Rhapsody, plus active sports and departmental clubs." },
  ],
};

const nitDelhi: CollegeContentPack = {
  slug: "national-institute-of-technology-delhi",
  college: {
    estd: 2010,
    website: "https://nitdelhi.ac.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹9 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "NIT Delhi — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "NIT Delhi NIRF #45 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "National Institute of Technology, Delhi, established in 2010 as one of the newer NITs formed under the National Institutes of Technology Act, operates from a campus in Narela, on Delhi's northern outskirts. Despite being one of the youngest NITs, its Delhi-NCR location has helped it build a strong recruiter pipeline, particularly for Computer Science and Electronics graduates.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "80", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "70", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Electrical Engineering", duration: "4 years", seats: "60", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "50", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹9 LPA", highestPackage: "₹40 LPA (indicative)", placedPct: "80" },
  recruiters: ["Amazon", "TCS", "Infosys", "Wipro", "Cognizant", "Deloitte", "HCL", "Capgemini"],
  highlights: [
    "One of the newer NITs (2010), campus in Narela, Delhi",
    "Delhi-NCR location supports strong recruiter access",
    "Growing CSE and Electronics placement outcomes",
    "JEE Main via JoSAA is the sole B.Tech admission route",
  ],
  faqs: [
    { question: "Is NIT Delhi a good option?", answer: "NIT Delhi is one of the newer NITs, and while its infrastructure is still maturing relative to older NITs, its Delhi-NCR location gives it strong access to recruiters, particularly for IT-services and analytics roles." },
    { question: "What is NIT Delhi's CSE cutoff?", answer: "CSE closing ranks at NIT Delhi have typically fallen in the 14,000-18,000 band (General, Other State) in recent JoSAA rounds; verify current-year figures on the JoSAA seat matrix." },
  ],
  sections: [
    { tab: "info", heading: "About NIT Delhi", body: "National Institute of Technology, Delhi was established in 2010 as one of the newer NITs sanctioned under the National Institutes of Technology Act, 2007. It operates from a campus in Narela on Delhi's northern outskirts, running undergraduate programmes in Computer Science, Electronics & Communication, Electrical, and Civil Engineering.\n\nAs a young institute, NIT Delhi is still building out its permanent infrastructure and research profile relative to older NITs, but its location within the National Capital Region gives it a meaningful advantage in recruiter access and internship opportunities." },
    { tab: "info", heading: "Campus & Location", body: "The NIT Delhi campus in Narela is being developed in phases, with academic blocks, hostels, and laboratory facilities expanding as the institute matures. Its position within Delhi-NCR provides strong connectivity to the region's dense corporate and IT-services base." },
    { tab: "info", heading: "Why Choose NIT Delhi", body: "- NIT brand and JoSAA admission credibility with a Delhi-NCR location advantage\n- Growing placement pipeline benefiting from proximity to NCR's corporate base\n- Comparatively accessible JoSAA cutoffs relative to older, more established NITs\n- Smaller batch sizes allowing closer faculty-student interaction" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 80 | ₹5.5 L |\n| Electronics & Communication | 4 years | 70 | ₹5.5 L |\n| Electrical Engineering | 4 years | 60 | ₹5.5 L |\n| Civil Engineering | 4 years | 50 | ₹5.5 L |\n\nFees follow the standard NIT fee structure; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, per common NIT fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Main via JoSAA)", body: "Admission to NIT Delhi's B.Tech programmes is through JEE Main rank via JoSAA centralised counselling, with home-state and other-state quota seats allocated per the common NIT system. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 75% aggregate (or top 20 percentile) for NIT eligibility\n- Valid JEE Main rank for the admission year\n- Documents: Class 10/12 mark sheets, JEE Main scorecard, category/domicile certificate, photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "NIT Delhi's placement cell benefits from its NCR location, drawing a strong base of IT-services and analytics recruiters. CSE and Electronics graduates post the strongest outcomes; overall placement percentage has generally stayed around 80% across recent years as the institute's placement network continues to mature." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select roles)\n- TCS, Infosys, Wipro, Cognizant, HCL, Capgemini (bulk IT-services hiring)\n- Deloitte (analytics/consulting)\n- Regional Delhi-NCR IT and infrastructure firms" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx., Other State) |\n|---|---|\n| Computer Science & Engineering | 14,000 – 18,000 |\n| Electronics & Communication | 22,000 – 28,000 |\n| Electrical Engineering | 28,000 – 35,000 |\n| Civil Engineering | 35,000 – 45,000 |\n\nRanges are indicative and vary by home-state/other-state quota; verify the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- Delhi and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "NIT Delhi is ranked #45 in NIRF 2024 Engineering — a solid position for one of the youngest institutes in the NIT system, founded in 2010." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "NIT Delhi provides on-campus hostel accommodation as its infrastructure continues to expand, with separate hostels for men and women. Student life includes technical and cultural fests along with growing sports and departmental club activity as the campus matures." },
  ],
};

const ssnCollege: CollegeContentPack = {
  slug: "sri-sivasubramaniya-nadar-college-of-engineering",
  college: {
    estd: 1996,
    website: "https://www.ssn.edu.in",
    feesNum: 550000,
    feesLabel: "₹5.5 L",
    packageLabel: "₹6.5 LPA",
    affiliation: "Autonomous College, Anna University",
    approvedBy: "UGC, AICTE",
    metaTitle: "SSN College of Engineering — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "SSN College of Engineering Kalavakkam NIRF #46: B.Tech courses, fees, TNEA admission, placement stats, hostel and scholarship details.",
    about:
      "Sri Sivasubramaniya Nadar College of Engineering (SSN), founded in 1996 near Kalavakkam on Chennai's IT corridor (OMR), is a self-financing autonomous college affiliated with Anna University. Despite being privately run, SSN has built one of Tamil Nadu's strongest placement and academic reputations among non-deemed private engineering colleges, particularly in Computer Science and Information Technology.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "240", feesLabel: "₹5.5 L total" },
    { name: "B.Tech Information Technology", duration: "4 years", seats: "120", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "180", feesLabel: "₹5.0 L total" },
    { name: "B.Tech Electrical & Electronics", duration: "4 years", seats: "120", feesLabel: "₹4.8 L total" },
  ],
  placement: { avgPackage: "₹6.5 LPA", highestPackage: "₹43 LPA (indicative)", placedPct: "88" },
  recruiters: ["TCS", "Infosys", "Cognizant", "Zoho", "Amazon (select roles)", "Wipro", "HCL", "Standard Chartered"],
  highlights: [
    "Self-financing autonomous college affiliated with Anna University, founded 1996",
    "Located on Chennai's OMR IT corridor, close to major tech-park employers",
    "Consistently high placement percentage among Tamil Nadu's private engineering colleges",
    "Admission via TNEA (Tamil Nadu Engineering Admissions) counselling",
  ],
  faqs: [
    { question: "How is admission to SSN done?", answer: "SSN College of Engineering admits students through TNEA (Tamil Nadu Engineering Admissions) counselling, based on Class 12 cutoff marks, for Tamil Nadu domicile students; a management quota exists for a smaller share of seats." },
    { question: "Is SSN good for placements?", answer: "SSN posts one of the highest placement percentages among Tamil Nadu's private engineering colleges, particularly in Computer Science and IT, helped significantly by its location on Chennai's OMR IT corridor." },
  ],
  sections: [
    { tab: "info", heading: "About SSN College of Engineering", body: "Sri Sivasubramaniya Nadar College of Engineering was founded in 1996 by the SSN Trust near Kalavakkam, on Chennai's Old Mahabalipuram Road (OMR) — the heart of the city's IT corridor. As a self-financing college affiliated with Anna University, SSN operates with significant academic autonomy while remaining tied to the university's examination and degree framework.\n\nSSN has built a reputation as one of the strongest non-deemed private engineering colleges in Tamil Nadu, particularly for Computer Science and Information Technology, helped by its proximity to major IT parks and tech employers along the OMR corridor." },
    { tab: "info", heading: "Campus & Location", body: "The SSN campus in Kalavakkam spans a substantial site along OMR, with dedicated departmental blocks, a well-stocked library, and sports facilities. Its OMR location places it minutes from major tech parks housing companies like TCS, Infosys, Cognizant, and Wipro — a significant advantage for internships and placements." },
    { tab: "info", heading: "Why Choose SSN College of Engineering", body: "- Among the strongest placement records of any non-deemed private college in Tamil Nadu\n- OMR location gives direct proximity to Chennai's largest IT-park cluster\n- Strong Anna University-affiliated academic rigour with college-level autonomy\n- Consistently competitive TNEA cutoffs reflecting high demand" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 240 | ₹5.5 L |\n| Information Technology | 4 years | 120 | ₹5.0 L |\n| Electronics & Communication | 4 years | 180 | ₹5.0 L |\n| Electrical & Electronics | 4 years | 120 | ₹4.8 L |\n\nFees are set per Anna University/Tamil Nadu government norms for self-financing colleges and revised periodically; confirm current-year figures with SSN admissions." },
    { tab: "courses-fees", heading: "Fee Payment & Concessions", body: "TNEA-counselled seats follow government-regulated fee slabs; management-quota seats carry a separate (higher) fee structure. Fees are payable per semester through the college's designated bank channels." },
    { tab: "admissions", heading: "Admission Process (TNEA)", body: "The bulk of SSN's seats are filled through TNEA (Tamil Nadu Engineering Admissions) counselling, based on a normalised Class 12 cutoff score (out of 200) for Tamil Nadu domicile students. A smaller share of seats is available under the management quota, filled by SSN's own admission process for out-of-state or otherwise eligible candidates." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per TNEA norms\n- TNEA cutoff score/rank for counselling-quota seats\n- Documents: Class 10/12 mark sheets, TNEA application/rank card, community certificate (Tamil Nadu candidates), transfer certificate, passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "SSN's placement cell benefits substantially from its OMR location, running dense recruitment drives with IT-services majors and a growing base of product-company and analytics recruiters. Overall placement percentage has generally stayed in the mid-to-high 80s across recent years, among the best for a non-deemed private college in the state." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Cognizant, Wipro, HCL (bulk IT-services hiring, aided by OMR proximity)\n- Zoho (select product-engineering roles)\n- Standard Chartered (analytics/banking-tech)\n- Amazon for select high-performing CSE/IT graduates" },
    { tab: "cutoffs", heading: "TNEA Cutoffs (Indicative)", body: "| Branch | Approx. TNEA Cutoff (Open Category, out of 200) |\n|---|---|\n| Computer Science & Engineering | 195 – 199 |\n| Information Technology | 192 – 197 |\n| Electronics & Communication | 188 – 194 |\n| Electrical & Electronics | 180 – 188 |\n\nRanges are indicative from recent TNEA counselling years; exact cutoffs vary by round and category, confirm on the official TNEA portal." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Tamil Nadu government scholarship and fee-reimbursement schemes for SC/ST/OBC-eligible students\n- SSN Trust merit scholarships for top academic performers\n- Continuing merit scholarships tied to semester GPA\n- Need-based financial assistance through the college's alumni-funded aid programmes" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "SSN College of Engineering is ranked #46 in NIRF 2024 Engineering — a strong position for a self-financing, non-deemed private college, reflecting its placement strength and academic reputation within Tamil Nadu." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "SSN provides on-campus hostel accommodation for both men and women, though a significant share of students commute given the college's proximity to Chennai. Student life includes the annual technical symposium Techsangam and cultural fest, plus active sports and departmental clubs." },
  ],
};

const iiitHyderabad: CollegeContentPack = {
  slug: "international-institute-of-information-technology-hyderabad",
  college: {
    estd: 1998,
    website: "https://www.iiit.ac.in",
    feesNum: 1000000,
    feesLabel: "₹10.0 L",
    packageLabel: "₹22 LPA",
    affiliation: "Deemed University (Elite, State-supported)",
    approvedBy: "UGC, AICTE",
    metaTitle: "IIIT Hyderabad — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIIT Hyderabad NIRF #47 engineering: B.Tech/Dual-Degree courses, fees, admission via UGEE/JEE Main, placement package, hostel details.",
    about:
      "International Institute of Information Technology, Hyderabad (IIIT-H), founded in 1998 as India's first IIIT and granted deemed-university status, is widely regarded as an elite computer science and research institute on par with the top IITs for its core specialisation. Located in Gachibowli, Hyderabad's tech hub, IIIT-H runs distinctive Dual Degree (B.Tech + M.S./M.Tech) programmes and admits students through its own UGEE test as well as JEE Main scores.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "165", feesLabel: "₹10.0 L total" },
    { name: "B.Tech Electronics & Communication Engineering", duration: "4 years", seats: "95", feesLabel: "₹10.0 L total" },
    { name: "Dual Degree CSE (B.Tech + M.S. by Research)", duration: "5 years", seats: "90", feesLabel: "₹12.5 L total" },
    { name: "B.Tech Computational Natural Sciences", duration: "4 years", seats: "20", feesLabel: "₹10.0 L total" },
  ],
  placement: { avgPackage: "₹22 LPA", highestPackage: "₹1.2 Cr (indicative)", placedPct: "95" },
  recruiters: ["Google", "Microsoft", "Amazon", "Adobe", "Goldman Sachs", "Sprinklr", "Rubrik", "Qualcomm"],
  highlights: [
    "India's first IIIT (1998), located in Gachibowli, Hyderabad's tech corridor",
    "Elite CS-focused deemed university, placement outcomes rivaling top IITs",
    "Distinctive Dual Degree (B.Tech + M.S. by Research) programmes",
    "Admission via UGEE (own test) or JEE Main score",
  ],
  faqs: [
    { question: "Is IIIT Hyderabad as good as an IIT?", answer: "For Computer Science specifically, IIIT Hyderabad's research output, faculty, and placement packages are widely regarded as on par with or exceeding all but the very top IITs (Bombay, Delhi), reflecting its deep, singular focus on CS and allied fields." },
    { question: "How do I get into IIIT Hyderabad?", answer: "Admission is via UGEE (Undergraduate Entrance Exam, IIIT-H's own test) or directly through JEE Main rank for a portion of seats — check the current year's exact seat split between the two routes on the official admissions page." },
  ],
  sections: [
    { tab: "info", heading: "About IIIT Hyderabad", body: "International Institute of Information Technology, Hyderabad was founded in 1998 as India's first Information Technology-focused institute of its kind, established as a not-for-profit, self-supporting, deemed university with strong support from the Andhra Pradesh (now Telangana) state government and the IT industry. Located in Gachibowli, at the heart of Hyderabad's technology corridor, IIIT-H has built a research and placement reputation that is widely regarded as elite among India's computer science institutes.\n\nA defining feature is its research-integrated Dual Degree structure, where a significant share of undergraduates pursue a combined B.Tech + M.S. by Research over five years, embedding them in active faculty research labs from early in their degree." },
    { tab: "info", heading: "Campus & Location", body: "The IIIT-H campus in Gachibowli sits within Hyderabad's HITEC City tech corridor, surrounded by major technology company campuses (Microsoft, Google, Amazon, Deloitte, and others have offices nearby), which feeds directly into its internship and placement pipeline. The campus itself is compact but intensively research-oriented, with numerous specialised labs across computer vision, NLP, robotics, VLSI, and more." },
    { tab: "info", heading: "Why Choose IIIT Hyderabad", body: "- Elite, singularly CS-focused institute with placement outcomes among India's best\n- Distinctive research-integrated Dual Degree (B.Tech + M.S. by Research) option\n- Gachibowli location places it in the middle of Hyderabad's tech-industry cluster\n- Small, highly selective batch sizes with deep faculty-student research engagement" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 165 | ₹10.0 L |\n| Electronics & Communication Engineering | 4 years | 95 | ₹10.0 L |\n| Dual Degree CSE (B.Tech + M.S. by Research) | 5 years | 90 | ₹12.5 L |\n| Computational Natural Sciences | 4 years | 20 | ₹10.0 L |\n\nFees are charged per year and are higher than public NITs/IITs given IIIT-H's self-supporting deemed-university model; confirm current-year figures on the official admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "IIIT-H offers need-based and merit-based fee waivers, including full tuition waivers for economically weaker students under its need-blind admission commitment for Indian nationals. Fees are payable per semester through the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "IIIT-H admits students via UGEE (Undergraduate Entrance Examination), its own computer-based test, and also accepts a portion of seats through JEE Main rank. Applicants apply online, sit UGEE if choosing that route, and are allotted seats based on rank/score across IIIT-H's own counselling process." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum aggregate as per IIIT-H norms\n- Valid UGEE score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate (if applicable), passport photos" },
    { tab: "placements", heading: "Placement Overview", body: "IIIT-H posts placement outcomes among the strongest of any Indian institute, with the vast majority of graduates placed in software engineering, research, and quant/analytics roles at leading global technology and finance firms. Average and median packages are consistently reported at levels comparable to IIT Bombay/Delhi CSE, reflecting the institute's singular focus on computing." },
    { tab: "placements", heading: "Top Recruiters", body: "- Google, Microsoft, Amazon, Adobe (software/product)\n- Goldman Sachs and other quant/analytics firms\n- Sprinklr, Rubrik (high-growth product companies)\n- Qualcomm and other semiconductor/R&D recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "UGEE admission to CSE is extremely competitive, with typically only the top few hundred rank-holders (out of tens of thousands of applicants) securing a seat; for the JEE Main route, CSE cutoff ranks have historically been comparable to or tighter than several older IITs. These figures are indicative — IIIT-H publishes exact cutoffs after each admission cycle." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Need-blind admission policy with full/partial fee waivers for economically weaker Indian students\n- Merit scholarships for top UGEE/JEE Main rank-holders\n- Research assistantships for Dual Degree students embedded in faculty labs\n- External and corporate-sponsored scholarships accessible to eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIIT Hyderabad is ranked #47 in NIRF 2024 Engineering, a ranking that understates its reputation specifically within computer science and research circles, where it is regarded as one of India's very top CS institutes." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIIT-H provides on-campus hostel accommodation for the large majority of students, with a research-lab culture that keeps many students on campus late into the evening. Student life includes Felicity, its large annual techno-cultural fest, alongside a dense calendar of hackathons, research talks, and coding competitions reflecting the institute's CS-first identity." },
  ],
};

const bitMesra: CollegeContentPack = {
  slug: "birla-institute-of-technology-mesra",
  college: {
    estd: 1955,
    website: "https://www.bitmesra.ac.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹7.5 LPA",
    affiliation: "Deemed University",
    approvedBy: "UGC, AICTE",
    metaTitle: "BIT Mesra — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "Birla Institute of Technology Mesra NIRF #48 engineering: B.Tech courses, fees, admission via BITSAT-equivalent, placement, hostel details.",
    about:
      "Birla Institute of Technology, Mesra (BIT Mesra), established in 1955 near Ranchi, Jharkhand, is one of India's oldest private deemed universities, predating even the IIT system's expansion. With a large, self-contained campus and a wide spread of engineering, pharmacy, and management programmes, BIT Mesra has built a long-standing reputation across eastern India and beyond, alongside satellite campuses in several other cities.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "240", feesLabel: "₹7.0 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "150", feesLabel: "₹6.5 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "150", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "90", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹7.5 LPA", highestPackage: "₹44 LPA (indicative)", placedPct: "80" },
  recruiters: ["TCS", "Infosys", "Amazon (select roles)", "Wipro", "Tata Steel", "L&T", "Cognizant", "Deloitte"],
  highlights: [
    "One of India's oldest private deemed universities, founded 1955",
    "Large, self-contained campus near Ranchi, Jharkhand with satellite campuses elsewhere",
    "Long-standing regional reputation across eastern India",
    "Admission via BITSAT-equivalent BIT Mesra entrance test or JEE Main score",
  ],
  faqs: [
    { question: "Is BIT Mesra different from BITS Pilani?", answer: "Yes — Birla Institute of Technology, Mesra (BIT Mesra) is a separate institution from Birla Institute of Technology and Science, Pilani (BITS Pilani), despite the similar founding-family name. They have different admission processes, campuses, and administrations." },
    { question: "What is the admission process at BIT Mesra?", answer: "BIT Mesra admits B.Tech students through its own entrance examination or via JEE Main score for a portion of seats — check the current year's exact seat split on the official admissions page." },
  ],
  sections: [
    { tab: "info", heading: "About BIT Mesra", body: "Birla Institute of Technology, Mesra was established in 1955 near Ranchi in what is now Jharkhand, making it one of India's oldest private engineering institutions — predating even most IITs' founding. Granted deemed-university status decades ago, BIT Mesra has grown to include Computer Science, Electronics, Mechanical, Civil, Biotechnology, and Pharmacy programmes, alongside postgraduate and doctoral research.\n\nBIT Mesra also operates satellite/extension campuses in cities including Patna, Jaipur, and Noida, extending its reach well beyond its original Ranchi base, though the main Mesra campus remains its flagship." },
    { tab: "info", heading: "Campus & Location", body: "The main BIT Mesra campus spans a large, self-contained site near Ranchi, Jharkhand, with academic blocks, extensive hostel infrastructure, a hospital, and sports facilities built up over nearly seven decades. Its scale and self-sufficiency reflect its long institutional history relative to newer private universities." },
    { tab: "info", heading: "Why Choose BIT Mesra", body: "- Nearly 70 years of institutional history and a large, established alumni network\n- Wide programme spread across engineering, pharmacy, and management\n- Multiple campus locations (Ranchi, Patna, Jaipur, Noida) for flexibility\n- Deemed-university curriculum flexibility with long-standing industry ties" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| Computer Science & Engineering | 4 years | 240 | ₹7.0 L |\n| Electronics & Communication | 4 years | 150 | ₹6.5 L |\n| Mechanical Engineering | 4 years | 150 | ₹6.0 L |\n| Civil Engineering | 4 years | 90 | ₹6.0 L |\n\nFees are charged per year and vary modestly across the Ranchi main campus and satellite campuses; confirm current-year figures on the official BIT Mesra admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "BIT Mesra offers merit-based fee waivers tied to entrance rank or JEE Main percentile at admission, along with continuing merit scholarships. Fees are payable in semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process", body: "BIT Mesra offers admission through its own entrance examination (conducted online across multiple test centres) or directly via JEE Main rank for a portion of seats. Applicants apply online, and BIT Mesra releases branch- and campus-wise merit lists across multiple counselling rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 60% aggregate (varies by branch/category)\n- Valid BIT Mesra entrance score or JEE Main rank as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard, category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "BIT Mesra's placement cell runs campus drives concentrated in IT services with growing product-company and core-sector participation, particularly given its proximity to Jharkhand's steel and mining industrial base. CSE placement outcomes lead the institute; overall placement percentage has generally stayed around 80% across recent years per institute reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- TCS, Infosys, Wipro, Cognizant (bulk IT-services hiring)\n- Amazon for select CSE roles\n- Tata Steel, L&T (core/manufacturing, given the Jharkhand industrial belt)\n- Deloitte and other consulting/analytics recruiters" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "For the JEE Main route, CSE admissions have typically required a percentile in the 85-92 range in recent years; for BIT Mesra's own entrance test, cutoffs are set relative to the year's applicant pool. These figures are indicative — confirm current-year cutoffs with BIT Mesra admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Entrance-rank/JEE Main percentile-based merit scholarships up to substantial tuition waivers\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular achievement scholarships\n- Jharkhand state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "BIT Mesra is ranked #48 in NIRF 2024 Engineering, reflecting its long institutional history and consistent placement/research output relative to other private deemed universities." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "BIT Mesra provides extensive on-campus hostel accommodation given its large, self-contained Ranchi campus, including a campus hospital and sports complex built up over decades. Student life includes the annual technical fest Envision and cultural fest Vivo, plus a strong alumni-network presence at campus events." },
  ],
};

const iiestShibpur: CollegeContentPack = {
  slug: "indian-institute-of-engineering-science-and-technology-shibpur",
  college: {
    estd: 1856,
    website: "https://www.iiests.ac.in",
    feesNum: 600000,
    feesLabel: "₹6.0 L",
    packageLabel: "₹11 LPA",
    affiliation: "Institute of National Importance",
    approvedBy: "MHRD, AICTE",
    metaTitle: "IIEST Shibpur — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "IIEST Shibpur NIRF #49 engineering: B.Tech courses, fees, JoSAA cutoffs, placement package, hostel and scholarship details.",
    about:
      "Indian Institute of Engineering Science and Technology, Shibpur, tracing its history to 1856 as one of Asia's oldest engineering colleges, became India's first IIEST in 2014, a distinct category of Institute of National Importance modeled on the IIT system. Located in Howrah, West Bengal, across the river from Kolkata, IIEST Shibpur combines nearly 170 years of engineering-education heritage with an IIT-equivalent admission and funding structure.",
  },
  courses: [
    { name: "B.Tech Computer Science & Technology", duration: "4 years", seats: "80", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Electronics & Telecommunication", duration: "4 years", seats: "70", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Civil Engineering", duration: "4 years", seats: "70", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "70", feesLabel: "₹6.0 L total" },
  ],
  placement: { avgPackage: "₹11 LPA", highestPackage: "₹46 LPA (indicative)", placedPct: "82" },
  recruiters: ["Amazon", "Microsoft", "TCS", "Tata Steel", "ONGC", "L&T", "Deloitte", "Cognizant"],
  highlights: [
    "Traces to 1856 — among Asia's oldest engineering colleges",
    "First IIEST in India (2014), an Institute of National Importance modeled on the IIT system",
    "Historic Shibpur campus in Howrah, across the river from Kolkata",
    "JEE Advanced is the primary admission route via JoSAA",
  ],
  faqs: [
    { question: "Is IIEST Shibpur equivalent to an IIT?", answer: "IIEST Shibpur holds Institute of National Importance status, the same category as IITs, and is admitted through JEE Advanced/JoSAA, making it functionally IIT-equivalent in status and admission process, though branded separately as an IIEST." },
    { question: "How old is IIEST Shibpur?", answer: "IIEST Shibpur traces its roots to 1856 as the Civil Engineering College, Calcutta, making it one of the oldest engineering institutions in Asia — it became IIEST (with National Importance status) only in 2014." },
  ],
  sections: [
    { tab: "info", heading: "About IIEST Shibpur", body: "Indian Institute of Engineering Science and Technology, Shibpur traces its origins to 1856, when it was established as the Civil Engineering College, Calcutta — making it one of the oldest engineering institutions in Asia. After operating for decades as Bengal Engineering and Science University (BESU), it was converted in 2014 into India's first IIEST, a distinct category of Institute of National Importance with funding and admission structures modeled closely on the IIT system.\n\nLocated in Shibpur, Howrah, directly across the Hooghly river from Kolkata, IIEST combines a rare depth of institutional history with modern IIT-equivalent status, running programmes across Computer Science, Electronics, Civil, Mechanical, Electrical, and several other engineering and architecture disciplines." },
    { tab: "info", heading: "Campus & Location", body: "The IIEST Shibpur campus in Howrah spans a historic site with colonial-era academic buildings alongside newer construction, reflecting its nearly 170-year history. Its location just across the river from Kolkata gives students access to the city's cultural and economic hub while maintaining a distinct, heritage-rich campus identity." },
    { tab: "info", heading: "Why Choose IIEST Shibpur", body: "- Institute of National Importance status equivalent to IITs, admitted via JEE Advanced/JoSAA\n- Nearly 170 years of engineering-education heritage — among the oldest in Asia\n- Location directly across the river from Kolkata, a major eastern India economic hub\n- Wide programme spread including architecture alongside core engineering branches" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats | Total Fees |\n|---|---|---|---|\n| Computer Science & Technology | 4 years | 80 | ₹6.0 L |\n| Electronics & Telecommunication | 4 years | 70 | ₹6.0 L |\n| Civil Engineering | 4 years | 70 | ₹6.0 L |\n| Mechanical Engineering | 4 years | 70 | ₹6.0 L |\n\nFees follow a structure comparable to the IIT system given IIEST's equivalent National Importance status; SC/ST/PwD and income-eligible students receive tuition waivers under government policy." },
    { tab: "courses-fees", heading: "Fee Waivers & Payment", body: "Tuition is waived for SC/ST students and for General/OBC/EWS students with family income below ₹5 lakh/year, consistent with central-institute fee-waiver policy. Fees are payable in two semester instalments via the institute's online portal." },
    { tab: "admissions", heading: "Admission Process (JEE Advanced via JoSAA)", body: "Admission to IIEST Shibpur's B.Tech programmes is primarily through JEE Advanced rank via the JoSAA centralised counselling process, the same system used for IIT admissions, reflecting its Institute of National Importance status. Candidates register on JoSAA, list branch/institute preferences, and are allotted seats over multiple rounds." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics\n- Valid JEE Advanced rank for the admission year\n- Age and attempt-limit criteria per JEE Advanced rules\n- Documents: Class 10/12 mark sheets, JEE Advanced scorecard, category certificate (if applicable), photo ID" },
    { tab: "placements", heading: "Placement Overview", body: "IIEST Shibpur's placement cell runs campus drives across software, core engineering, and PSU recruiters, with Computer Science and Electronics graduates posting the strongest package outcomes. Overall placement percentage has generally stayed in the low-to-mid 80s across recent years per institute placement reports." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon, Microsoft (software)\n- Tata Steel, ONGC, L&T (core/PSU)\n- Deloitte, Cognizant, TCS (consulting/IT services)\n- Regional West Bengal and eastern India infrastructure firms for Civil branch" },
    { tab: "cutoffs", heading: "JoSAA Closing Ranks (Indicative)", body: "| Branch | General Closing Rank (approx.) |\n|---|---|\n| Computer Science & Technology | 6,000 – 9,000 |\n| Electronics & Telecommunication | 10,000 – 14,000 |\n| Mechanical Engineering | 14,000 – 19,000 |\n| Civil Engineering | 18,000 – 24,000 |\n\nRanges are indicative from recent JoSAA rounds; confirm the current cycle's cutoffs on the official JoSAA seat matrix." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- Full/partial tuition waiver for SC/ST, PwD, and income-eligible General/OBC/EWS students\n- Merit-cum-Means scholarships for hostel/mess cost support\n- Institute merit scholarships for top academic performers\n- West Bengal state and central government scholarship schemes for eligible students" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "IIEST Shibpur is ranked #49 in NIRF 2024 Engineering, reflecting its dual identity as both one of Asia's oldest engineering institutions and a modern Institute of National Importance." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "IIEST Shibpur provides on-campus hostel accommodation across several historic and newer hostel blocks. Student life includes the annual technical fest Srijan and cultural fest, plus a strong sports and alumni-network culture reflecting the institute's nearly 170-year history." },
  ],
};

const lpu: CollegeContentPack = {
  slug: "lovely-professional-university",
  college: {
    estd: 2005,
    website: "https://www.lpu.in",
    feesNum: 700000,
    feesLabel: "₹7.0 L",
    packageLabel: "₹5.5 LPA",
    affiliation: "State Private University, Punjab",
    approvedBy: "UGC, AICTE",
    metaTitle: "Lovely Professional University (LPU) — Courses, Fees, Placements, Cutoffs 2026",
    metaDescription: "LPU Phagwara NIRF #50 engineering: B.Tech courses, fees, LPUNEST admission, placement drive stats, hostel and scholarship details.",
    about:
      "Lovely Professional University (LPU), founded in 2005 in Phagwara, Punjab, has grown into India's largest single-campus private university by enrolment, running an exceptionally wide range of B.Tech specialisations and one of the country's highest-volume campus placement operations. Its scale — tens of thousands of students across engineering, management, agriculture, and more — gives LPU a placement-drive reach that few Indian universities can match.",
  },
  courses: [
    { name: "B.Tech Computer Science & Engineering", duration: "4 years", seats: "1800", feesLabel: "₹7.0 L total" },
    { name: "B.Tech CSE (AI, Data Science, Cyber Security)", duration: "4 years", seats: "600", feesLabel: "₹7.5 L total" },
    { name: "B.Tech Electronics & Communication", duration: "4 years", seats: "240", feesLabel: "₹6.0 L total" },
    { name: "B.Tech Mechanical Engineering", duration: "4 years", seats: "180", feesLabel: "₹5.5 L total" },
  ],
  placement: { avgPackage: "₹5.5 LPA", highestPackage: "₹1.2 Cr (indicative, top international offer)", placedPct: "78" },
  recruiters: ["Amazon", "TCS", "Infosys", "Wipro", "Accenture", "Cognizant", "HCL", "Capgemini"],
  highlights: [
    "India's largest single-campus private university by enrolment, founded 2005",
    "One of the highest-volume campus placement drives among Indian universities",
    "Very wide programme spread — CSE, AI/ML, agriculture, design, and more on one campus",
    "Admission via LPUNEST (own test) or JEE Main/board merit",
  ],
  faqs: [
    { question: "How big is LPU's campus?", answer: "LPU's Phagwara campus is one of the largest single university campuses in India by area and enrolment, hosting tens of thousands of students across engineering, management, agriculture, design, and other schools." },
    { question: "What is LPUNEST?", answer: "LPUNEST (LPU National Eligibility and Scholarship Test) is LPU's own entrance-cum-scholarship exam; applicants can alternatively use JEE Main scores or Class 12 board merit for admission, and LPUNEST performance also determines merit-scholarship eligibility." },
  ],
  sections: [
    { tab: "info", heading: "About LPU", body: "Lovely Professional University was founded in 2005 in Phagwara, Punjab, and has since grown into India's largest single-campus private university by student enrolment. Its scale is unusual even among large private universities — LPU runs schools spanning engineering, management, agriculture, design, hotel management, law, and more, all on one integrated campus.\n\nWithin engineering, LPU's School of Computer Science and Engineering is by far its largest programme by intake, offering an extensive menu of specialisations including AI & Machine Learning, Data Science, Cyber Security, IoT, and Blockchain alongside core CSE." },
    { tab: "info", heading: "Campus & Facilities", body: "The LPU campus in Phagwara spans over 600 acres, making it one of the largest university campuses in India, with dedicated buildings per school, a large central library, extensive sports infrastructure (including its own cricket ground), and campus-wide digital-learning systems." },
    { tab: "info", heading: "Why Choose LPU", body: "- Massive scale gives access to one of India's highest-volume campus placement drives\n- Very wide CSE specialisation choice (AI/ML, Data Science, Cyber Security, IoT, Blockchain)\n- Large multi-disciplinary campus allows cross-school electives and exposure\n- Multiple admission routes (LPUNEST, JEE Main, board merit) with tied scholarship opportunities" },
    { tab: "courses-fees", heading: "B.Tech Programmes & Fee Structure", body: "| Programme | Duration | Seats (approx.) | Total Fees |\n|---|---|---|---|\n| CSE (core) | 4 years | 1800 | ₹7.0 L |\n| CSE — AI, Data Science, Cyber Security | 4 years | 600 | ₹7.5 L |\n| Electronics & Communication | 4 years | 240 | ₹6.0 L |\n| Mechanical Engineering | 4 years | 180 | ₹5.5 L |\n\nFees are charged per year and vary by specialisation; LPU revises fee slabs periodically and offers substantial LPUNEST-linked scholarships that can significantly reduce effective cost — confirm current-year figures on the official LPU admissions portal." },
    { tab: "courses-fees", heading: "Fee Payment & Waivers", body: "LPU ties a significant share of its fee structure to LPUNEST performance, with scholarships ranging from 25% to 100% tuition waiver based on rank/score. Fees are payable in semester instalments through the university's online portal, with education-loan tie-ups available." },
    { tab: "admissions", heading: "Admission Process", body: "LPU offers three main routes for B.Tech admission: LPUNEST (its own entrance-cum-scholarship test), direct admission via JEE Main score, or Class 12 board-merit-based admission. Applicants apply online, and LPU releases branch-wise merit lists and scholarship offers across multiple rounds based on the chosen route's score." },
    { tab: "admissions", heading: "Eligibility & Documents", body: "- Class 12 pass with Physics, Chemistry, Mathematics, minimum 50-60% aggregate (varies by branch/category)\n- Valid LPUNEST score, JEE Main rank, or qualifying board percentage as per chosen route\n- Documents: Class 10/12 mark sheets, entrance scorecard (if applicable), category certificate, passport photos, transfer certificate" },
    { tab: "placements", heading: "Placement Overview", body: "LPU's Training and Placement Cell runs one of India's highest-volume campus placement drives by sheer scale, with total offers across all programmes regularly reported in the thousands each year. CSE and its AI/ML/Data Science specialisations post the strongest packages; prospective students should review LPU's detailed branch-wise placement reports rather than headline aggregate figures, which blend a very wide range of outcomes given the university's scale." },
    { tab: "placements", heading: "Top Recruiters", body: "- Amazon (select high-package roles)\n- TCS, Infosys, Wipro, Accenture, Cognizant, HCL, Capgemini (bulk IT-services hiring — the majority of offers)\n- A large base of regional and mid-size IT/service firms across drives\n- Growing analytics and product-company participation for top CSE performers" },
    { tab: "cutoffs", heading: "Admission Cutoffs (Indicative)", body: "LPU's multiple admission routes mean there is no single uniform cutoff. For the JEE Main route, CSE admissions have typically required a percentile in the 70-85 range in recent years; for LPUNEST, cutoffs are set relative to the year's applicant pool and directly determine scholarship tier. These are indicative — confirm current-year cutoffs with LPU admissions." },
    { tab: "scholarships", heading: "Scholarships & Financial Aid", body: "- LPUNEST-linked scholarships from 25% to 100% tuition waiver based on rank/score\n- Continuing merit scholarships tied to semester CGPA\n- Sports and extracurricular-achievement scholarships\n- Need-based financial assistance and education-loan facilitation cell" },
    { tab: "rankings", heading: "NIRF & Other Rankings", body: "LPU is ranked #50 in NIRF 2024 Engineering and also features prominently in NIRF's Overall University and Innovation categories, reflecting its rapid growth since 2005 into one of India's largest private universities." },
    { tab: "hostel", heading: "Hostel & Campus Life", body: "LPU offers extensive on-campus hostel accommodation across numerous blocks for men and women, given its very large enrolment. Campus life is correspondingly large-scale — LPU hosts a massive annual cultural fest, one of India's biggest university sports meets, and hundreds of active student clubs and societies across its many schools." },
  ],
};

export const engBatch4: CollegeContentPack[] = [
  upes,
  mnitJaipur,
  nitDurgapur,
  nitDelhi,
  ssnCollege,
  iiitHyderabad,
  bitMesra,
  iiestShibpur,
  lpu,
];
