import type { CollegeContentPack } from "./types";

// Online-degree content packs — flagship "ultra-rich" tier (exceeds the 31-section
// IIT Madras benchmark). Uses two online-specific tabs — "recognition" and
// "learning" — in place of the campus-only "cutoffs" and "hostel" tabs.
// Batch 1, part 1: Manipal University Jaipur (Online) — the locked template.

const manipalJaipurOnline: CollegeContentPack = {
  slug: "manipal-university-jaipur-online",
  college: {
    estd: 2011,
    website: "https://online.manipal.edu",
    feesNum: 150000,
    feesLabel: "₹1.5 L – ₹1.75 L (Online MBA, total)",
    packageLabel: "Career support via Online Manipal placement cell",
    affiliation: "Manipal University Jaipur (UGC-recognised, part of Manipal Education & Medical Group)",
    approvedBy: "UGC-DEB entitled; NAAC A+ accredited; AICTE-approved (relevant programmes); WES-recognised",
    metaTitle: "Manipal University Jaipur (Online) 2026 — Fees, Online MBA, Admission, UGC-DEB Recognition",
    metaDescription:
      "Manipal University Jaipur (Online) via Online Manipal: online MBA/MCA/BBA/BCA/BA/M.Com fees, admission, UGC-DEB entitlement, NAAC A+ accreditation, WES recognition, LMS, exams and placement support.",
    about:
      "Manipal University Jaipur (Online), delivered through the Online Manipal platform, offers UGC-entitled online degree programmes from a NAAC A+ accredited university under the Manipal Education & Medical Group. Its online MBA is among the most recognised in India, aimed at working professionals and recent graduates who need a fully online, flexible degree with the same academic value as an on-campus degree.",
  },
  courses: [
    { name: "Online MBA (Master of Business Administration)", duration: "2 years (4 semesters)", seats: "No fixed cap (online)", feesLabel: "₹1.5 L – ₹1.75 L total (indicative)" },
    { name: "Online MCA (Master of Computer Applications)", duration: "2 years (4 semesters)", seats: "No fixed cap (online)", feesLabel: "₹1.4 L – ₹1.6 L total (indicative)" },
    { name: "Online M.Com", duration: "2 years (4 semesters)", seats: "No fixed cap (online)", feesLabel: "₹0.9 L – ₹1.1 L total (indicative)" },
    { name: "Online BBA", duration: "3 years (6 semesters)", seats: "No fixed cap (online)", feesLabel: "₹1.3 L – ₹1.5 L total (indicative)" },
    { name: "Online BCA", duration: "3 years (6 semesters)", seats: "No fixed cap (online)", feesLabel: "₹1.3 L – ₹1.5 L total (indicative)" },
    { name: "Online B.Com / BA", duration: "3 years (6 semesters)", seats: "No fixed cap (online)", feesLabel: "₹0.75 L – ₹1.0 L total (indicative)" },
  ],
  highlights: [
    "NAAC A+ accredited university (Manipal University Jaipur), UGC-entitled online degrees",
    "Online MBA is among the most recognised online MBAs in India",
    "Fully online delivery via the Online Manipal LMS — live + recorded classes",
    "Degree carries the same academic value as an on-campus Manipal degree (UGC 2020 norms)",
    "WES-recognised — supports higher study and jobs abroad",
    "Two intakes a year (typically January and July); no entrance exam for most programmes",
    "Dedicated placement & career-support cell for online learners",
    "EMI and no-cost financing options on programme fees",
  ],
  faqs: [
    { question: "Is the Manipal University Jaipur online degree valid?", answer: "Yes. Online programmes from Manipal University Jaipur are entitled by the UGC's Distance Education Bureau (UGC-DEB), and under the UGC's 2020 regulations an online degree from an entitled university holds the same academic value as the equivalent on-campus degree — valid for jobs, government exams and higher education." },
    { question: "Is the Online Manipal MBA good for working professionals?", answer: "Yes. The online MBA is designed for flexibility — recorded and live classes, remote-proctored exams and a mobile-friendly LMS — so working professionals can study without career breaks while earning a recognised master's degree." },
    { question: "Is the online degree recognised abroad?", answer: "Manipal University Jaipur is WES-recognised, which supports credential evaluation for higher study and employment in countries such as Canada and the US. Always confirm specific-country/employer requirements before applying abroad." },
    { question: "Does an online degree from Manipal appear as 'online' on the certificate?", answer: "The degree is awarded by Manipal University Jaipur. Under UGC norms an online-mode degree is equivalent to the on-campus degree; confirm the exact wording of the current-year certificate directly with Online Manipal admissions." },
  ],
  sections: [
    // ── INFO ────────────────────────────────────────────────
    { tab: "info", heading: "About Manipal University Jaipur (Online)", body: "Manipal University Jaipur (Online) delivers fully online degree programmes through **Online Manipal**, the digital-learning platform of the Manipal Education & Medical Group (MEMG) — one of India's most established private higher-education groups. Manipal University Jaipur is a UGC-recognised, **NAAC A+ accredited** university, and its online programmes are entitled by the **UGC Distance Education Bureau (UGC-DEB)**.\n\nThe online portfolio spans postgraduate programmes (MBA, MCA, M.Com, MA) and undergraduate programmes (BBA, BCA, B.Com, BA), designed primarily for **working professionals and recent graduates** who need a recognised, flexible degree without attending campus. The online MBA in particular is widely regarded as one of the strongest online MBAs in India." },
    { tab: "info", heading: "Quick Facts & Snapshot", body: "| Attribute | Detail |\n|---|---|\n| Delivery platform | Online Manipal |\n| Parent university | Manipal University Jaipur |\n| Group | Manipal Education & Medical Group (MEMG) |\n| Accreditation | NAAC A+ (university) |\n| Online entitlement | UGC-DEB entitled |\n| International recognition | WES-recognised |\n| Mode | 100% online (live + recorded) |\n| Intakes | Typically January & July |\n| Entrance exam | Not required for most programmes |\n| Flagship programme | Online MBA |\n\nAll figures should be confirmed against the current-year prospectus on the Online Manipal website." },
    { tab: "info", heading: "Why Choose Manipal University Jaipur Online", body: "- **Brand & accreditation:** a NAAC A+ university under the trusted Manipal name\n- **Recognition:** UGC-DEB entitled online degrees with the same academic value as on-campus degrees\n- **Flagship online MBA:** consistently rated among India's leading online MBAs\n- **Flexibility:** recorded lectures, live classes and remote-proctored exams designed around a working schedule\n- **Global mobility:** WES recognition supports study/work abroad\n- **Support:** dedicated enrolment advisors, academic mentors and a placement cell for online learners\n- **Affordability:** competitive fees with EMI and no-cost financing" },
    { tab: "info", heading: "Who These Online Programmes Are For", body: "Online Manipal's Manipal University Jaipur programmes are built for:\n\n- **Working professionals** seeking a career upgrade (MBA/MCA) without a career break\n- **Recent graduates** who want a recognised degree with maximum flexibility\n- **Career switchers** moving into management, analytics, IT or finance\n- **Homemakers and remote learners** who cannot relocate or attend a physical campus\n- **International/NRI learners** who want an Indian degree recognised for further study abroad\n\nBecause classes are recorded and exams are remote-proctored, learners can study from anywhere in India or overseas." },
    { tab: "info", heading: "Online vs Distance vs On-Campus: What's the Difference?", body: "| Feature | On-campus (regular) | Distance (correspondence) | Online (this programme) |\n|---|---|---|---|\n| Attendance | Physical, daily | Self-study + few contact classes | Fully online, live + recorded |\n| Flexibility | Low | Medium | High |\n| Exams | On-campus | Exam centre | Remote-proctored (from home) |\n| Recognition | UGC | UGC-DEB | UGC-DEB (equivalent value) |\n| Best for | Full-time students | Self-paced learners | Working professionals |\n\nUnder UGC's 2020 regulations, an online degree from a UGC-entitled university carries the **same academic value** as the corresponding on-campus degree." },

    // ── COURSES & FEES ──────────────────────────────────────
    { tab: "courses-fees", heading: "Online Programmes Offered", body: "| Programme | Level | Duration | Indicative Total Fee |\n|---|---|---|---|\n| Online MBA | PG | 2 years | ₹1.5 L – ₹1.75 L |\n| Online MCA | PG | 2 years | ₹1.4 L – ₹1.6 L |\n| Online M.Com | PG | 2 years | ₹0.9 L – ₹1.1 L |\n| Online MA (e.g. English/JMC) | PG | 2 years | ₹0.9 L – ₹1.1 L |\n| Online BBA | UG | 3 years | ₹1.3 L – ₹1.5 L |\n| Online BCA | UG | 3 years | ₹1.3 L – ₹1.5 L |\n| Online B.Com | UG | 3 years | ₹0.75 L – ₹1.0 L |\n| Online BA | UG | 3 years | ₹0.75 L – ₹1.0 L |\n\nAll fees are indicative and vary by intake, specialisation and any running offers; confirm the exact current-year fee on the Online Manipal website." },
    { tab: "courses-fees", heading: "Online MBA — Specialisations", body: "The Online MBA is the flagship programme, typically offering a broad set of specialisations that a working professional can align to their career path:\n\n- Marketing\n- Finance\n- Human Resource Management\n- Information Systems / IT & FinTech\n- Operations Management\n- Analytics & Data Science\n- BFSI (Banking, Financial Services & Insurance)\n- Retail / International Business (where offered)\n\nSpecialisation availability changes by intake — check the live list before enrolling. The MBA is delivered over 4 semesters with a mix of live sessions, recorded lectures, assignments and remote-proctored exams." },
    { tab: "courses-fees", heading: "Technology Programmes — Online MCA & BCA", body: "For IT and computing careers, Online Manipal offers **MCA** (PG) and **BCA** (UG) from Manipal University Jaipur:\n\n- **Online MCA (2 yrs):** advanced software development, data structures, cloud, analytics and a capstone project — suited to graduates targeting software/IT roles or a step up from BCA.\n- **Online BCA (3 yrs):** foundational programming, databases, web and application development — a recognised entry route into IT for 10+2 learners.\n\nBoth are UGC-entitled and delivered fully online with the same LMS, mentorship and exam model as the other programmes." },
    { tab: "courses-fees", heading: "Undergraduate Programmes — BBA, B.Com & BA", body: "Undergraduate options let 10+2 learners earn a recognised degree online:\n\n- **Online BBA (3 yrs):** management foundations, marketing, finance, HR and business analytics — a strong base for an MBA later.\n- **Online B.Com (3 yrs):** accounting, taxation, corporate finance and commerce — useful for finance/accounting careers and professional exams (CA/CS/CMA aspirants).\n- **Online BA (3 yrs):** liberal-arts/communication tracks depending on the intake.\n\nUG programmes are the most affordable tier and share the same accreditation and delivery model." },
    { tab: "courses-fees", heading: "Fee Structure, Semester Payment & EMI", body: "Fees are typically charged **per semester**, which spreads the cost across the programme:\n\n| Programme | Approx. per-semester fee | Semesters |\n|---|---|---|\n| Online MBA | ₹37,500 – ₹44,000 | 4 |\n| Online MCA | ₹35,000 – ₹40,000 | 4 |\n| Online BBA/BCA | ₹22,000 – ₹25,000 | 6 |\n| Online B.Com/BA | ₹12,500 – ₹17,000 | 6 |\n\nAll figures are indicative. Online Manipal usually offers **no-cost EMI** and third-party education-loan tie-ups so fees can be paid monthly. Confirm the exact schedule, EMI plans and any scholarship-adjusted fee at the time of admission." },

    // ── ADMISSIONS ──────────────────────────────────────────
    { tab: "admissions", heading: "Eligibility Criteria", body: "Eligibility depends on the programme level:\n\n- **PG (MBA/MCA/M.Com/MA):** a bachelor's degree (typically 3–4 years) from a recognised university with the minimum aggregate specified for the programme (commonly ~50%, relaxed for reserved categories). MCA usually expects mathematics/computing background as per the current norms.\n- **UG (BBA/BCA/B.Com/BA):** 10+2 (or equivalent) from a recognised board with the minimum aggregate specified.\n\nThere is **no national entrance exam** requirement for most programmes; admission is based on meeting the eligibility criteria. Always verify the current-year eligibility on the Online Manipal site." },
    { tab: "admissions", heading: "Admission Process — Step by Step", body: "1. **Register** on the Online Manipal website with your basic details.\n2. **Choose** your programme and specialisation.\n3. **Fill the application** and upload the required documents.\n4. **Pay** the application/enrolment fee (and first-semester fee or EMI setup).\n5. **Document verification** by the admissions team.\n6. **Confirmation & LMS access** — you receive your enrolment confirmation and login to the Online Manipal learning platform.\n\nAn enrolment advisor is typically assigned to guide you through specialisation choice, financing and onboarding." },
    { tab: "admissions", heading: "Intake Sessions & Key Dates", body: "Online Manipal generally runs **two intakes per year**:\n\n| Intake | Typical application window | Classes begin |\n|---|---|---|\n| January session | Oct – Jan | January |\n| July session | Apr – Jul | July |\n\nExact dates shift each year and applications often close in waves as batches fill. Apply early in the window to secure your preferred specialisation and any early-bird scholarship. Confirm the live calendar on the Online Manipal website." },
    { tab: "admissions", heading: "Documents Required", body: "Keep scanned copies ready for a smooth application:\n\n- Class 10 & 12 mark sheets/certificates\n- Graduation mark sheets & degree certificate (for PG programmes)\n- Government photo ID (Aadhaar/PAN/passport)\n- Passport-size photograph\n- Category/reservation certificate (if claiming a category benefit)\n- Work-experience proof (optional, useful for some scholarships/waivers)\n\nDocuments are uploaded during the online application and verified by the admissions team before enrolment is confirmed." },

    // ── APPROVALS & RECOGNITION (online-specific) ───────────
    { tab: "recognition", heading: "UGC-DEB Entitlement & Online Degree Validity", body: "Manipal University Jaipur's online programmes are **entitled by the University Grants Commission's Distance Education Bureau (UGC-DEB)** to be offered in online mode. Under the **UGC (Open and Distance Learning Programmes and Online Programmes) Regulations, 2020**, a degree awarded in online mode by an entitled university holds the **same academic value** as the corresponding degree awarded in conventional (on-campus) mode.\n\nIn practical terms this means the online degree is a bona fide university degree — not a 'certificate' or 'diploma' substitute — and can be used for employment, competitive/government examinations and further study, subject to the specific eligibility rules of each employer or exam." },
    { tab: "recognition", heading: "Accreditations & Approvals", body: "| Body | Status | What it means |\n|---|---|---|\n| NAAC | A+ (Manipal University Jaipur) | Independent quality accreditation of the university |\n| UGC | Recognised university; UGC-DEB entitled | Degrees are UGC-recognised; online mode is entitled |\n| AICTE | Approval for relevant programmes | Technical/management programme approval where applicable |\n| WES | Recognised | Supports credential evaluation abroad |\n\nAccreditation status can be revised over time — confirm the current NAAC grade and entitlement year on the university/UGC websites before enrolling." },
    { tab: "recognition", heading: "Degree Equivalence — Online Equals On-Campus", body: "A common concern is whether an online degree is 'lesser' than a campus degree. The regulatory position is clear:\n\n- The UGC's 2020 regulations explicitly establish **equivalence** between online-mode and on-campus degrees from entitled institutions.\n- The degree is awarded by **Manipal University Jaipur**, the same degree-awarding university.\n\nThat said, the **learning experience** differs (self-paced, online), and some employers or foreign universities may ask for details of the mode. The academic value and eligibility, however, are treated on par with the regular degree under Indian regulations." },
    { tab: "recognition", heading: "International Recognition (WES & Study Abroad)", body: "Manipal University Jaipur is **WES-recognised**. World Education Services (WES) is a widely used credential-evaluation body in **Canada and the United States**, so a WES-evaluated Manipal degree can support:\n\n- Applications to **master's/PhD programmes** abroad\n- **Skilled-immigration** credential assessments (e.g. Canada Express Entry)\n- **Employment** where a foreign-credential evaluation is required\n\nRecognition of any online degree still depends on the **specific university, employer or immigration authority** — always confirm their acceptance of online-mode degrees and the exact evaluation they require before applying." },
    { tab: "recognition", heading: "Is the Degree Valid for Government Jobs & Higher Study?", body: "- **Government jobs & exams:** UGC-entitled online degrees are generally accepted for eligibility, but individual recruiters/commissions (UPSC, SSC, state PSCs, banks) set their own conditions — verify the specific notification's wording on distance/online degrees.\n- **Higher study (e.g. MBA after BBA, PhD after PG):** the degree is valid for further study at recognised institutions; some competitive/foreign programmes may have additional criteria.\n- **Professional progression:** widely accepted by private employers for promotions, role changes and salary bands that require a recognised degree.\n\nWhen a specific eligibility rule matters to you, confirm it in writing with that employer/authority before enrolling." },

    // ── LEARNING EXPERIENCE (online-specific) ───────────────
    { tab: "learning", heading: "The Online Manipal Learning Platform (LMS)", body: "All teaching, content and assessment run through the **Online Manipal LMS**, accessible via web and a mobile app. A typical learner dashboard brings together:\n\n- **Recorded lectures** for every module (watch anytime, any device)\n- **Live/interactive sessions** with faculty on a schedule\n- **E-learning content** — reading material, presentations and reference resources\n- **Assignments, quizzes and discussion forums**\n- **Exam scheduling and results**\n\nBecause content is recorded and downloadable within the app, learners can study offline and revisit lectures before exams — key for working professionals with irregular hours." },
    { tab: "learning", heading: "Live Classes, Recorded Lectures & Study Material", body: "The programme blends **synchronous** and **asynchronous** learning:\n\n- **Recorded video lectures** cover the full syllabus and are the backbone of the course — ideal for self-paced study.\n- **Live online classes** add real-time interaction, doubt-solving and industry context.\n- **Curated e-content** (readings, case studies, slide decks) supports each module.\n- **Access to Online Manipal's digital library and resources** for research and assignments.\n\nThis structure lets a learner keep pace even if they miss a live session, since everything is available on-demand in the LMS." },
    { tab: "learning", heading: "Examination Pattern — Remote-Proctored Exams", body: "End-of-semester examinations are conducted through **remote proctoring**, so learners can appear **from home**:\n\n- Exams are taken online at a scheduled time, monitored by AI/human proctoring via webcam.\n- A stable internet connection, a webcam-enabled device and a quiet space are required.\n- Assessment typically combines **internal assessment** (assignments/quizzes) with the **proctored semester exam**.\n\nThis removes the need to travel to a physical exam centre — one of the biggest practical advantages of the online mode for working professionals and remote learners." },
    { tab: "learning", heading: "Mentorship, Doubt-Solving & Student Support", body: "Online learners get structured support so they are not studying in isolation:\n\n- **Academic mentors / programme coordinators** to guide progress\n- **Doubt-clearing sessions** and discussion forums with faculty and peers\n- **Enrolment & success advisors** for administrative help (fees, exams, documents)\n- **Peer community** across the online cohort for networking\n- **Technical support** for LMS/app issues\n\nThe combination of mentorship plus an always-on LMS is designed to keep completion rates high despite the flexibility of online study." },
    { tab: "learning", heading: "Flexibility, Duration & Mobile Learning", body: "The online model is built around a **working schedule**:\n\n- **Study anytime, anywhere** via the mobile app and web LMS\n- **No relocation, no daily commute** — attend from any city or country\n- **Recorded content** means you set your own study rhythm\n- **Standard duration** — 2 years (PG) / 3 years (UG), same as on-campus\n\nFor most learners the biggest benefit is being able to **upskill without a career break**, applying new learning directly at work while the degree is in progress." },

    // ── PLACEMENTS ──────────────────────────────────────────
    { tab: "placements", heading: "Career Support for Online Learners", body: "Online Manipal provides a **dedicated career-support / placement cell** for online-degree learners — distinct from a traditional campus placement drive. Typical services include:\n\n- **Resume and LinkedIn profile building**\n- **Interview preparation** and soft-skills training\n- **Access to a jobs/opportunities portal** with partner employers\n- **Virtual placement drives and webinars**\n- **Career counselling** aligned to the learner's specialisation\n\nBecause many online learners are **already employed**, the emphasis is on **career advancement, role change and salary progression** rather than a first job." },
    { tab: "placements", heading: "Career Outcomes & Recruiter Ecosystem", body: "Outcomes vary widely because online cohorts mix fresh graduates and experienced professionals. Reported outcomes for Online Manipal learners commonly include:\n\n- **Promotions and role upgrades** within the learner's current organisation\n- **Switches into management, analytics, IT and BFSI roles**\n- **Participation in virtual placement drives** with the platform's hiring partners\n\nOnline Manipal markets a large network of hiring partners across sectors. Specific packages depend heavily on the individual's prior experience and specialisation, so treat any single 'average package' figure as **indicative** and confirm current placement statistics directly with Online Manipal." },
    { tab: "placements", heading: "Value for Working Professionals", body: "For someone already working, the placement value of an online MBA/MCA is best measured as **return on career**, not a campus package:\n\n- **Eligibility unlock:** many mid/senior roles and salary bands require a recognised master's degree — the online MBA fulfils that without a career break.\n- **Skill-to-job transfer:** learners apply coursework (analytics, finance, management) directly at work, often accelerating promotions.\n- **Network & brand:** the Manipal name and alumni network add credibility on a CV.\n\nThis is the core reason working professionals choose a recognised online degree over a full-time programme." },
    { tab: "placements", heading: "Industry Projects & Applied Learning", body: "The programmes embed **applied, industry-relevant work** so learning translates into employability:\n\n- **Capstone / project work** (especially in MBA and MCA)\n- **Case-study-driven assessments** reflecting real business/technology problems\n- **Guest sessions and webinars** with industry practitioners\n- **Specialisation electives** aligned to in-demand roles (analytics, BFSI, IT)\n\nWhile online programmes don't include a traditional in-person internship, the project and case-study components are designed to build a portfolio a learner can showcase to employers." },

    // ── SCHOLARSHIPS ────────────────────────────────────────
    { tab: "scholarships", heading: "Scholarships & Fee Concessions", body: "Online Manipal periodically offers **scholarships and fee concessions** that reduce the effective programme cost. Commonly available categories include:\n\n- **Merit-based** concessions for strong academic records\n- **Early-bird** discounts for applying early in an intake\n- **Defence personnel & their dependents**\n- **Divyang (persons with disability)** concessions\n- **Alumni** benefits (for Manipal-group alumni)\n\nScholarship availability and percentages change by intake and cannot be combined unless stated. Confirm the live scholarship list and eligibility with your enrolment advisor before paying fees." },
    { tab: "scholarships", heading: "EMI & Education-Loan Options", body: "To make fees manageable, Online Manipal typically supports:\n\n- **No-cost / low-cost EMI** on programme fees via financing partners\n- **Third-party education loans** through NBFC/bank tie-ups\n- **Semester-wise payment**, which naturally spreads the cost\n\nEMI plans let learners pay monthly instead of a large upfront amount — particularly useful for working professionals self-funding the degree. Interest terms depend on the financing partner; review them carefully before signing." },
    { tab: "scholarships", heading: "Who Should Ask About a Waiver", body: "You should specifically ask your enrolment advisor about concessions if you are:\n\n- A **defence-services** member or dependent\n- A **person with a disability (Divyang)**\n- A **Manipal-group alumnus**\n- Applying **early** in the intake window\n- Able to demonstrate **strong academic merit** or relevant **work experience**\n\nEven a modest percentage waiver on a two- or three-year programme is a meaningful saving, so it's worth confirming eligibility before you lock in your fee plan." },

    // ── RANKINGS ────────────────────────────────────────────
    { tab: "rankings", heading: "Accreditation & Quality Standing", body: "| Marker | Status |\n|---|---|\n| NAAC | A+ (Manipal University Jaipur) |\n| UGC | Recognised university; UGC-DEB entitled online programmes |\n| WES | Recognised (international credential evaluation) |\n| Group | Manipal Education & Medical Group (MEMG) |\n\nFor online degrees, **accreditation and entitlement matter more than a stream rank** — they determine whether the degree is recognised and valued. Manipal University Jaipur's NAAC A+ grade and UGC-DEB entitlement are its core quality signals. Confirm the current NAAC grade and entitlement on the official sites." },
    { tab: "rankings", heading: "Institutional Reputation & Online-MBA Standing", body: "Manipal University Jaipur is a well-established private university, and its parent group (Manipal) is one of the most recognised names in Indian higher education. The **Online Manipal MBA** is frequently cited among the **leading online MBAs in India** in ed-tech and media roundups.\n\nUnlike campus NIRF rankings (which assess physical institutions), online programmes are best judged by **accreditation, entitlement, brand strength and learner outcomes** — areas where Manipal University Jaipur Online scores well. Where a specific ranking or survey position is quoted elsewhere, verify its source and year." },
    { tab: "rankings", heading: "How to Judge an Online University", body: "When comparing online-degree providers, weigh these factors in order:\n\n1. **UGC-DEB entitlement** — non-negotiable for a valid degree\n2. **NAAC / university accreditation** — quality assurance\n3. **Brand and employer recognition** — how the degree reads on a CV\n4. **International recognition (e.g. WES)** — if you may study/work abroad\n5. **LMS quality, mentorship and support** — completion and experience\n6. **Fees, EMI and scholarships** — total cost of the degree\n\nManipal University Jaipur (Online) is positioned strongly on entitlement, accreditation and brand — the factors that most affect the long-term value of an online degree." },
  ],
};

export const onlineBatch1: CollegeContentPack[] = [manipalJaipurOnline];
