/**
 * Seeds the full DCI (Dental Council of India / National Dental Commission)
 * registry of BDS colleges — 330 institutions, sourced from the official
 * dciindia.gov.in college-search database. This is the authoritative national
 * list (vs. NIRF, which only formally ranks the top 40).
 *
 * Skips rows that are the same institution as one already seeded by
 * seed:dental (NIRF top-40), matched by DCI S.No — same college, different
 * naming/spelling on the DCI vs NIRF site.
 *
 *   npm run seed:dental-all -w @collegechoice/api
 */
import * as dotenv from "dotenv";
import path from "node:path";
dotenv.config({ path: path.join(process.cwd(), ".env") });
dotenv.config({ path: path.join(process.cwd(), "../../.env") });

import { PrismaClient } from "@prisma/client";
import { ensureCity, ensureStream, toCollegeType, uniqueCollegeSlug, buildSeoText } from "./normalize";

const prisma = new PrismaClient();

type Row = [no: number, name: string, city: string, state: string, type: "Government" | "Private"];

// Full DCI college-search registry (as of the 2024 snapshot). State names
// normalised (Orissa -> Odisha, Uttrakhand -> Uttarakhand).
const DCI: Row[] = [
  [1, "Anil Neerukonda Institute of Dental Sciences", "Visakhapatnam", "Andhra Pradesh", "Private"],
  [2, "C.K.S. Teja Institute of Dental Sciences & Research", "Tirupati", "Andhra Pradesh", "Private"],
  [3, "Care Dental College", "Guntur", "Andhra Pradesh", "Private"],
  [4, "Drs. Sudha & Nageswara Rao Siddhartha Institute", "Gannavaram", "Andhra Pradesh", "Private"],
  [5, "G. Pulla Reddy Dental College & Hospital", "Kurnool", "Andhra Pradesh", "Private"],
  [6, "Gitam Dental College & Hospital", "Visakhapatnam", "Andhra Pradesh", "Private"],
  [7, "Govt. Dental College & Hospital", "Vijayawada", "Andhra Pradesh", "Government"],
  [8, "Govt. Dental College, RIMS", "Kadapa", "Andhra Pradesh", "Government"],
  [9, "GSL Dental College & Hospital", "Rajahmundry", "Andhra Pradesh", "Private"],
  [10, "KIMS Dental College", "Amalapuram", "Andhra Pradesh", "Private"],
  [11, "Lenora Institute of Dental Sciences", "Rajahmundry", "Andhra Pradesh", "Private"],
  [12, "Narayana Dental College & Hospital", "Nellore", "Andhra Pradesh", "Private"],
  [13, "Nimra Institute of Dental Sciences", "Vijayawada", "Andhra Pradesh", "Private"],
  [14, "Sibar Institute of Dental Sciences", "Guntur", "Andhra Pradesh", "Private"],
  [15, "Sree Sai Dental College & Research Institute", "Srikakulam", "Andhra Pradesh", "Private"],
  [16, "St. Joseph Dental College", "Duggirala", "Andhra Pradesh", "Private"],
  [17, "Vishnu Dental College", "Bhimavaram", "Andhra Pradesh", "Private"],
  [18, "Govt. Dental College", "Dibrugarh", "Assam", "Government"],
  [19, "Govt. Dental College", "Silchar", "Assam", "Government"],
  [20, "Regional Dental College", "Guwahati", "Assam", "Government"],
  [21, "Buddha Institute of Dental Sciences & Hospital", "Patna", "Bihar", "Private"],
  [22, "Government Dental College & Hospital", "Nalanda", "Bihar", "Government"],
  [23, "Mithila Minority Dental College & Hospital", "Darbhanga", "Bihar", "Private"],
  [24, "Patna Dental College & Hospital", "Patna", "Bihar", "Government"],
  [25, "Sarjug Dental College", "Darbhanga", "Bihar", "Private"],
  [27, "Chattisgarh Dental College & Research Institute", "Rajnandgaon", "Chhattisgarh", "Private"],
  [28, "Govt. Dental College", "Raipur", "Chhattisgarh", "Government"],
  [29, "Maitri College of Dentistry", "Durg", "Chhattisgarh", "Private"],
  [30, "New Horizon Dental College & Research Institute", "Bilaspur", "Chhattisgarh", "Private"],
  [31, "Rungta College of Dental Sciences & Research", "Bhilai", "Chhattisgarh", "Private"],
  [32, "Shri Balaji Institute of Dental Sciences", "Raipur", "Chhattisgarh", "Private"],
  [33, "Triveni Institute of Dental Sciences", "Bilaspur", "Chhattisgarh", "Private"],
  [34, "Vaidik Dental College and Research Centre", "Daman", "Daman and Diu", "Private"],
  [35, "Army Hospital (Research and Referral)", "Delhi Cantt", "Delhi", "Government"],
  [36, "ESIC Dental College", "Rohini", "Delhi", "Government"],
  [38, "Lady Hardinge Medical College & Hospital", "New Delhi", "Delhi", "Government"],
  [40, "University College of Medical Sciences", "Dilshad Garden", "Delhi", "Government"],
  [41, "Goa Dental College & Hospital", "Panaji", "Goa", "Government"],
  [42, "Ahmedabad Dental College & Hospital", "Gandhinagar", "Gujarat", "Private"],
  [43, "AMC Dental College", "Ahmedabad", "Gujarat", "Government"],
  [44, "College of Dental Sciences and Research Centre", "Ahmedabad", "Gujarat", "Private"],
  [45, "College of Dental Sciences", "Amargadh", "Gujarat", "Private"],
  [46, "Faculty of Dental Science, Dharmsinh Desai University", "Nadiad", "Gujarat", "Private"],
  [47, "Goenka Research Institute of Dental Sciences", "Gandhinagar", "Gujarat", "Private"],
  [49, "Govt. Dental College Hospital", "Jamnagar", "Gujarat", "Government"],
  [50, "K.M. Shah Dental College & Hospital", "Vadodara", "Gujarat", "Private"],
  [51, "Karnavati School of Dentistry", "Gandhinagar", "Gujarat", "Private"],
  [52, "Manubhai Patel Dental College & Hospital", "Vadodara", "Gujarat", "Private"],
  [53, "Narsinhbhai Patel Dental College & Hospital", "Visnagar", "Gujarat", "Private"],
  [54, "Siddhpur Dental College", "Patan", "Gujarat", "Government"],
  [55, "D.A.V. Centenary Dental College", "Yamuna Nagar", "Haryana", "Private"],
  [56, "Jan Nayak Ch. Devi Lal Dental College", "Sirsa", "Haryana", "Private"],
  [57, "Maharishi Markandeshwar College", "Mullana", "Haryana", "Private"],
  [59, "PDM Dental College & Research Institute", "Jhajjar", "Haryana", "Private"],
  [61, "Sri Govind Tricentenary Dental College", "Gurugram", "Haryana", "Private"],
  [62, "Sudha Rustagi College of Dental Sciences", "Faridabad", "Haryana", "Private"],
  [63, "Swami Devi Dyal Hospital & Dental College", "Panchkula", "Haryana", "Private"],
  [64, "Yamuna Institute of Dental Sciences & Research", "Yamuna Nagar", "Haryana", "Private"],
  [65, "Bhojia Dental College & Hospital", "Nalagarh", "Himachal Pradesh", "Private"],
  [66, "H.P. Govt. Dental College & Hospital", "Shimla", "Himachal Pradesh", "Government"],
  [67, "Himachal Dental College", "Sunder Nagar", "Himachal Pradesh", "Private"],
  [68, "Himachal Institute of Dental Sciences", "Poanta Sahib", "Himachal Pradesh", "Private"],
  [69, "M.N.D.A.V. Dental College & Hospital", "Solan", "Himachal Pradesh", "Private"],
  [70, "Govt. Dental College", "Srinagar", "Jammu and Kashmir", "Government"],
  [71, "Indira Gandhi Government Dental College", "Jammu", "Jammu and Kashmir", "Government"],
  [72, "Institute of Dental Sciences", "Sehora", "Jammu and Kashmir", "Private"],
  [73, "Awadh Dental College & Hospital", "Jamshedpur", "Jharkhand", "Private"],
  [74, "Dental Institute Rajendra Institute", "Ranchi", "Jharkhand", "Government"],
  [75, "Hazaribag College of Dental Sciences", "Hazaribag", "Jharkhand", "Private"],
  [76, "Vananchal Dental College & Hospital", "Garhwa", "Jharkhand", "Private"],
  [78, "A.J. Institute of Dental Sciences", "Mangaluru", "Karnataka", "Private"],
  [79, "Al Ameen Dental College & Hospital", "Bijapur", "Karnataka", "Private"],
  [80, "Al-Badar Rural Dental College & Hospital", "Gulbarga", "Karnataka", "Private"],
  [81, "AME's Dental College & Hospital", "Raichur", "Karnataka", "Private"],
  [82, "Bangalore Institute of Dental Sciences & Hospital", "Bengaluru", "Karnataka", "Private"],
  [84, "BGS Global Institute of Dental Sciences", "Bengaluru", "Karnataka", "Private"],
  [85, "College of Dental Sciences and Research Centre", "Davangere", "Karnataka", "Private"],
  [86, "Coorg Institute of Dental Sciences", "Virajpet", "Karnataka", "Private"],
  [87, "D.A. Pandu Memorial R.V. Dental College", "Bengaluru", "Karnataka", "Private"],
  [88, "Dayanand Sagar College of Dental Sciences", "Bengaluru", "Karnataka", "Private"],
  [89, "Dr. Syamala Reddy Dental College", "Bengaluru", "Karnataka", "Private"],
  [90, "ESIC Dental College", "Gulbarga", "Karnataka", "Government"],
  [91, "Farooqia Dental College & Hospital", "Mysuru", "Karnataka", "Private"],
  [92, "Govt. Dental College & Research Institute", "Bellary", "Karnataka", "Government"],
  [94, "H.K.D.E.Ts Dental College", "Humnabad", "Karnataka", "Private"],
  [95, "H.K.E. Society's Institute of Dental Sciences", "Gulbarga", "Karnataka", "Private"],
  [97, "K.G.F. College of Dental Sciences & Hospital", "Kolar Gold Fields", "Karnataka", "Private"],
  [98, "K.V.G. Dental College & Hospital", "Sullia", "Karnataka", "Private"],
  [99, "KLE Society's Institute of Dental Sciences", "Bengaluru", "Karnataka", "Private"],
  [101, "Krishnadevaraya College of Dental Sciences", "Bengaluru", "Karnataka", "Private"],
  [102, "M.R. Ambedkar Dental College & Hospital", "Bengaluru", "Karnataka", "Private"],
  [103, "M.S. Ramaiah Dental College", "Bengaluru", "Karnataka", "Private"],
  [106, "Maratha Mandal's Dental College", "Belagavi", "Karnataka", "Private"],
  [107, "Navodaya Dental College", "Raichur", "Karnataka", "Private"],
  [108, "P.M.N.M. Dental College & Hospital", "Bagalkot", "Karnataka", "Private"],
  [109, "Rajarajeswari Dental College & Hospital", "Bengaluru", "Karnataka", "Private"],
  [110, "S.B. Patil Dental College & Hospital", "Bidar", "Karnataka", "Private"],
  [111, "S.J.M. Dental College & Hospital", "Chitradurga", "Karnataka", "Private"],
  [113, "Sharavathi Dental College & Hospital", "Shivamogga", "Karnataka", "Private"],
  [114, "Sri Hasanamba Dental College & Hospital", "Hassan", "Karnataka", "Private"],
  [115, "Sri Rajiv Gandhi College of Dental Sciences", "Bengaluru", "Karnataka", "Private"],
  [116, "Sri Siddhartha Dental College", "Tumkur", "Karnataka", "Private"],
  [117, "Sri Venkateshwara Dental College & Hospital", "Bengaluru", "Karnataka", "Private"],
  [118, "Srinivas Institute of Dental Sciences", "Mangaluru", "Karnataka", "Private"],
  [119, "Subbaiah Institute of Dental Sciences", "Shivamogga", "Karnataka", "Private"],
  [120, "The Oxford Dental College", "Bengaluru", "Karnataka", "Private"],
  [121, "V.S. Dental College", "Bengaluru", "Karnataka", "Private"],
  [122, "Vydehi Institute of Dental Sciences & Research", "Bengaluru", "Karnataka", "Private"],
  [124, "Al-Azhar Dental College", "Thodupuzha", "Kerala", "Private"],
  [125, "Amrita School of Dentistry", "Kochi", "Kerala", "Private"],
  [126, "Annoor Dental College & Hospital", "Ernakulam", "Kerala", "Private"],
  [127, "Azeezia College of Dental Sciences & Research", "Kollam", "Kerala", "Private"],
  [128, "Century International Institute of Dental Science", "Kasaragod", "Kerala", "Private"],
  [129, "Educare Institute of Dental Sciences", "Malappuram", "Kerala", "Private"],
  [130, "Govt. Dental College", "Alappuzha", "Kerala", "Government"],
  [131, "Govt. Dental College", "Kottayam", "Kerala", "Government"],
  [132, "Govt. Dental College", "Kozhikode", "Kerala", "Government"],
  [133, "Govt. Dental College", "Thrissur", "Kerala", "Government"],
  [135, "Indira Gandhi Institute of Dental Sciences", "Kothamangalam", "Kerala", "Private"],
  [136, "Kannur Dental College", "Kannur", "Kerala", "Private"],
  [137, "KMCT Dental College", "Kozhikode", "Kerala", "Private"],
  [138, "Malabar Dental College & Research Centre", "Malappuram", "Kerala", "Private"],
  [139, "Mar Baselios Dental College", "Kothamangalam", "Kerala", "Private"],
  [140, "MES Dental College", "Malappuram", "Kerala", "Private"],
  [141, "Noorul Islam College of Dental Sciences", "Thiruvananthapuram", "Kerala", "Private"],
  [142, "Pariyaram Dental College", "Kannur", "Kerala", "Government"],
  [143, "PMS College of Dental Science & Research", "Thiruvananthapuram", "Kerala", "Private"],
  [144, "PSM College of Dental Sciences & Research", "Thrissur", "Kerala", "Private"],
  [145, "Pushpagiri College of Dental Sciences", "Tiruvalla", "Kerala", "Private"],
  [146, "Royal Dental College", "Palakkad", "Kerala", "Private"],
  [147, "Sree Anjaneya Medical Trust Dental College", "Kozhikode", "Kerala", "Private"],
  [148, "Sri Sankara Dental College", "Thiruvananthapuram", "Kerala", "Private"],
  [149, "St. Gregorios Dental College", "Ernakulam", "Kerala", "Private"],
  [150, "Travancore Dental College", "Kollam", "Kerala", "Private"],
  [151, "Bhabha College of Dental Sciences", "Bhopal", "Madhya Pradesh", "Private"],
  [152, "College of Dental Sciences & Hospital", "Indore", "Madhya Pradesh", "Private"],
  [153, "College of Dentistry", "Indore", "Madhya Pradesh", "Government"],
  [154, "Guru Gobind Singh College of Dentistry", "Burhanpur", "Madhya Pradesh", "Private"],
  [155, "Hitkarini Dental College & Hospital", "Jabalpur", "Madhya Pradesh", "Private"],
  [156, "Index Institute of Dental Sciences", "Indore", "Madhya Pradesh", "Private"],
  [157, "Maharana Pratap College of Dentistry", "Gwalior", "Madhya Pradesh", "Private"],
  [158, "Mansarover Dental College", "Bhopal", "Madhya Pradesh", "Private"],
  [159, "Modern Dental College & Research Centre", "Indore", "Madhya Pradesh", "Private"],
  [160, "People's Dental Academy", "Bhopal", "Madhya Pradesh", "Private"],
  [161, "Peoples College of Dental Sciences", "Bhopal", "Madhya Pradesh", "Private"],
  [162, "Rishiraj College of Dental Sciences", "Bhopal", "Madhya Pradesh", "Private"],
  [163, "RKDF Dental College & Research Centre", "Bhopal", "Madhya Pradesh", "Private"],
  [164, "Sri Aurobindo College of Dentistry", "Indore", "Madhya Pradesh", "Private"],
  [165, "Aditya Dental College", "Beed", "Maharashtra", "Private"],
  [166, "Annasaheb Chudaman Patil Memorial Dental College", "Dhule", "Maharashtra", "Private"],
  [167, "Armed Forces Medical College", "Pune", "Maharashtra", "Government"],
  [168, "Bharati Vidyapeeth Dental College & Hospital", "Navi Mumbai", "Maharashtra", "Private"],
  [170, "Bharati Vidyapeeth Dental College & Hospital, Sangli", "Sangli", "Maharashtra", "Private"],
  [171, "Chatrapati Shahu Maharaj Dental College", "Aurangabad", "Maharashtra", "Private"],
  [172, "D.Y. Patil Dental School", "Pune", "Maharashtra", "Private"],
  [173, "Dr. D.Y. Patil Dental College & Hospital", "Pune", "Maharashtra", "Private"],
  [174, "Dr. Hedgewar Smruti Rugna Seva Mandals Dental College", "Hingoli", "Maharashtra", "Private"],
  [175, "Dr. Rajesh Ramdasji Kambe Dental College", "Akola", "Maharashtra", "Private"],
  [176, "Govt. Dental College & Hospital", "Aurangabad", "Maharashtra", "Government"],
  [177, "Govt. Dental College & Hospital", "Jalgaon", "Maharashtra", "Government"],
  [180, "Late Shri Yashwantrao Chavan Memorial Dental College", "Ahmednagar", "Maharashtra", "Private"],
  [181, "M.A. Rangoonwala College of Dental Sciences", "Pune", "Maharashtra", "Private"],
  [182, "Maharashtra Institute of Dental Sciences & Research", "Latur", "Maharashtra", "Private"],
  [183, "Mahatma Gandhi Missions Dental College", "Navi Mumbai", "Maharashtra", "Private"],
  [184, "Mahatma Gandhi Vidya Mandir's Dental College", "Nashik", "Maharashtra", "Private"],
  [186, "Nanded Rural Dental College & Research Center", "Nanded", "Maharashtra", "Private"],
  [187, "Padmashree Dr. D.Y. Patil Dental College", "Navi Mumbai", "Maharashtra", "Private"],
  [188, "Pandit Dindayal Upadhyay Dental College", "Solapur", "Maharashtra", "Private"],
  [189, "Ranjeet Deshmukh Dental College", "Nagpur", "Maharashtra", "Private"],
  [190, "Rural Dental College", "Loni", "Maharashtra", "Private"],
  [191, "S.M.B.T. Dental College & Hospital", "Amrutnagar", "Maharashtra", "Private"],
  [192, "Saraswati Danwantri Dental College & Hospital", "Parbhani", "Maharashtra", "Private"],
  [193, "School of Dental Sciences, Krishna Institute", "Karad", "Maharashtra", "Private"],
  [194, "Sharad Pawar Dental College & Hospital", "Wardha", "Maharashtra", "Private"],
  [195, "Sinhgad Dental College & Hospital", "Pune", "Maharashtra", "Private"],
  [196, "SMBT Institute of Dental Sciences & Research", "Nashik", "Maharashtra", "Private"],
  [197, "Swargiya Dadasaheb Kalmegh Smruti Dental College", "Nagpur", "Maharashtra", "Private"],
  [198, "Tatyasaheb Kore Dental College & Research Centre", "New Pargaon", "Maharashtra", "Private"],
  [199, "Terna Dental College & Hospital", "Navi Mumbai", "Maharashtra", "Private"],
  [200, "Vasantdada Patil Dental College and Hospital", "Sangli", "Maharashtra", "Private"],
  [201, "Vidarbha Youth Welfare Society's Dental College", "Amravati", "Maharashtra", "Private"],
  [202, "Yerala Medical Trust Dental College", "Navi Mumbai", "Maharashtra", "Private"],
  [203, "Yogita Dental College & Hospital", "Ratnagiri", "Maharashtra", "Private"],
  [204, "Dental College, Jawaharlal Nehru Institute", "Imphal", "Manipur", "Government"],
  [205, "Dental College, RIMS", "Imphal", "Manipur", "Government"],
  [206, "Hi-Tech Dental College & Hospital", "Bhubaneswar", "Odisha", "Private"],
  [207, "Institute of Dental Sciences", "Bhubaneswar", "Odisha", "Private"],
  [208, "Kalinga Institute of Dental Sciences", "Bhubaneswar", "Odisha", "Private"],
  [209, "S.C.B. Dental College & Hospital", "Cuttack", "Odisha", "Government"],
  [210, "Indira Gandhi Institute of Dental Sciences", "Puducherry", "Pondicherry", "Private"],
  [212, "Mahe Institute of Dental Sciences & Hospital", "Mahe", "Pondicherry", "Private"],
  [213, "Sri Venkateshwaraa Dental College", "Puducherry", "Pondicherry", "Private"],
  [214, "Adesh Institute of Dental Sciences & Research", "Bathinda", "Punjab", "Private"],
  [215, "Baba Jaswant Singh Dental College Hospital", "Ludhiana", "Punjab", "Private"],
  [217, "Dasmesh Institute of Research & Dental Sciences", "Faridkot", "Punjab", "Private"],
  [218, "Desh Bhagat Dental College & Hospital", "Mandi Gobindgarh", "Punjab", "Private"],
  [219, "Genesis Institute of Dental Sciences & Research", "Ferozepur", "Punjab", "Private"],
  [220, "Gian Sagar Dental College & Hospital", "Rajpura", "Punjab", "Private"],
  [222, "Guru Nanak Dev Dental College & Research", "Sunam", "Punjab", "Private"],
  [223, "Luxmi Bai Institute of Dental Sciences", "Patiala", "Punjab", "Private"],
  [224, "National Dental College & Hospital", "Gulabgarh", "Punjab", "Private"],
  [225, "Pb. Govt. Dental College & Hospital", "Amritsar", "Punjab", "Government"],
  [226, "Rayat Bahra Dental College", "Mohali", "Punjab", "Private"],
  [227, "Shaheed Kartar Singh Sarabha Dental College", "Ludhiana", "Punjab", "Private"],
  [228, "Sri Guru Ram Das Institute of Dental Sciences", "Amritsar", "Punjab", "Private"],
  [229, "Sukhmani Dental College & Hospital", "Derabassi", "Punjab", "Private"],
  [230, "Darshan Dental College & Hospital", "Udaipur", "Rajasthan", "Private"],
  [231, "Daswani Dental College & Research Centre", "Kota", "Rajasthan", "Private"],
  [232, "Dr. S. S. Tantia Dental College", "Sri Ganganagar", "Rajasthan", "Private"],
  [233, "Eklavya Dental College & Hospital", "Kotputli", "Rajasthan", "Private"],
  [234, "Geetanjali Dental & Research Institute", "Udaipur", "Rajasthan", "Private"],
  [235, "Government Dental College", "Jodhpur", "Rajasthan", "Government"],
  [236, "Govt. Dental College & Hospital", "Jaipur", "Rajasthan", "Government"],
  [237, "Jaipur Dental College", "Jaipur", "Rajasthan", "Private"],
  [238, "Jodhpur Dental College General Hospital", "Jodhpur", "Rajasthan", "Private"],
  [239, "Maharaja Ganga Singh Dental College", "Sri Ganganagar", "Rajasthan", "Private"],
  [240, "Mahatma Gandhi Dental College & Hospital", "Jaipur", "Rajasthan", "Private"],
  [241, "NIMS Dental College", "Jaipur", "Rajasthan", "Private"],
  [242, "Pacific Dental College & Research Centre", "Udaipur", "Rajasthan", "Private"],
  [244, "R.R. Dental College & Hospital", "Udaipur", "Rajasthan", "Private"],
  [245, "Rajasthan Dental College & Hospital", "Jaipur", "Rajasthan", "Private"],
  [246, "Surendera Dental College & Research Institute", "Sri Ganganagar", "Rajasthan", "Private"],
  [247, "Vyas Dental College & Hospital", "Jodhpur", "Rajasthan", "Private"],
  [249, "Asan Memorial Dental College & Hospital", "Kancheepuram", "Tamil Nadu", "Private"],
  [250, "Best Dental Science College", "Madurai", "Tamil Nadu", "Private"],
  [252, "CSI College of Dental Sciences & Research", "Madurai", "Tamil Nadu", "Private"],
  [253, "Dhanalakshmi Srinivasan Dental College", "Perambalur", "Tamil Nadu", "Private"],
  [254, "Government Dental College", "Pudukkottai", "Tamil Nadu", "Government"],
  [255, "Govt. Dental College & Hospital", "Cuddalore", "Tamil Nadu", "Government"],
  [256, "JKK Natrajah Dental College & Hospital", "Komarapalayam", "Tamil Nadu", "Private"],
  [257, "K.S.R. Institute of Dental Science & Research", "Tiruchengode", "Tamil Nadu", "Private"],
  [258, "Karpaga Vinayaga Institute of Dental Sciences", "Kanchipuram", "Tamil Nadu", "Private"],
  [259, "Madha Dental College & Hospital", "Kundrathur", "Tamil Nadu", "Private"],
  [260, "Meenakshi Ammal Dental College & Hospital", "Chennai", "Tamil Nadu", "Private"],
  [261, "Nandha Dental College and Hospital", "Erode", "Tamil Nadu", "Private"],
  [262, "Priyadarshini Dental College & Hospital", "Pandur", "Tamil Nadu", "Private"],
  [263, "R.V.S. Dental College & Hospital", "Sulur", "Tamil Nadu", "Private"],
  [264, "Ragas Dental College & Hospital", "Chennai", "Tamil Nadu", "Private"],
  [265, "Rajas Dental College & Hospital", "Kavalkinaru", "Tamil Nadu", "Private"],
  [267, "Sathyabama University Dental College", "Chennai", "Tamil Nadu", "Private"],
  [269, "Sree Balaji Dental College & Hospital", "Narayanpuram", "Tamil Nadu", "Private"],
  [270, "Sree Mookambika Institute of Dental Sciences", "Kulasekharam", "Tamil Nadu", "Private"],
  [272, "Sri Ramakrishna Dental College & Hospital", "Coimbatore", "Tamil Nadu", "Private"],
  [273, "Sri Venkateswara Dental College & Hospital", "Kancheepuram", "Tamil Nadu", "Private"],
  [275, "Tagore Dental College & Hospital", "Chennai", "Tamil Nadu", "Private"],
  [276, "Tamil Nadu Government Dental College", "Chennai", "Tamil Nadu", "Government"],
  [277, "Thai Moogambigai Dental College & Hospital", "Chennai", "Tamil Nadu", "Private"],
  [278, "Vinayaka Mission's Sankarachariyar Dental College", "Salem", "Tamil Nadu", "Private"],
  [279, "Vivekanandha Dental College for Women", "Elayampalayam", "Tamil Nadu", "Private"],
  [281, "Government Dental College and Hospital", "Hyderabad", "Telangana", "Government"],
  [282, "Kamineni Institute of Dental Sciences", "Nalgonda", "Telangana", "Private"],
  [283, "Malla Reddy Dental College for Women", "Hyderabad", "Telangana", "Private"],
  [284, "Malla Reddy Institute of Dental Sciences", "Hyderabad", "Telangana", "Private"],
  [285, "Mamata Dental College", "Khammam", "Telangana", "Private"],
  [286, "Mamata Institute of Dental Sciences", "Khammam", "Telangana", "Private"],
  [287, "Meghna Institute of Dental Sciences", "Nizamabad", "Telangana", "Private"],
  [288, "MNR Dental College & Hospital", "Medak", "Telangana", "Private"],
  [289, "Panineeya Mahavidyalaya Institute", "Hyderabad", "Telangana", "Private"],
  [290, "Sri Balaji Dental College", "Hyderabad", "Telangana", "Private"],
  [291, "Sri Sai College of Dental Surgery", "Vikarabad", "Telangana", "Private"],
  [292, "Sri Venkata Sai Institute of Dental Sciences", "Hyderabad", "Telangana", "Private"],
  [293, "Tirumala Institute of Dental Sciences & Research", "Hyderabad", "Telangana", "Private"],
  [294, "Agartala Government Dental College and IGM Hospital", "Agartala", "Tripura", "Government"],
  [295, "Babu Banarasi Das College of Dental Sciences", "Lucknow", "Uttar Pradesh", "Private"],
  [296, "Career Institute of Dental Sciences & Hospital", "Lucknow", "Uttar Pradesh", "Private"],
  [297, "Chandra Dental College & Hospital", "Safedabad", "Uttar Pradesh", "Private"],
  [298, "D.J. College of Dental Sciences & Research", "Modi Nagar", "Uttar Pradesh", "Private"],
  [299, "Dental College Azamgarh", "Azamgarh", "Uttar Pradesh", "Private"],
  [303, "I.T.S. Centre for Dental Studies & Research", "Ghaziabad", "Uttar Pradesh", "Private"],
  [304, "I.T.S. Dental College, Hospital & Research Centre", "Greater Noida", "Uttar Pradesh", "Private"],
  [305, "Inderprastha Dental College & Hospital", "Ghaziabad", "Uttar Pradesh", "Private"],
  [306, "Institute of Dental Sciences", "Bareilly", "Uttar Pradesh", "Private"],
  [307, "Institute of Dental Studies & Technology", "Modinagar", "Uttar Pradesh", "Private"],
  [308, "K.D. Dental College", "Mathura", "Uttar Pradesh", "Private"],
  [309, "Kalka Dental College & Hospital", "Meerut", "Uttar Pradesh", "Private"],
  [310, "Kothiwal Dental College & Research Centre", "Moradabad", "Uttar Pradesh", "Private"],
  [311, "Maharana Pratap Dental College & Hospital", "Kanpur", "Uttar Pradesh", "Private"],
  [312, "Purvanchal Institute of Dental Sciences", "Gorakhpur", "Uttar Pradesh", "Private"],
  [313, "Rama Dental College, Hospital & Research Centre", "Kanpur", "Uttar Pradesh", "Private"],
  [314, "Santosh Dental College & Hospital", "Ghaziabad", "Uttar Pradesh", "Private"],
  [315, "Saraswati Dental College", "Lucknow", "Uttar Pradesh", "Private"],
  [316, "Sardar Patel Post Graduate Institute", "Lucknow", "Uttar Pradesh", "Private"],
  [317, "School of Dental Sciences", "Greater Noida", "Uttar Pradesh", "Private"],
  [318, "Shree Bankey Bihari Dental College", "Masuri", "Uttar Pradesh", "Private"],
  [319, "Subharati Dental College", "Meerut", "Uttar Pradesh", "Private"],
  [320, "Teerthanker Mahaveer Dental College & Research", "Moradabad", "Uttar Pradesh", "Private"],
  [321, "U.P. Rural Institute of Medical Sciences & Research", "Saifai", "Uttar Pradesh", "Government"],
  [322, "Seema Dental College & Hospital", "Rishikesh", "Uttarakhand", "Private"],
  [323, "Uttaranchal Dental College & Medical Research", "Dehradun", "Uttarakhand", "Private"],
  [324, "Burdwan Dental College", "Bardhaman", "West Bengal", "Government"],
  [325, "Dr. R. Ahmed Dental College & Hospital", "Kolkata", "West Bengal", "Government"],
  [326, "Gurunanak Institute of Dental Science & Research", "Kolkata", "West Bengal", "Private"],
  [327, "Haldia Institute of Dental Sciences & Research", "Haldia", "West Bengal", "Private"],
  [328, "Kusum Devi Sunderlal Dugar Jain Dental College", "Kolkata", "West Bengal", "Private"],
  [329, "Sanaka Institute of Dental Sciences", "Durgapur", "West Bengal", "Private"],
  [330, "The North Bengal Dental College", "Siliguri", "West Bengal", "Government"],
];

function moneyFor(type: string): { feesNum: number; feesLabel: string } {
  if (type === "Government") return { feesNum: 150000, feesLabel: "₹1.5 L" };
  return { feesNum: 1200000, feesLabel: "₹12.0 L" };
}

async function upsertRow([, name, city, state, type]: Row, streamId: number) {
  const cityId = await ensureCity(prisma, city, state);
  const slug = await uniqueCollegeSlug(prisma, name, city);
  const m = moneyFor(type);
  const seo = buildSeoText({ name, city, state, stream: "Dental", type, feesLabel: m.feesLabel, examName: "NEET" });
  const data = {
    name,
    location: `${city}, ${state}`,
    state,
    type: toCollegeType(type),
    feesNum: m.feesNum,
    feesLabel: m.feesLabel,
    examName: "NEET",
    about: seo.descriptionLong,
    descriptionLong: seo.descriptionLong,
    metaTitle: seo.metaTitle,
    metaDescription: seo.metaDescription,
    source: "manual:dci",
    published: true,
    streamId,
    cityId,
  };
  const existing = await prisma.college.findUnique({ where: { slug }, select: { id: true } });
  if (existing) return; // already seeded (e.g. by seed:dental NIRF pass) — don't clobber richer data
  await prisma.college.create({ data: { ...data, slug } });
}

async function run() {
  const streamId = await ensureStream(prisma, "Dental");
  let created = 0;
  for (const row of DCI) {
    const before = await prisma.college.count({ where: { streamId } });
    await upsertRow(row, streamId);
    const after = await prisma.college.count({ where: { streamId } });
    if (after > before) created++;
  }
  console.log(`DCI dental colleges processed: ${DCI.length}. New rows created: ${created}.`);

  await prisma.$executeRaw`UPDATE "Stream" AS s SET "collegeCount" = (SELECT COUNT(*) FROM "College" c WHERE c."streamId" = s.id)`;
  await prisma.$executeRaw`UPDATE "City" AS ci SET "collegeCount" = (SELECT COUNT(*) FROM "College" c WHERE c."cityId" = ci.id)`;
  const total = await prisma.college.count({ where: { streamId } });
  console.log(`\nDone. Dental stream now has ${total} colleges total.`);
}

run()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
